import {deepClone,uid} from '../core/utils.js';
export const triggers=[['click','عند الضغط'],['hover','عند المرور'],['load','عند الظهور'],['focus','عند التركيز'],['input','أثناء الكتابة'],['scroll','عند الظهور أثناء التمرير']];
export const motions=[['fade','ظهور لطيف'],['slide','انزلاق خفيف'],['zoom','تكبير بسيط'],['pulse','نبض'],['glow','وهج'],['shake','اهتزاز'],['bounce','قفزة']];
export function makeInteraction(sourceId,trigger='click',action='motion',options={}){return {id:uid('int'),sourceId,trigger,enabled:true,action,options:{motion:'fade',duration:420,targetId:sourceId,pageId:null,anchor:'',...options}}}
export function upsertInteraction(project,i){project.interactions=project.interactions||[];const n=project.interactions.findIndex(x=>x.id===i.id);if(n<0)project.interactions.push(deepClone(i));else project.interactions[n]=deepClone(i)}
export const removeInteraction=(p,id)=>p.interactions=(p.interactions||[]).filter(x=>x.id!==id);
export const interactionsFor=(p,id)=>(p.interactions||[]).filter(x=>x.sourceId===id&&x.enabled!==false);
export const triggerLabel=t=>Object.fromEntries(triggers)[t]||t;
export const motionLabel=t=>Object.fromEntries(motions)[t]||t;
const selectorFor=id=>{if(!id)return '';const esc=globalThis.CSS?.escape?CSS.escape(id):String(id).replace(/(["\\])/g,'\\$1');return `[data-node-id="${esc}"],[data-runtime-id="${esc}"]`};
function motion(el,m='fade',duration=420){if(!el)return;for(const c of [...el.classList])if(c.startsWith('motion-'))el.classList.remove(c);void el.offsetWidth;el.style.animationDuration=`${Number(duration)||420}ms`;el.classList.add('motion-'+m);const done=()=>{el.classList.remove('motion-'+m);el.style.animationDuration=''};el.addEventListener('animationend',done,{once:true})}
export function createRuntime({document,project,navigate,scrollToAnchor}){const cleanups=[],find=id=>{const s=selectorFor(id);return s?document.querySelector(s):null},add=(el,t,fn)=>{el.addEventListener(t,fn);cleanups.push(()=>el.removeEventListener(t,fn))},run=i=>{const o=i.options||{},target=find(o.targetId||i.sourceId);switch(i.action){case'motion':motion(target,o.motion,o.duration);break;case'show':if(target)target.hidden=false;break;case'hide':if(target)target.hidden=true;break;case'toggle':if(target)target.hidden=!target.hidden;break;case'scroll':if(o.anchor)scrollToAnchor?.(o.anchor);break;case'page':if(o.pageId)navigate?.(o.pageId);break;case'url':if(o.url)location.href=o.url;break}};
for(const i of project.interactions||[]){if(i.enabled===false)continue;const source=find(i.sourceId);if(!source)continue;const one=()=>run(i);switch(i.trigger){case'load':{const t=setTimeout(one,40);cleanups.push(()=>clearTimeout(t));break}case'click':add(source,'click',e=>{if(source.tagName==='A'&&(source.getAttribute('href')||'#')==='#')e.preventDefault();one()});break;case'hover':add(source,'pointerenter',one);break;case'focus':add(source,'focus',one);break;case'input':add(source,'input',one);break;case'scroll':if('IntersectionObserver' in globalThis){const o=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting))one()},{threshold:.15});o.observe(source);cleanups.push(()=>o.disconnect())}break;default:break}}return()=>cleanups.splice(0).forEach(fn=>fn())}