import {clamp} from '../core/utils.js';

export const DEVICE_ORDER=['desktop','tablet','mobile'];
const px=v=>typeof v==='number'?`${v}px`:v;
export function resolveStyle(node,device='desktop',theme={}){const s={...(node.style||{})};const r=node.responsive?.[device]||{};Object.assign(s,r);if(['grid','columns'].includes(node.type)){s.display=s.display||'grid';s.gridTemplateColumns=s.gridTemplateColumns||`repeat(${clamp(Number(node.props?.count||3),1,6)},minmax(0,1fr))`;s.gap=s.gap??node.props?.gap??16}else if(node.type==='stack'){s.display=s.display||'flex';s.flexDirection=s.flexDirection||'column';s.gap=s.gap??node.props?.gap??12}if(!s.color&&theme.text)s.color=theme.text;if(s.radius!=null&&!s.borderRadius)s.borderRadius=px(s.radius);if(s.padding!=null&&!s.paddingBlock)s.paddingBlock=px(s.padding);if(s.paddingY!=null)s.paddingBlock=px(s.paddingY);if(s.paddingX!=null)s.paddingInline=px(s.paddingX);if(s.shadow)s.boxShadow='0 12px 30px rgba(25,30,55,.10)';if(s.width!=null)s.width=typeof s.width==='number'?`${s.width}px`:s.width;if(s.height!=null)s.height=typeof s.height==='number'?`${s.height}px`:s.height;if(s.maxWidth!=null)s.maxWidth=px(s.maxWidth);if(s.minWidth!=null)s.minWidth=px(s.minWidth);return s}
export function styleObjectToCss(s){return Object.entries(s).filter(([k,v])=>v!==undefined&&v!==null&&v!==''&&k!=='shadow'&&k!=='radius'&&k!=='paddingY'&&k!=='paddingX').map(([k,v])=>`${camelToKebab(k)}:${String(v).match(/^\d+(\.\d+)?$/)&&!['opacity','zIndex','fontWeight','lineHeight','flexGrow','flexShrink','order'].includes(k)?`${v}px`:v};`).join('')}
const camelToKebab=s=>s.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`);
export function normalizeLayout(node){const s=node.style||{};if(['grid','columns'].includes(node.type)){s.display='grid';s.gridTemplateColumns=s.gridTemplateColumns||`repeat(${clamp(Number(node.props?.count||3),1,6)},minmax(0,1fr))`;s.gap=s.gap??node.props?.gap??16}else if(['stack'].includes(node.type)){s.display='flex';s.flexDirection='column';s.gap=s.gap??node.props?.gap??12}else if(node.type==='spaced'){s.display='flex';s.justifyContent='space-between';s.alignItems='center';s.gap=s.gap??12}node.style=s;return s}
export function deviceScale(base,from,to){const ratios={desktop:1,tablet:.85,mobile:.62};return clamp((Number(base)||0)*(ratios[to]/ratios[from]),0,9999)}
export function propagateStyle(node,device,patch){if(!node)return;node.responsive=node.responsive||{};for(const d of DEVICE_ORDER){if(d===device)continue;node.responsive[d]={...(node.responsive[d]||{})};for(const [k,v] of Object.entries(patch)){if(['fontSize','paddingY','paddingX','gap','height','marginTop','marginBottom'].includes(k)&&typeof v==='number'){node.responsive[d][k]=deviceScale(v,device,d)}else if(k==='width'&&typeof v==='number'){node.responsive[d][k]=`${deviceScale(v,device,d)}px`}else node.responsive[d][k]=v}}}
