import {renderPage} from './renderer.js';
import {createRuntime} from './interaction.js';
import {addNode,insertNodeAtDrop} from '../core/commands.js';
import {clamp} from '../core/utils.js';

export class WorkspaceEngine{
 constructor(store,inspector,panels){this.store=store;this.inspector=inspector;this.panels=panels;this.runtimeCleanup=null;this.boundDrop=false;this.wired=false;}
 mount(){this.pageCanvas=document.getElementById('pageCanvas');this.deviceFrame=document.getElementById('deviceFrame');this.viewport=document.getElementById('canvasViewport');this.stage=document.getElementById('canvasStage');this.wireCanvas();this.wireControls();this.render()}
 activePage(){return this.store.activePage()}
 wireCanvas(){if(this.wired)return;this.wired=true;this.pageCanvas.addEventListener('click',e=>{const wrap=e.target.closest('.node-wrap');if(!wrap)return;if(this.store.ui.interactionMode)return;this.store.setUI({selected:wrap.dataset.nodeId,rightOpen:true})});this.pageCanvas.addEventListener('dragover',e=>{e.preventDefault();this.pageCanvas.classList.add('drop-target')});this.pageCanvas.addEventListener('dragleave',()=>this.pageCanvas.classList.remove('drop-target'));this.pageCanvas.addEventListener('drop',e=>{e.preventDefault();this.pageCanvas.classList.remove('drop-target');const type=e.dataTransfer.getData('application/bunaa-type');if(!type)return;const target=e.target.closest?.('.node-wrap')?.dataset?.nodeId||null;insertNodeAtDrop(this.store,type,target);this.render();this.panels.setTab('layers')});document.getElementById('dropFooter').addEventListener('dragover',e=>e.preventDefault());document.getElementById('dropFooter').addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer.getData('application/bunaa-type');if(type)this.addElement(type)});}
 wireControls(){document.getElementById('zoomIn').onclick=()=>this.setZoom(this.store.ui.zoom+.1);document.getElementById('zoomOut').onclick=()=>this.setZoom(this.store.ui.zoom-.1);document.getElementById('zoomFit').onclick=()=>this.fit();document.getElementById('gridBtn').onclick=()=>{this.store.setUI({grid:!this.store.ui.grid});this.render()};document.getElementById('structureBtn').onclick=()=>{this.store.setUI({leftTab:'layers'});this.panels.setTab('layers')};document.getElementById('focusBtn').onclick=()=>{this.store.setUI({focus:!this.store.ui.focus});this.renderShell()};this.setupPan();}
 setupPan(){let p=null;this.viewport.addEventListener('pointerdown',e=>{if(e.button!==1&&!(e.button===0&&e.target.closest('#canvasStage')&&e.ctrlKey))return;p={x:e.clientX,y:e.clientY,sx:this.viewport.scrollLeft,sy:this.viewport.scrollTop};this.viewport.setPointerCapture(e.pointerId);this.viewport.style.cursor='grabbing'});this.viewport.addEventListener('pointermove',e=>{if(!p)return;this.viewport.scrollLeft=p.sx-(e.clientX-p.x);this.viewport.scrollTop=p.sy-(e.clientY-p.y)});this.viewport.addEventListener('pointerup',e=>{p=null;this.viewport.style.cursor=''})}
 setZoom(z){z=clamp(z,.55,1.5);this.store.setUI({zoom:z});this.applyZoom()}
 applyZoom(){const z=this.store.ui.zoom;this.stage.style.transform=`scale(${z})`;this.stage.style.width=`calc(var(--site-width,1180px) * ${z})`;document.getElementById('zoomLabel').textContent=Math.round(z*100)+'%'}
 fit(){const available=this.viewport.clientWidth-90;const base=this.deviceWidth();this.setZoom(clamp(available/base,.55,1.2));this.viewport.scrollTop=0;this.viewport.scrollLeft=Math.max(0,(this.viewport.scrollWidth-this.viewport.clientWidth)/2)}
 deviceWidth(){return this.store.project.devices[this.store.ui.device]?.width||1180}
 addElement(type){addNode(this.store,type);this.render();this.panels.setTab('layers')}
 toggleInteraction(on){this.store.setUI({interactionMode:on});this.render();if(on)this.runRuntime();else this.cleanupRuntime()}
 runRuntime(){this.cleanupRuntime();this.runtimeCleanup=createRuntime({document,navigate:id=>{this.store.transact('تنقل',p=>{p.activePageId=id},{record:false});this.render()},scrollToAnchor:a=>this.scrollToAnchor(a)});}
 cleanupRuntime(){if(this.runtimeCleanup){this.runtimeCleanup();this.runtimeCleanup=null}}
 scrollToAnchor(id){const x=this.pageCanvas.querySelector(`[data-node-id="${CSS.escape(id)}"]`);x?.scrollIntoView({behavior:'smooth',block:'center'})}
 render(){const p=this.activePage();renderPage(p,this.pageCanvas,{project:this.store.project,theme:this.store.project.theme,device:this.store.ui.device,selectedId:this.store.ui.interactionMode?null:this.store.ui.selected});this.deviceFrame.className=`site-frame ${this.store.ui.device}`;this.pageCanvas.classList.toggle('show-grid',this.store.ui.grid);document.getElementById('canvasPageTitle').textContent=p.name;document.getElementById('canvasModeLabel').textContent=this.store.ui.interactionMode?'وضع تجربة التفاعل':'وضع البناء';document.getElementById('selectionInfo').textContent=this.store.ui.selected?`العنصر: ${this.store.find(this.store.ui.selected)?.node?.props?.label||this.store.find(this.store.ui.selected)?.node?.type||''}`:'لم يتم تحديد عنصر';document.getElementById('pageCountLabel').textContent=`${this.store.project.pages.length} ${this.store.project.pages.length===1?'صفحة':'صفحات'}`;document.getElementById('elementCountLabel').textContent=`${this.store.nodeCount()} عنصر`;document.getElementById('zoomLabel').textContent=Math.round(this.store.ui.zoom*100)+'%';document.getElementById('dropEmpty').classList.toggle('hidden',(p.nodes||[]).length>0);this.applyZoom();if(this.store.ui.interactionMode)this.runRuntime();}
 renderShell(){const main=document.querySelector('.workspace-main');main.classList.toggle('focus-mode',this.store.ui.focus);document.body.classList.toggle('focus-canvas',this.store.ui.focus)}
 sync(){this.render();this.renderShell();this.refreshPageSelect()}
 refreshPageSelect(){const s=document.getElementById('pageSelect');s.innerHTML=this.store.project.pages.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');s.value=this.store.project.activePageId}
}
