const {safeUrl,safeMediaUrl} = __require("src/core/utils.js");
const {resolveStyle,styleObjectToCss} = __require("src/engine/layout.js");
const {applyThemeVars} = __require("src/core/design-system.js");
const {pageAnchor,resolvePageTarget} = __require("src/engine/routing.js");
const {resolveSymbol} = __require("src/core/symbols.js");
const {getCollectionItems} = __require("src/core/cms.js");
const {findAsset} = __require("src/core/assets.js");

const el=(tag,cls='')=>{const node=document.createElement(tag);if(cls)node.className=cls;return node};
const textNode=(text,tag='p')=>{const node=el(tag);node.textContent=String(text??'');return node};

function safeWrapperTag(node){const requested=node.semantic?.tag&&/^[a-z][a-z0-9-]*$/i.test(node.semantic.tag)?String(node.semantic.tag).toLowerCase():'div';const interactiveTags=new Set(['a','button','form','input','textarea','select','option','label','nav','footer']);return interactiveTags.has(requested)?'div':requested}
function wrap(node,ctx){const semanticTag=safeWrapperTag(node);const w=el(semanticTag,'node-wrap');w.dataset[ctx.export?'runtimeId':'nodeId']=node.id;w.dataset.bunaaType=node.type;if(node.locked)w.dataset.locked='1';if(ctx.device&&node.visibility&&node.visibility[ctx.device]===false)w.hidden=true;if(!ctx.export){w.dataset.type=node.type;w.dataset.label=node.props?.label||node.props?.title||node.props?.text||node.type}for(const cls of node.classes||[])w.classList.add(String(cls));for(const [key,value] of Object.entries(node.attrs||{})){const attrName=String(key||'').trim();if(value!=null&&attrName&&!/^on[a-z]+$/i.test(attrName)&&attrName.toLowerCase()!=='srcdoc'&&attrName.toLowerCase()!=='style')w.setAttribute(attrName,String(value))}if(node.semantic?.role)w.setAttribute('role',node.semantic.role);if(node.semantic?.ariaLabel)w.setAttribute('aria-label',node.semantic.ariaLabel);const content=el('div','node-content');content.dataset.bunaaContent='1';const resolved=resolveStyle(node,ctx.device,ctx.theme,ctx.styleLibrary,ctx.project);if(resolved.translate){w.style.translate=String(resolved.translate);delete resolved.translate}content.style.cssText=styleObjectToCss(resolved);renderContent(content,node,ctx);if(node.type==='image'){const image=content.querySelector('img');if(image){image.style.width='100%';image.style.height='100%';image.style.objectFit=resolved.objectFit||'cover'}}for(const child of node.children||[])content.appendChild(wrap(child,ctx));w.appendChild(content);if(!ctx.export&&ctx.multiSelectedIds?.includes(node.id))w.classList.add('multi-selected');if(!ctx.export&&ctx.selectedId===node.id){w.classList.add('selected');if(!node.locked){for(const direction of ['nw','n','ne','e','se','s','sw','w']){const handle=el('button','canvas-selection-handle');handle.type='button';handle.dataset.canvasResize=direction;handle.setAttribute('aria-label','تغيير حجم العنصر '+direction);handle.tabIndex=-1;content.appendChild(handle)}}}return w}


function boundValue(node,ctx,key,fallback=''){const variable=node?.props?.bindingVariable;if(variable&&ctx.project?.variables){const source=ctx.project.variables[variable];if(source&&Object.prototype.hasOwnProperty.call(source,'value'))return String(source.value)}return String(node?.props?.[key]??fallback)}

function assetSrc(node,kind,ctx){const asset=findAsset(ctx.project,node?.props?.assetId);if(!asset)return safeMediaUrl(node?.props?.src||node?.props?.url||'',kind)||'';return ctx.export&&ctx.assetMap?.get(asset.id)?ctx.assetMap.get(asset.id):asset.data}
function isDirectMediaSource(src,kind){const value=String(src||'');if(new RegExp('^data:'+kind+'/','i').test(value))return true;try{const path=new URL(value,typeof location!=='undefined'?location.href:'https://local.invalid/').pathname;return kind==='video'?/\\.(mp4|m4v|webm|ogv|ogg|mov|m3u8|mpd)$/i.test(path):kind==='audio'?/\\.(mp3|m4a|aac|wav|ogg|oga|opus|flac|wma)$/i.test(path):false}catch{return false}}
function externalVideoEmbedUrl(value){try{const url=new URL(String(value||''));if(!/^https?:$/.test(url.protocol))return '';const host=url.hostname.toLowerCase().replace(/^www\\./,'');let id='';if(host==='youtu.be'){id=url.pathname.split('/').filter(Boolean)[0]||'';return id?'https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id):''}if(host==='youtube.com'||host==='m.youtube.com'||host==='music.youtube.com'||host==='youtube-nocookie.com'){if(url.pathname==='/watch')id=url.searchParams.get('v')||'';else{const match=url.pathname.match(/^\\/(?:embed|shorts|live|v)\\/([^/?]+)/);if(match)id=match[1]}return id?'https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id):(/^\\/embed\\//.test(url.pathname)?url.href:'')}if(host==='vimeo.com'||host==='player.vimeo.com'){const match=url.pathname.match(/\\/(?:video\\/)?(\\d+)/);return match?'https://player.vimeo.com/video/'+match[1]:url.href}return ''}catch{return ''}}
function externalAudioEmbedUrl(value){try{const url=new URL(String(value||''));if(!/^https?:$/.test(url.protocol))return '';const host=url.hostname.toLowerCase().replace(/^www\\./,'');if((host==='soundcloud.com'||host==='m.soundcloud.com')&&!url.pathname.startsWith('/player/'))return 'https://w.soundcloud.com/player/?url='+encodeURIComponent(url.href)+'&auto_play=false&visual=true';if(host==='open.spotify.com'&&!url.pathname.startsWith('/embed/'))return 'https://open.spotify.com/embed'+url.pathname;return ''}catch{return ''}}


function pageHref(page,ctx){if(!page)return '#';if(ctx.export&&ctx.pageMap)return ctx.pageMap.get(page.id)||'#';return pageAnchor(page.id)}
function resolveHref(url,ctx){const target=resolvePageTarget(url,ctx.project);return target?pageHref(target,ctx):safeUrl(url||'#')}
function assetById(ctx,id){return (ctx.project?.assets||[]).find(asset=>asset.id===id)||null}
function assetTile(asset,ctx){
  const card=el('article','built-media-tile');const source=asset?(ctx.export&&ctx.assetMap?.get(asset.id)?ctx.assetMap.get(asset.id):asset.data):'';
  if(asset?.kind==='image'){const img=el('img');img.src=source||placeholder(asset.name);img.alt=asset.alt||asset.name;img.loading='lazy';card.appendChild(img)}
  else if(asset?.kind==='video'){const video=el('video');video.controls=true;video.preload='metadata';video.playsInline=true;if(source)video.src=source;card.appendChild(video)}
  else if(asset?.kind==='audio'){const audio=el('audio');audio.controls=true;audio.preload='metadata';if(source)audio.src=source;card.appendChild(audio)}
  else if(asset){const a=el('a','built-file-link');a.href=source||'#';a.textContent=`▤ ${asset.name}.${asset.extension||'bin'}`;a.download=asset.filename||'';card.appendChild(a)}
  else card.appendChild(textNode('اختر ملفات من مكتبة الوسائط.'));
  if(asset){const caption=el('small','built-media-caption');caption.textContent=asset.alt||asset.originalName||asset.filename;card.appendChild(caption)}return card;
}
function walkNodes(nodes,fn){for(const node of nodes||[]){fn(node);walkNodes(node.children,fn)}}
function findNodeOnPage(page,id){let found=null;walkNodes(page?.nodes,n=>{if(n.id===id)found=n});return found}
function plainTextFromNode(node){if(!node)return '';const p=node.props||{};const keys=['title','text','description','question','answer','quote','name','label','body'];return keys.map(k=>p[k]).filter(v=>typeof v==='string'&&v.trim()).join('\n')}
const SAFE_SNIPPET_TAGS=new Set(['h1','h2','h3','h4','h5','h6','p','span','strong','em','b','i','u','s','ul','ol','li','a','img','blockquote','pre','code','br','hr','figure','figcaption','table','thead','tbody','tr','th','td','div','section','small','mark','sup','sub','del','ins']);
function safeSnippetUrl(value,tag,attr){const v=String(value||'').trim();if(!v)return '';if(/^(javascript|vbscript):/i.test(v))return '';if(/^data:/i.test(v))return tag==='img'&&attr==='src'&&/^data:image\/(png|jpeg|gif|webp|svg\+xml);/i.test(v)?v:'';if(/^(https?:|mailto:|tel:|#|\/|\.\.?\/)/i.test(v))return v;return ''}
function appendSafeSnippet(root,markup){
  let parsed;try{parsed=new DOMParser().parseFromString(String(markup||''),'text/html')}catch{return}
  const copy=(source,parent)=>{for(const child of [...source.childNodes]){if(child.nodeType===3){parent.appendChild(document.createTextNode(child.nodeValue||''));continue}if(child.nodeType!==1)continue;const tag=child.tagName.toLowerCase();if(['script','style','iframe','object','embed','form','input','button','textarea','select','option','link','meta','base','template','svg','math'].includes(tag))continue;if(!SAFE_SNIPPET_TAGS.has(tag)){copy(child,parent);continue}const target=document.createElement(tag);for(const attr of [...child.attributes]){const name=attr.name.toLowerCase();if(name.startsWith('on')||['style','srcdoc','formaction','action','contenteditable'].includes(name))continue;if(['href','src'].includes(name)){const value=safeSnippetUrl(attr.value,tag,name);if(value)target.setAttribute(name,value);continue}if(['class','title','alt','width','height','rowspan','colspan','scope','role','aria-label','loading'].includes(name)||/^aria-[a-z-]+$/.test(name)){if(name==='class')target.className=attr.value.split(/\s+/).filter(x=>/^[a-z0-9_-]{1,50}$/i.test(x)).join(' ');else target.setAttribute(name,attr.value.slice(0,300))}}if(tag==='a'&&target.target==='_blank')target.rel='noopener noreferrer';copy(child,target);parent.appendChild(target)}};copy(parsed.body,root)
}

function renderContent(root,node,ctx){const p=node.props||{};switch(node.type){
case'heading':root.appendChild(textNode(boundValue(node,ctx,'text','عنوان'),'h2'));break;
case'text':root.appendChild(textNode(boundValue(node,ctx,'text','نص')));break;
case'button':{const a=el('a','built-button');a.textContent=boundValue(node,ctx,'text','زر');a.href=resolveHref(p.url,ctx);a.dataset.action=p.action||'url';const target=resolvePageTarget(p.url,ctx.project);if(target)a.dataset.pageTarget=target.id;if(p.newTab)a.target='_blank';root.appendChild(a);break}
case'link':{const a=el('a');a.textContent=boundValue(node,ctx,'text','رابط');a.href=resolveHref(p.url,ctx);const target=resolvePageTarget(p.url,ctx.project);if(target)a.dataset.pageTarget=target.id;root.appendChild(a);break}
case'image':{const img=el('img');img.src=safeMediaUrl(node.props?.bindingVariable?boundValue(node,ctx,'src',p.src):p.src,'image')||assetSrc(node,'image',ctx)||placeholder();img.alt=p.alt||'';img.loading='lazy';root.appendChild(img);break}
case'gallery':case'media-grid':{const gallery=el('div',node.type==='gallery'?'built-gallery':'built-media-grid');const ids=Array.isArray(p.assetIds)&&p.assetIds.length?p.assetIds:(ctx.project.assets||[]).filter(a=>node.type==='media-grid'||a.kind==='image').slice(0,Math.max(1,Math.min(24,Number(p.count)||6))).map(a=>a.id);gallery.style.gridTemplateColumns=`repeat(${Math.max(1,Math.min(6,Number(p.columns)||3))},minmax(0,1fr))`;const items=ids.map(id=>assetById(ctx,id)).filter(Boolean);if(items.length)items.forEach(asset=>gallery.appendChild(assetTile(asset,ctx)));else for(let i=0;i<Math.max(1,Math.min(12,Number(p.count)||3));i++){const placeholderAsset={kind:'image',name:`صورة ${i+1}`,alt:`صورة تجريبية ${i+1}`,data:placeholder(`صورة ${i+1}`)};gallery.appendChild(assetTile(placeholderAsset,ctx))}root.appendChild(gallery);break}
case'video-gallery':case'audio-playlist':{const type=node.type==='video-gallery'?'video':'audio';const box=el('div',node.type==='video-gallery'?'built-video-gallery':'built-audio-playlist');if(p.title)box.appendChild(textNode(p.title,'h3'));const assets=(p.assetIds||[]).map(id=>assetById(ctx,id)).filter(a=>a&&a.kind===type);if(node.type==='video-gallery')box.style.gridTemplateColumns='repeat('+Math.max(1,Math.min(4,Number(p.columns)||2))+',minmax(0,1fr))';if(assets.length)assets.forEach(asset=>box.appendChild(assetTile(asset,ctx)));if(p.url){if(type==='audio'){const src=safeMediaUrl(p.url,'audio');const embed=externalAudioEmbedUrl(src);if(embed){const frame=el('iframe','built-audio-embed');frame.src=embed;frame.title=p.title||'صوت خارجي';frame.loading='lazy';box.appendChild(frame)}else if(src){const audio=el('audio');audio.controls=true;audio.preload='metadata';audio.src=src;box.appendChild(audio)}}else{const embed=externalVideoEmbedUrl(p.url);if(embed){const frame=el('iframe');frame.src=embed;frame.title=p.title||'فيديو خارجي';frame.loading='lazy';frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.setAttribute('allowfullscreen','');box.appendChild(frame)}else if(isDirectMediaSource(p.url,'video')){const video=el('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.src=safeMediaUrl(p.url,'video');box.appendChild(video)}else if(safeMediaUrl(p.url,'video')){const frame=el('iframe');frame.src=safeMediaUrl(p.url,'video');frame.title=p.title||'فيديو خارجي';frame.loading='lazy';frame.setAttribute('allowfullscreen','');box.appendChild(frame)}}}if(!assets.length&&!p.url)box.appendChild(textNode(type==='video'?'أضف رابط فيديو خارجيًا أو ارفع مقطعًا من المكتبة.':'أضف رابط صوت خارجيًا أو ارفع ملفًا من المكتبة.'));root.appendChild(box);break}
case'document-viewer':{const asset=assetById(ctx,p.assetId);const src=assetSrc(node,'document',ctx);const isPdf=(asset?.extension||'').toLowerCase()==='pdf'||/application\/pdf/i.test(asset?.type||'');const box=el('div','built-document-viewer');if(p.title)box.appendChild(textNode(p.title,'h3'));if(asset&&src&&isPdf){const frame=el('iframe');frame.src=src;frame.title=p.title||asset.filename||'PDF';frame.loading='lazy';frame.style.width='100%';frame.style.height=`${Math.max(260,Math.min(1400,Number(p.height)||640))}px`;frame.setAttribute('loading','lazy');box.appendChild(frame)}if(asset&&src){const link=el('a','built-file-link');link.href=src;link.textContent=isPdf?'فتح أو تنزيل ملف PDF':`فتح ${asset.filename}`;link.target='_blank';link.rel='noopener';link.download=asset.filename||'';box.appendChild(link)}else box.appendChild(textNode('اختر ملف PDF من خصائص العنصر.'));root.appendChild(box);break}
case'file-card':{const asset=assetById(ctx,p.assetId);const src=assetSrc(node,'document',ctx);const box=el('article','built-file-card');box.append(textNode('▤','strong'),textNode(p.title||asset?.name||'ملف قابل للتنزيل','h3'));if(p.text)box.appendChild(textNode(p.text));if(asset&&src){const link=el('a','built-button');link.href=src;link.textContent=p.button||'فتح الملف';link.download=p.download===false?'':asset.filename||'';link.target=p.download===false?'_blank':'';if(link.target)link.rel='noopener';box.append(link);box.appendChild(textNode(`${asset.filename||asset.name} • ${Math.round((asset.size||0)/1024)} KB`,'small'))}else box.appendChild(textNode('اختر ملفًا من مكتبة الوسائط.'));root.appendChild(box);break}
case'page-embed':{const target=(ctx.project.pages||[]).find(pg=>pg.id===p.pageId);const box=el('div','built-page-embed');box.dataset.pageEmbedContent='1';if(!target){box.appendChild(textNode('اختر صفحة داخلية من خصائص العنصر.'))}else if((ctx.embeddingPages||[]).includes(target.id)){box.appendChild(textNode('توقف تضمين الصفحة لتجنب حلقة لا نهائية.'))}else{const mode=p.mode||'full';if(mode==='text'){const chosen=p.nodeId?findNodeOnPage(target,p.nodeId):null;let value=chosen?plainTextFromNode(chosen):(target.nodes||[]).map(plainTextFromNode).filter(Boolean).join('\n');value=String(value||'').slice(0,Math.max(120,Math.min(10000,Number(p.textLimit)||1800)));box.appendChild(textNode(value||'لا يوجد نص في الصفحة.'))}else{let nodes=target.nodes||[];if(mode==='section'){const chosen=findNodeOnPage(target,p.nodeId);nodes=chosen?[chosen]:[]}if(!nodes.length)box.appendChild(textNode(mode==='section'?'اختر قسمًا من الصفحة المحددة.':'الصفحة لا تحتوي عناصر بعد.'));else{const nested={...ctx,pageId:target.id,embeddingPages:[...(ctx.embeddingPages||[]),target.id]};nodes.forEach(child=>box.appendChild(wrap(child,nested)))}}}root.appendChild(box);break}
case'html-snippet':{const d=el('div','built-html-snippet');appendSafeSnippet(d,p.html||'');root.appendChild(d);break}
case'quote':root.appendChild(textNode(p.text||'اقتباس','blockquote'));break;
case'list':{const ul=el('ul');String(p.items||'').split(/\n+/).filter(Boolean).forEach(x=>ul.appendChild(textNode(x,'li')));root.appendChild(ul);break}
case'divider':root.appendChild(el('hr'));break;
case'spacer':root.appendChild(el('div'));break;
case'section':case'container':case'grid':case'columns':case'stack':case'spaced':case'group':case'hero':break;
case'card':{const c=el('div','built-card');c.append(textNode(p.title||'بطاقة','h3'),textNode(p.text||'وصف مختصر'));if(p.button){const a=el('a');a.href=resolveHref(p.url,ctx);a.textContent=p.button;if(resolvePageTarget(p.url,ctx.project))a.dataset.pageTarget=resolvePageTarget(p.url,ctx.project).id;c.appendChild(a)}root.appendChild(c);break}
case'navbar':{const nav=el('nav','built-nav');nav.appendChild(textNode(p.brand||ctx.project.site?.brand?.name||'الموقع','strong'));const links=el('div','nav-links');const menuId=p.menuId||ctx.project.navigation?.headerMenuId;const menu=ctx.project.navigation?.menus?.find(item=>item.id===menuId);const items=Array.isArray(menu?.items)&&menu.items.length?menu.items:(Array.isArray(p.links)?p.links.map((label,index)=>({label,targetId:p.linkTargets?.[index]})):[]);items.forEach((item,index)=>{const a=el('a');a.textContent=item.label||item.name||`رابط ${index+1}`;const target=ctx.project.pages.find(pg=>pg.id===item.targetId)||ctx.project.pages.find(pg=>pg.name===a.textContent)||ctx.project.pages[index]||ctx.project.pages[0];a.href=item.type==='url'?safeUrl(item.url||'#'):pageHref(target,ctx);if(item.newTab)a.target='_blank';links.appendChild(a)});nav.appendChild(links);root.appendChild(nav);break}
case'footer':{const f=el('footer');f.append(textNode(p.brand||'الموقع','strong'),textNode(p.text||''));root.appendChild(f);break}
case'alert':root.appendChild(textNode(p.text||'تنبيه'));break;
case'badge':root.appendChild(textNode(p.text||'جديد','span'));break;
case'progress':{const bar=el('div','built-progress'),fill=el('div'),value=Math.max(0,Math.min(100,Number(p.value)||0));fill.style.width=`${value}%`;bar.append(fill,textNode(p.label||`${value}%`));root.appendChild(bar);break}
case'stats':{const g=el('div','built-stats');(p.items||[]).forEach(([v,l])=>{const d=el('div');d.append(textNode(v,'strong'),textNode(l));g.appendChild(d)});root.appendChild(g);break}
case'timeline':{const g=el('div','built-timeline');(p.items||[]).forEach(([v,l])=>{const d=el('div');d.append(textNode(v,'strong'),textNode(l));g.appendChild(d)});root.appendChild(g);break}
case'pricing':{const g=el('div','built-pricing');(p.plans||[]).forEach(([n,v])=>{const d=el('div');d.append(textNode(n,'h3'),textNode(v,'strong'));g.appendChild(d)});root.appendChild(g);break}
case'testimonial':{const d=el('div','built-testimonial');d.append(textNode(`“${p.quote||''}”`),textNode(p.name||'عميل','strong'));root.appendChild(d);break}
case'tabs':{const g=el('div','built-tabs');const items=p.items||[];const panels=[];const buttons=[];items.forEach((item,i)=>{const b=el('button');b.type='button';b.textContent=item;const panel=textNode(`محتوى ${item}`);panel.className=i?'tab-panel hidden':'tab-panel';b.onclick=()=>{panels.forEach(x=>x.classList.add('hidden'));panel.classList.remove('hidden');buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active')};if(i===0)b.classList.add('active');buttons.push(b);panels.push(panel);g.append(b,panel)});root.appendChild(g);break}
case'accordion':{const g=el('div','built-accordion');(p.items||[]).forEach(q=>{const d=el('details');d.append(textNode(q,'summary'),textNode('أضف الإجابة من التخصيص.'));g.appendChild(d)});root.appendChild(g);break}
case'dropdown':{const s=el('select');(p.items||[]).forEach(x=>s.appendChild(textNode(x,'option')));root.appendChild(s);break}
case'input':case'search':case'file':{const label=textNode(p.label||'حقل','label'),input=el('input');input.type=node.type==='search'?'search':node.type==='file'?'file':(p.type||'text');input.placeholder=p.placeholder||'';root.append(label,input);break}
case'textarea':{root.append(textNode(p.label||'رسالة','label'),Object.assign(el('textarea'),{placeholder:p.placeholder||''}));break}
case'select':{root.append(textNode(p.label||'اختيار','label'));const s=el('select');(p.items||[]).forEach(x=>s.appendChild(textNode(x,'option')));root.appendChild(s);break}
case'checkbox':case'radio':{const label=el('label');const input=el('input');input.type=node.type;label.append(input,textNode(p.label||'اختيار'));root.appendChild(label);break}
case'form':{const f=el('form','built-form');f.noValidate=true;f.addEventListener('submit',e=>e.preventDefault());f.appendChild(textNode(p.submitLabel||'النموذج','strong'));root.appendChild(f);break;}
case'video':{const external=safeMediaUrl(p.url,'video');const asset=findAsset(ctx.project,p.assetId);const src=external||assetSrc(node,'video',ctx);const embed=externalVideoEmbedUrl(src);if(embed){const iframe=el('iframe');iframe.src=embed;iframe.title=p.title||'فيديو';iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.setAttribute('allowfullscreen','');iframe.referrerPolicy='strict-origin-when-cross-origin';root.appendChild(iframe)}else if(isDirectMediaSource(src,'video')||asset?.kind==='video'||/^assets\\//i.test(src)){const video=el('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.src=src;video.title=p.title||'فيديو';if(p.poster)video.poster=safeMediaUrl(p.poster,'image');root.appendChild(video)}else if(src){const iframe=el('iframe');iframe.src=src;iframe.title=p.title||'فيديو';iframe.loading='lazy';iframe.allow='fullscreen; picture-in-picture';iframe.setAttribute('allowfullscreen','');root.appendChild(iframe)}else root.appendChild(textNode('أضف رابط فيديو أو اختر ملفًا من مكتبة الوسائط.'));break}
case'audio':{const audioUrl=safeMediaUrl(p.url??p.src,'audio');const asset=findAsset(ctx.project,p.assetId);const src=audioUrl||assetSrc(node,'audio',ctx);const embed=externalAudioEmbedUrl(src);if(embed){const iframe=el('iframe','built-audio-embed');iframe.src=embed;iframe.title=p.title||'مشغل صوت';iframe.loading='lazy';iframe.allow='autoplay; clipboard-write; encrypted-media';root.appendChild(iframe)}else{const audio=el('audio');audio.controls=true;audio.preload='metadata';if(src)audio.src=src;audio.setAttribute('aria-label',p.title||'مشغل صوت');root.appendChild(audio)}break}
case'table':{const table=el('table'),thead=el('thead'),tr=el('tr');(p.headers||[]).forEach(h=>tr.appendChild(textNode(h,'th')));thead.appendChild(tr);const tbody=el('tbody');(p.rows||[]).forEach(row=>{const r=el('tr');row.forEach(v=>r.appendChild(textNode(v,'td')));tbody.appendChild(r)});table.append(thead,tbody);root.appendChild(table);break}
case'chart':{const g=el('div','built-chart');(p.values||[40,60,80]).forEach(v=>{const b=el('i');b.style.height=`${Math.max(10,Math.min(100,Number(v)||0))}%`;g.appendChild(b)});root.appendChild(g);break}
case'calendar':root.appendChild(textNode(p.month||'هذا الشهر','div'));break;
case'product':{const c=el('div','built-product');c.append(textNode(p.name||'منتج','h3'),textNode(`${p.price||''} ${p.currency||''}`,'strong'));const a=el('a');a.href=resolveHref(p.url,ctx);a.textContent=p.cta||'اختيار';c.appendChild(a);root.appendChild(c);break}
case'faq':{const d=el('details','built-faq');d.append(textNode(p.question||'سؤال','summary'),textNode(p.answer||''));root.appendChild(d);break}
case'rating':root.appendChild(textNode('★'.repeat(Math.max(0,Math.min(5,Number(p.value)||0))),'div'));break;
case'counter':root.appendChild(textNode(`${p.value||0}${p.suffix||''}`,'div'));break;
case'social':{const g=el('div','built-social');(p.items||[]).forEach(x=>{const a=el('a');a.href=safeUrl(p.urls?.[x]||'#');a.textContent=x;g.appendChild(a)});root.appendChild(g);break}
case'gradient':case'glass':case'marquee':root.appendChild(textNode(p.text||''));break;
case'richtext':{const d=el('div','richtext');d.textContent=String(p.text||p.html||'');root.appendChild(d);break}
case'avatar':{const img=el('img','built-avatar');img.src=assetSrc(node,'image',ctx)||safeMediaUrl(p.src,'image')||placeholder(p.name||'ش');img.alt=p.name||'';root.appendChild(img);root.appendChild(textNode(p.name||'اسم','strong'));break}
case'logo':{const d=el('div','built-logo');const src=assetSrc(node,'image',ctx)||safeMediaUrl(p.src,'image');if(src){const img=el('img');img.src=src;img.alt=p.text||'';d.appendChild(img)}else d.append(textNode(p.text||ctx.project.site?.brand?.name||'العلامة','strong'));root.appendChild(d);break}
case'breadcrumbs':{const nav=el('nav','built-breadcrumbs');(p.items||ctx.project.pages.map(pg=>pg.name)).forEach((label,i,arr)=>{const span=textNode(label,'span');if(i<arr.length-1)span.append(' › ');nav.appendChild(span)});root.appendChild(nav);break}
case'chip-list':{const d=el('div','built-chips');(p.items||['ميزة','جديد','شائع']).forEach(x=>d.appendChild(textNode(x,'span')));root.appendChild(d);break}
case'feature-list':{const d=el('div','built-feature-list');(p.items||[['ميزة','وصف مختصر'],['ميزة ثانية','وصف مختصر']]).forEach(([title,desc])=>{const item=el('div');item.append(textNode('✓','strong'),textNode(title,'h3'),textNode(desc));d.appendChild(item)});root.appendChild(d);break}
case'team':{const d=el('div','built-team');(p.items||[['أحمد','مدير'],['سارة','مصممة'],['علي','مطور']]).forEach(([name,role])=>{const item=el('div');item.appendChild(textNode(name,'strong'));item.appendChild(textNode(role));d.appendChild(item)});root.appendChild(d);break}
case'logo-cloud':{const d=el('div','built-logo-cloud');(p.items||['Acme','Nova','Orbit','Pixel']).forEach(x=>d.appendChild(textNode(x,'strong')));root.appendChild(d);break}
case'stepper':{const d=el('ol','built-stepper');(p.items||[['01','ابدأ'],['02','صمّم'],['03','أطلق']]).forEach(([n,label])=>{const item=el('li');item.append(textNode(n,'strong'),textNode(label));d.appendChild(item)});root.appendChild(d);break}
case'code':{const pre=el('pre');pre.textContent=p.code||'// اكتب الكود هنا';root.appendChild(pre);break}
case'embed':{const iframe=el('iframe');iframe.src=safeUrl(p.url||'');iframe.title=p.title||'مضمن';iframe.loading='lazy';root.appendChild(iframe);break}
case'collection-list':{const d=el('div','built-collection-list');const items=getCollectionItems(ctx.project,p.collectionId).slice(0,Math.max(1,Math.min(50,Number(p.limit)||6)));items.forEach(item=>{const card=el('article','cms-card');const title=item.data?.title||item.slug||'عنصر';card.appendChild(textNode(title,'h3'));if(item.data?.image){const img=el('img');img.src=safeMediaUrl(item.data.image,'image');img.alt=title;card.appendChild(img)}if(item.data?.body)card.appendChild(textNode(item.data.body));d.appendChild(card)});if(!items.length)d.appendChild(textNode('لا توجد عناصر محتوى بعد.'));root.appendChild(d);break}
case'schedule':{const d=el('div','built-schedule');(p.items||[['09:00','موعد']]).forEach(([time,title])=>{const item=el('div');item.append(textNode(time,'strong'),textNode(title));d.appendChild(item)});root.appendChild(d);break}
case'icon-text':{const d=el('div','built-icon-text');d.append(textNode(p.icon||'✦','strong'),textNode(p.title||'ميزة','h3'),textNode(p.text||''));root.appendChild(d);break}
case'image-text':{const d=el('div','built-image-text');const img=el('img');img.src=safeMediaUrl(p.image,'image')||assetSrc(node,'image',ctx)||placeholder();img.alt=p.title||'';const copy=el('div');copy.append(textNode(p.title||'عنوان','h3'),textNode(p.text||''));d.append(img,copy);root.appendChild(d);break}
case'feature-grid':{const d=el('div','built-feature-grid');(p.items||[]).forEach(([title,desc])=>{const card=el('article');card.append(textNode(title,'h3'),textNode(desc));d.appendChild(card)});root.appendChild(d);break}
case'contact-card':{const d=el('address','built-contact-card');d.append(textNode(p.title||'تواصل معنا','h3'),textNode(p.email||''),textNode(p.phone||''),textNode(p.address||''));root.appendChild(d);break}
case'stat-card':{const d=el('div','built-stat-card');d.append(textNode(p.value||'0','strong'),textNode(p.label||''),textNode(p.trend||''));root.appendChild(d);break}
case'pricing-card':{const d=el('article','built-pricing-card');d.append(textNode(p.name||'خطة','h3'),textNode(p.price||''),textNode(p.period||''));const ul=el('ul');(p.features||[]).forEach(x=>ul.appendChild(textNode(x,'li')));d.appendChild(ul);const b=el('a','built-button');b.href=resolveHref(p.url,ctx);b.textContent=p.button||'ابدأ';d.appendChild(b);root.appendChild(d);break}
case'testimonial-card':{const d=el('blockquote','built-testimonial-card');d.append(textNode(`“${p.quote||''}”`),textNode(`${p.name||'عميل'}${p.role?' — '+p.role:''}`,'cite'));root.appendChild(d);break}
case'logo-row':{const d=el('div','built-logo-row');(p.items||[]).forEach(x=>d.appendChild(textNode(x,'strong')));root.appendChild(d);break}
case'social-links':{const d=el('div','built-social-links');(p.items||[]).forEach(([name,url])=>{const a=el('a');a.href=safeUrl(url||'#');a.textContent=name;d.appendChild(a)});root.appendChild(d);break}
case'download':{const a=el('a','built-button');a.href=assetSrc(node,'document',ctx)||safeUrl(p.url||'#');a.download=p.filename||findAsset(ctx.project,p.assetId)?.filename||'';a.textContent=p.text||'تحميل';root.appendChild(a);break}
case'map':{const d=el('div','built-map');d.append(textNode(p.title||'الموقع','h3'),textNode(p.address||'حدد الموقع من الخصائص.'),textNode(`${p.lat||''}, ${p.lng||''}`));root.appendChild(d);break}
case'back-to-top':{const b=el('button','built-button');b.type='button';b.textContent=p.text||'↑ أعلى الصفحة';b.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});root.appendChild(b);break}
case'language-switcher':{const s=el('select','built-language-switcher');(p.languages||['AR','EN']).forEach(x=>s.appendChild(textNode(x,'option')));root.appendChild(s);break}
case'divider-label':{const d=el('div','built-divider-label');d.append(el('span'),textNode(p.text||'أو'),el('span'));root.appendChild(d);break}
case'notice-bar':{const d=el('div','built-notice-bar');d.appendChild(textNode(p.text||''));if(p.button){const a=el('a');a.href=resolveHref(p.url,ctx);a.textContent=p.button;d.appendChild(a)}root.appendChild(d);break}
case'video-card':{const d=el('article','built-video-card');d.append(textNode(p.title||'فيديو','h3'));const asset=assetById(ctx,p.assetId);const src=safeMediaUrl(p.url,'video')||assetSrc(node,'video',ctx);const embed=externalVideoEmbedUrl(src);if(embed){const frame=el('iframe');frame.src=embed;frame.title=p.title||'فيديو';frame.loading='lazy';frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.setAttribute('allowfullscreen','');d.appendChild(frame)}else if(src&&(isDirectMediaSource(src,'video')||asset?.kind==='video'||/^assets\\//i.test(src))){const video=el('video');video.src=src;video.controls=true;video.playsInline=true;video.preload='metadata';video.title=p.title||'فيديو';d.appendChild(video)}else if(src&&/^https?:\\/\\//i.test(src)){const frame=el('iframe');frame.src=src;frame.title=p.title||'فيديو';frame.loading='lazy';frame.setAttribute('allow','fullscreen; picture-in-picture');frame.setAttribute('allowfullscreen','');d.appendChild(frame)}else d.appendChild(textNode('أضف رابط فيديو أو اختر ملفًا من المكتبة.'));if(p.duration)d.appendChild(textNode(p.duration,'small'));root.appendChild(d);break}
case'compare':case'feature-comparison':{const table=el('table','comparison-table');(p.items||p.rows||[]).forEach((row,ri)=>{const tr=el('tr');row.forEach(cell=>tr.appendChild(textNode(cell,ri===0?'th':'td')));table.appendChild(tr)});root.appendChild(table);break}
case'callout':{const d=el('aside','built-callout');d.append(textNode(p.title||'ملاحظة','strong'),textNode(p.text||''));root.appendChild(d);break}
case'spinner':{const d=el('span','built-spinner');d.setAttribute('aria-label','تحميل');root.appendChild(d);break}
case'countdown':{root.appendChild(textNode(`${p.days||0} يوم • ${p.hours||0} ساعة • ${p.minutes||0} دقيقة`,'div'));break}
case'cookie-banner':{const d=el('div','built-cookie');d.append(textNode(p.text||''));const b=el('button');b.type='button';b.textContent=p.accept||'موافق';b.onclick=()=>d.remove();d.appendChild(b);root.appendChild(d);break}
case'cta':case'newsletter':case'lead-form':case'social-proof':case'highlight':case'announcement':case'quote-banner':{const d=el('div');if(p.title)d.appendChild(textNode(p.title,'h3'));d.appendChild(textNode(p.text||p.label||''));if(p.button){const b=el('button','built-button');b.type='button';b.textContent=p.button;d.appendChild(b)}root.appendChild(d);break}
case'symbol-instance':{const symbol=resolveSymbol(ctx.project,p.symbolId);if(symbol?.root&&!ctx.symbolDepth){const rendered=wrap(symbol.root,{...ctx,symbolDepth:(ctx.symbolDepth||0)+1});root.appendChild(rendered)}else if(!symbol?.root){root.appendChild(textNode('مكون مشترك غير موجود.'));}break}
default:if(p.text)root.appendChild(textNode(p.text));}}

const placeholder=(label='صورة')=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="420"><rect width="800" height="420" fill="#eef0f7"/><rect x="280" y="150" width="240" height="26" rx="13" fill="#5b5ce2" opacity=".25"/><text x="400" y="235" text-anchor="middle" font-family="Arial" font-size="28" fill="#5b5ce2">${label}</text></svg>`);
function renderPage(page,container,ctx){applyThemeVars(container,ctx.theme||{});container.dataset.pageId=page?.id||'';const pageCtx={...ctx,pageId:page?.id||ctx.pageId,embeddingPages:ctx.embeddingPages||[page?.id].filter(Boolean)};container.replaceChildren(...(page.nodes||[]).map(node=>wrap(node,pageCtx)));container.classList.toggle('is-empty',!(page.nodes||[]).length);return container}
function nodeHtml(node,theme,project,device='desktop',pageMap=null,assetMap=null,pageId=null){return wrap(node,{theme,project,styleLibrary:project?.styleLibrary||{},device,selectedId:null,headingTag:'h2',export:true,pageMap,assetMap,pageId,embeddingPages:[pageId].filter(Boolean)}).outerHTML}
exports.renderPage = renderPage;
exports.nodeHtml = nodeHtml;
