const {renderPage} = __require("src/engine/renderer.js");
const {createRuntime} = __require("src/engine/interaction.js");
const {addNode,insertNodeAtDrop} = __require("src/core/commands.js");
const {clamp} = __require("src/core/utils.js");
const {pageFromAnchor} = __require("src/engine/routing.js");
class WorkspaceEngine{constructor(store,inspector,panels){this.store=store;this.inspector=inspector;this.panels=panels;this.runtimeCleanup=null;this.runtimeKey='';this.wired=false;this.space=false}
mount(){this.pageCanvas=document.getElementById('pageCanvas');this.deviceFrame=document.getElementById('deviceFrame');this.viewport=document.getElementById('canvasViewport');this.stage=document.getElementById('canvasStage');this.host=document.getElementById('canvasStageHost');this.wireCanvas();this.wireControls();this.resizeObserver=globalThis.ResizeObserver?new ResizeObserver(()=>{this.reflowHost();this.centerStage()}):null;this.resizeObserver?.observe(this.viewport)}
wireCanvas(){if(this.wired)return;this.wired=true;this.pageCanvas.addEventListener('click',e=>{if(!this.store.ui.interactionMode&&e.target.closest('[data-page-embed-content]'))return;const link=e.target.closest('a');const w=e.target.closest('.node-wrap');if(this.store.ui.interactionMode){if(w){const sourceId=w.dataset.nodeId;const ownsClick=this.store.project.interactions?.some(i=>i.sourceId===sourceId&&i.enabled!==false&&i.trigger==='click');if(ownsClick){if(link)e.preventDefault();return}}if(link){const target=link.dataset.pageTarget||pageFromAnchor(link.getAttribute('href'),this.store.project)?.id;if(target){e.preventDefault();this.store.setActivePage(target);this.store.setUI({leftTab:'elements'});return}}return}if(!w)return;e.preventDefault();this.store.setUI({selected:w.dataset.nodeId,rightOpen:true})});this.pageCanvas.addEventListener('dragover',e=>{if(e.dataTransfer?.types?.includes('Files')||e.dataTransfer?.types?.includes('application/bunaa-type'))e.preventDefault()});this.pageCanvas.addEventListener('drop',async e=>{e.preventDefault();const target=e.target.closest('.node-wrap')?.dataset.nodeId||null;const files=[...(e.dataTransfer?.files||[])];if(files.length){const targetNode=target?this.store.find(target)?.node:null;const multiTypes=new Set(['gallery','image-carousel','media-grid','video-gallery','audio-playlist']);let attachedSingle=false;for(const file of files){try{const asset=await this.assetService?.addFile(file);if(!asset)continue;let attached=false;if(target&&targetNode&&multiTypes.has(targetNode.type)){const current=this.store.find(target)?.node?.props?.assetIds||[];this.assetService?.assignMany(target,[...current,asset.id]);attached=(this.store.find(target)?.node?.props?.assetIds||[]).includes(asset.id)}else if(target&&!attachedSingle){attached=Boolean(this.assetService?.assignToNode(target,asset.id));if(attached)attachedSingle=true}if(!attached)this.panels.insertAsset(asset)}catch(error){console.warn('Dropped asset failed',error);globalThis.__BUNAA_APP?.toast?.(error.message||'تعذر إضافة الملف')}}this.panels.setTab('layers');return}const type=e.dataTransfer.getData('application/bunaa-type');if(type){insertNodeAtDrop(this.store,type,target);this.panels.setTab('layers')}});document.getElementById('dropFooter')?.addEventListener('dragover',e=>{if(e.dataTransfer?.types?.includes('Files'))e.preventDefault()});document.getElementById('dropFooter')?.addEventListener('drop',async e=>{e.preventDefault();const files=[...(e.dataTransfer?.files||[])];if(files.length){for(const file of files){try{const asset=await this.assetService?.addFile(file);if(asset)this.panels.insertAsset(asset)}catch(error){console.warn(error);globalThis.__BUNAA_APP?.toast?.(error.message||'تعذر إضافة الملف')}}return}const type=e.dataTransfer.getData('application/bunaa-type');if(type)this.addElement(type)})}
wireControls(){document.getElementById('zoomIn')?.addEventListener('click',()=>this.setZoom(this.store.ui.zoom+.1));document.getElementById('zoomOut')?.addEventListener('click',()=>this.setZoom(this.store.ui.zoom-.1));document.getElementById('zoomFit')?.addEventListener('click',()=>this.fit());document.getElementById('gridBtn')?.addEventListener('click',()=>this.store.setUI({grid:!this.store.ui.grid}));document.getElementById('structureBtn')?.addEventListener('click',()=>this.panels.setTab('layers'));document.getElementById('focusBtn')?.addEventListener('click',()=>this.store.setUI({focus:!this.store.ui.focus}));this.setupPan()}
setupPan(){let pan=null;const stop=()=>{pan=null;this.viewport.style.cursor=''};this.viewport.addEventListener('pointerdown',e=>{const allow=e.button===1||(e.button===0&&this.space)||(e.button===0&&(e.ctrlKey||e.metaKey));if(!allow||!e.target.closest('#canvasStage'))return;pan={x:e.clientX,y:e.clientY,sx:this.viewport.scrollLeft,sy:this.viewport.scrollTop};try{this.viewport.setPointerCapture(e.pointerId)}catch{}this.viewport.style.cursor='grabbing'});this.viewport.addEventListener('pointermove',e=>{if(!pan)return;this.viewport.scrollLeft=pan.sx-(e.clientX-pan.x);this.viewport.scrollTop=pan.sy-(e.clientY-pan.y)});this.viewport.addEventListener('pointerup',stop);this.viewport.addEventListener('pointercancel',stop);window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!e.target.matches('input,textarea,select'))this.space=true});window.addEventListener('keyup',e=>{if(e.code==='Space')this.space=false});window.addEventListener('blur',()=>{this.space=false;stop()});this.viewport.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();this.setZoom(this.store.ui.zoom+(e.deltaY<0?.08:-.08))},{passive:false});window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select'))return;if(e.key==='PageDown')this.viewport.scrollBy({top:Math.max(240,this.viewport.clientHeight*.8),behavior:'smooth'});else if(e.key==='PageUp')this.viewport.scrollBy({top:-Math.max(240,this.viewport.clientHeight*.8),behavior:'smooth'});else if(e.key==='Home'&&this.store.ui.focus)this.viewport.scrollTo({top:0,behavior:'smooth'});else if(e.key==='End'&&this.store.ui.focus)this.viewport.scrollTo({top:this.viewport.scrollHeight,behavior:'smooth'});})}
setZoom(z){this.store.setUI({zoom:clamp(Number(z)||1,.2,1.5)})}
setDevice(device){if(!['desktop','tablet','mobile'].includes(device))return;this.store.setUI({device,zoom:1});this.inspector?.setDevice?.(device);requestAnimationFrame(()=>this.fit())}
deviceWidth(){return this.store.project.devices[this.store.ui.device]?.width||1180}
fit(){const base=this.deviceWidth(),available=Math.max(260,this.viewport.clientWidth-96);this.setZoom(clamp(available/base,.2,1.2));requestAnimationFrame(()=>{this.centerStage();this.viewport.scrollTop=0})}
centerStage(){if(!this.viewport)return;const overflow=this.viewport.scrollWidth>this.viewport.clientWidth+2;if(!overflow)this.viewport.scrollLeft=0}
addElement(type){addNode(this.store,type);this.panels.setTab('layers')}
syncRuntime(){if(!this.store.ui.interactionMode){this.runtimeCleanup?.();this.runtimeCleanup=null;this.runtimeKey='';return}const key=JSON.stringify([this.store.project.activePageId,this.store.project.interactions,this.store.ui.device]);if(key===this.runtimeKey&&this.runtimeCleanup)return;this.runtimeCleanup?.();this.runtimeCleanup=createRuntime({document,project:this.store.project,navigate:id=>{if(this.store.project.pages.some(p=>p.id===id))this.store.setActivePage(id)}});this.runtimeKey=key}
render(){const page=this.store.activePage();if(!page)return;renderPage(page,this.pageCanvas,{project:this.store.project,theme:this.store.project.theme,styleLibrary:this.store.project.styleLibrary,device:this.store.ui.device,selectedId:this.store.ui.interactionMode?null:this.store.ui.selected,pageId:page.id,embeddingPages:[page.id]});this.deviceFrame.className=`site-frame ${this.store.ui.device}`;this.pageCanvas.classList.toggle('show-grid',this.store.ui.grid);document.getElementById('canvasPageTitle').textContent=page.name;document.getElementById('canvasModeLabel').textContent=this.store.ui.interactionMode?'وضع تجربة التفاعل':'وضع البناء';const hit=this.store.ui.selected?this.store.find(this.store.ui.selected):null;document.getElementById('selectionInfo').textContent=hit?`العنصر: ${hit.node.props?.label||hit.node.props?.title||hit.node.type}`:'لم يتم تحديد عنصر';document.getElementById('pageCountLabel').textContent=`${this.store.project.pages.length} صفحة`;document.getElementById('elementCountLabel').textContent=`${this.store.nodeCount()} عنصر`;document.getElementById('dropEmpty').classList.toggle('hidden',page.nodes.length>0);document.getElementById('gridBtn').classList.toggle('active',this.store.ui.grid);this.applyZoom();this.syncRuntime()}
reflowHost(){const z=this.store.ui.zoom,base=this.deviceWidth(),viewportWidth=this.viewport?.clientWidth||0,padding=48;const required=Math.ceil(base*z+padding);this.host.style.setProperty('width',`${Math.max(viewportWidth,required)}px`,'important');this.host.style.setProperty('height',`${Math.ceil(Math.max(this.stage.offsetHeight*z,760*z)+70)}px`,'important')}
applyZoom(){const z=this.store.ui.zoom,base=this.deviceWidth();this.stage.style.width=`${base}px`;this.stage.style.maxWidth='none';this.stage.style.transform=`scale(${z})`;this.stage.style.transformOrigin='top center';this.reflowHost();document.getElementById('zoomLabel').textContent=`${Math.round(z*100)}%`;}
sync(){this.render();document.body.classList.toggle('focus-canvas',this.store.ui.focus);this.refreshPages()}
refreshPages(){const select=document.getElementById('pageSelect');if(!select)return;select.replaceChildren(...this.store.project.pages.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o}));select.value=this.store.project.activePageId}
cleanup(){this.runtimeCleanup?.();this.runtimeCleanup=null;this.resizeObserver?.disconnect?.()}
}
exports.WorkspaceEngine = WorkspaceEngine;
