import {uid,slugify,deepClone} from './utils.js';
export const SCHEMA_VERSION=11;
export const DEFAULT_THEME={primary:'#5b5ce2',secondary:'#20a06a',accent:'#f4a340',surface:'#fff',soft:'#f6f7fb',text:'#171b2a',muted:'#6f778b',radius:14,font:'system-ui'};
export const DEFAULT_DEVICES={desktop:{width:1180},tablet:{width:768},mobile:{width:390}};
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
export function makeNode(type,props={},style={},children=[]){return {id:uid('node'),type,props:{...props},style:{marginTop:0,marginBottom:14,...style},responsive:{},children:Array.isArray(children)?[...children]:[]}}
export function makePage(name='الرئيسية',nodes=[],slug){name=String(name||'الرئيسية');return {id:uid('page'),name,slug:slug||slugify(name),seo:{title:name,description:'',image:''},nodes:Array.isArray(nodes)?nodes:[]}}
export function makeProject(seed={}){const home=makePage('الرئيسية',seed.nodes||[],'home');return {version:SCHEMA_VERSION,meta:{name:seed.name||'مشروعي',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},theme:{...DEFAULT_THEME,...(seed.theme||{})},devices:{...DEFAULT_DEVICES,...(seed.devices||{})},pages:[home],assets:Array.isArray(seed.assets)?deepClone(seed.assets):[],variables:obj(seed.variables)?deepClone(seed.variables):{},interactions:Array.isArray(seed.interactions)?deepClone(seed.interactions):[],settings:{advancedDevices:false,propagateDevices:false,...(seed.settings||{})},activePageId:home.id,activeNodeId:null}}
function node(n,ids){n=obj(n)?n:{};let id=typeof n.id==='string'&&!ids.has(n.id)?n.id:uid('node');ids.add(id);return {...n,id,type:typeof n.type==='string'&&n.type?n.type:'container',props:obj(n.props)?n.props:{},style:{marginTop:0,marginBottom:14,...(obj(n.style)?n.style:{})},responsive:obj(n.responsive)?n.responsive:{},children:(Array.isArray(n.children)?n.children:[]).map(x=>node(x,ids))}}
function slug(value,used){const base=slugify(value);let s=base,i=2;while(used.has(s))s=base+'-'+i++;used.add(s);return s}
export function normalizeProject(project){const now=new Date().toISOString(),p=deepClone(obj(project)?project:makeProject());p.version=SCHEMA_VERSION;p.meta=obj(p.meta)?p.meta:{};p.meta.name=String(p.meta.name||'مشروعي');p.meta.createdAt=p.meta.createdAt||now;p.theme={...DEFAULT_THEME,...(obj(p.theme)?p.theme:{})};p.devices={...DEFAULT_DEVICES,...(obj(p.devices)?p.devices:{})};p.settings={advancedDevices:false,propagateDevices:false,...(obj(p.settings)?p.settings:{})};p.assets=Array.isArray(p.assets)?p.assets:[];p.variables=obj(p.variables)?p.variables:{};p.pages=Array.isArray(p.pages)&&p.pages.length?p.pages:[makePage()];const ids=new Set(),slugs=new Set();p.pages=p.pages.map((raw,i)=>{const x=obj(raw)?raw:{},name=String(x.name||'صفحة '+(i+1)),id=typeof x.id==='string'&&!ids.has(x.id)?x.id:uid('page');ids.add(id);return {...x,id,name,slug:slug(x.slug||name,slugs),seo:obj(x.seo)?{title:String(x.seo.title??name),description:String(x.seo.description??''),image:String(x.seo.image??'')}:{title:name,description:'',image:''},nodes:(Array.isArray(x.nodes)?x.nodes:[]).map(n=>node(n,ids))}});p.activePageId=p.pages.some(x=>x.id===p.activePageId)?p.activePageId:p.pages[0].id;const nodeIds=new Set();walk(p.pages.flatMap(x=>x.nodes),n=>nodeIds.add(n.id));p.interactions=(Array.isArray(p.interactions)?p.interactions:[]).filter(i=>i&&nodeIds.has(i.sourceId)&&(!i.options?.targetId||nodeIds.has(i.options.targetId)));p.activeNodeId=nodeIds.has(p.activeNodeId)?p.activeNodeId:null;p.meta.updatedAt=now;return p}
export function walk(nodes,fn,parent=null,index=0){for(let i=0;i<(nodes||[]).length;i++){const n=nodes[i];fn(n,parent,i,nodes);if(n?.children?.length)walk(n.children,fn,n,i)}}
function inPage(page,id){let hit=null;walk(page.nodes,(n,parent,index)=>{if(n.id===id)hit={node:n,parent,index,page}});return hit}
export function findNode(project,id){const p=project.pages.find(x=>x.id===project.activePageId);return p?inPage(p,id):null}
export function findNodeGlobal(project,id){if(!id)return null;for(const p of project.pages||[]){const hit=inPage(p,id);if(hit)return hit}return null}
export function countNodes(project){let n=0;for(const p of project.pages||[])walk(p.nodes,()=>n++);return n}
export function collectIds(project){const ids=new Set();for(const p of project.pages||[]){ids.add(p.id);walk(p.nodes,n=>ids.add(n.id))}return ids}
export function nextPageName(project){let i=1;while(project.pages.some(p=>p.name===`صفحة ${i}`))i++;return `صفحة ${i}`}