import {showModal} from './modal.js';
import {exportZip,exportCurrentHtml,exportProjectJson} from '../engine/exporter.js';
import {renderPage} from '../engine/renderer.js';

export class Dialogs{constructor(store,engine,panels){this.store=store;this.engine=engine;this.panels=panels;this.host=document.getElementById('modalHost')}
 bind(){document.getElementById('previewBtn').onclick=()=>this.preview();document.getElementById('exportBtn').onclick=()=>this.export();document.getElementById('qualityBtn').onclick=()=>this.quality();document.getElementById('globalStyleBtn').onclick=()=>this.theme();document.getElementById('shortcutsBtn').onclick=()=>this.shortcuts();document.getElementById('advancedDevicesBtn').onclick=()=>{this.store.setUI({advancedDevices:!this.store.ui.advancedDevices});document.getElementById('advancedDevicesBtn').textContent=this.store.ui.advancedDevices?'إغلاق إعدادات الأجهزة':'إعدادات الأجهزة'};document.getElementById('projectMenuBtn').onclick=()=>this.projectName();}
 preview(){const body=`<div class="preview-body"><iframe id="bunaaPreviewFrame" title="المعاينة"></iframe></div>`;const m=showModal(this.host,{title:'معاينة حية',body,actions:[] ,wide:true});const frame=m.querySelector('iframe');const page=this.store.activePage();const html=this.previewHtml(page);frame.srcdoc=html}
 previewHtml(page){
  const sandbox=document.createElement('div');sandbox.style.cssText='position:fixed;left:-100000px;top:-100000px;width:1180px;';document.body.appendChild(sandbox);
  const sections=this.store.project.pages.map(pg=>{const holder=document.createElement('section');holder.id=`page-${pg.slug}`;renderPage(pg,holder,{project:this.store.project,theme:this.store.project.theme,device:'desktop',selectedId:null});sandbox.appendChild(holder);return holder.outerHTML}).join('');sandbox.remove();
  const t=this.store.project.theme;
  const css=`<style>html{scroll-behavior:smooth}body{margin:0;font-family:system-ui;line-height:1.6;color:${t.text};background:#fff}main{max-width:1180px;margin:auto}.node-wrap{display:block}.built-button{display:inline-flex;padding:11px 20px;background:${t.primary};color:#fff;border-radius:11px;text-decoration:none;font-weight:800}.built-card{border:1px solid #e7e9ef;border-radius:14px;padding:18px}.built-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.built-gallery img{width:100%;height:180px;object-fit:cover;border-radius:12px}.built-nav{display:flex;justify-content:space-between;align-items:center}.nav-links{display:flex;gap:15px;flex-wrap:wrap}.built-form input,.built-form textarea,.built-form select{width:100%;padding:10px;border:1px solid #e4e6ed;border-radius:8px}.built-stats,.built-pricing,.built-timeline{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.built-stats>div,.built-pricing>div,.built-timeline>div{padding:16px;border:1px solid #e7e9ef;border-radius:12px}.built-progress{height:32px;background:#eef0f5;border-radius:10px;overflow:hidden;position:relative}.built-progress div{height:100%;background:${t.primary}}.built-progress span{position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:10px}.tab-panel.hidden{display:none}.carousel-controls{display:flex;justify-content:space-between;align-items:center}.carousel-controls button{border:1px solid #e1e4ed;background:#fff;border-radius:8px;width:32px;height:32px}@media(max-width:760px){.built-gallery,.built-stats,.built-pricing,.built-timeline{grid-template-columns:1fr}.nav-links{flex-direction:column;align-items:flex-start}}</style>`;
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${css}</head><body><main>${sections}</main></body></html>`;
 }
 export(){const body=`<div class="list-stack"><div class="quality-item good">التصدير متعدد الملفات يحافظ على الصفحات وبيانات المشروع.</div><button id="zipExport" class="primary-btn">تنزيل الموقع ZIP</button><button id="htmlExport" class="secondary-btn">تنزيل الصفحة HTML</button><button id="jsonExport" class="secondary-btn">تنزيل المشروع JSON</button></div>`;const m=showModal(this.host,{title:'تصدير المشروع',body,actions:[]});m.querySelector('#zipExport').onclick=()=>exportZip(this.store.project);m.querySelector('#htmlExport').onclick=()=>exportCurrentHtml(this.store.project);m.querySelector('#jsonExport').onclick=()=>exportProjectJson(this.store.project)}
 quality(){const issues=[];for(const p of this.store.project.pages){if(!p.seo.title)issues.push(`الصفحة ${p.name} بلا عنوان SEO`);const walk=n=>{if(n.type==='image'&&!n.props?.alt)issues.push(`صورة بدون وصف: ${n.id}`);if((n.type==='button'||n.type==='link')&&!n.props?.text)issues.push(`عنصر ${n.type} بلا نص`);(n.children||[]).forEach(walk)};(p.nodes||[]).forEach(walk)};const body=issues.length?`<div class="quality-list">${issues.map(x=>`<div class="quality-item warn">⚠ ${x}</div>`).join('')}</div>`:'<div class="quality-item good">✓ لم نجد مشكلات أساسية في الصفحات والعناصر.</div>';showModal(this.host,{title:'فحص الجودة',body,actions:[]})}
 theme(){const t=this.store.project.theme;const body=`<div class="field"><label>اللون الأساسي</label><input id="themePrimary" value="${t.primary}"></div><div class="field"><label>لون النص</label><input id="themeText" value="${t.text}"></div><div class="field"><label>الاستدارة</label><input id="themeRadius" type="number" value="${t.radius}"></div>`;const m=showModal(this.host,{title:'النمط العام',body,actions:[{label:'حفظ',kind:'primary',onClick:()=>{}}]});m.querySelector('#themePrimary').onchange=e=>this.store.transact('النمط العام',p=>p.theme.primary=e.target.value);m.querySelector('#themeText').onchange=e=>this.store.transact('النمط العام',p=>p.theme.text=e.target.value);m.querySelector('#themeRadius').onchange=e=>this.store.transact('النمط العام',p=>p.theme.radius=Number(e.target.value))}
 shortcuts(){showModal(this.host,{title:'الاختصارات',body:`<div class="shortcut-grid"><div><span>تراجع</span><kbd>Ctrl/⌘ Z</kbd></div><div><span>إعادة</span><kbd>Ctrl/⌘ Y</kbd></div><div><span>حفظ</span><kbd>Ctrl/⌘ S</kbd></div><div><span>تكبير</span><kbd>Ctrl/⌘ + عجلة</kbd></div><div><span>تحريك Canvas</span><kbd>Space + سحب</kbd></div><div><span>ملاءمة</span><kbd>F</kbd></div></div>`,actions:[]})}
 projectName(){const name=prompt('اسم المشروع',this.store.project.meta.name);if(name)this.store.transact('تسمية المشروع',p=>p.meta.name=name)}
}
