import {categories,searchDefinitions,nodeIcon} from '../catalog/components.js';
import {templates,materializeTemplate} from '../catalog/templates.js';
import {addNode,removeNode,duplicateNode,moveNode,setPageName} from '../core/commands.js';
import {triggers,motions,makeInteraction,upsertInteraction,removeInteraction} from '../engine/interaction.js';
import {findNodeGlobal,countNodes} from '../core/model.js';
import {dataUrlFromFile,escapeHtml,downloadText} from '../core/utils.js';
import {showModal} from './modal.js';

export class Panels{constructor(store,engine){this.store=store;this.engine=engine;this.category='all';this.search='';this.currentTab='elements'}
 mount(){this.bindTabs();this.renderLibrary();this.renderLayers();this.renderInteractions()}
 bindTabs(){document.querySelectorAll('[data-left-tab]').forEach(b=>b.addEventListener('click',()=>this.setTab(b.dataset.leftTab)));document.getElementById('elementSearch').addEventListener('input',e=>{this.search=e.target.value;this.renderLibrary()});document.getElementById('categoryTabs').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;this.category=b.dataset.cat;this.renderLibrary()});document.getElementById('openTemplatesBtn').addEventListener('click',()=>this.templatesModal());document.getElementById('openAssetsBtn').addEventListener('click',()=>this.assetsModal());}
 setTab(tab){this.currentTab=tab;document.querySelectorAll('.drawer-tab').forEach(b=>b.classList.toggle('active',b.dataset.leftTab===tab));for(const [id,view] of [['elements',document.getElementById('elementsView')],['layers',document.getElementById('layersView')],['interaction',document.getElementById('interactionView')]])view.classList.toggle('hidden',tab!==id);if(tab==='elements')this.renderLibrary();if(tab==='layers')this.renderLayers();if(tab==='interaction')this.renderInteractions()}
 renderLibrary(){const cat=document.getElementById('categoryTabs');cat.innerHTML=[['all','الكل'],...categories].map(([id,label])=>`<button class="category-chip ${this.category===id?'active':''}" data-cat="${id}">${label}</button>`).join('');const grid=document.getElementById('elementLibrary');grid.innerHTML=searchDefinitions(this.search,this.category).map(d=>`<div class="element-card" draggable="true" data-type="${d.type}"><div class="element-thumb">${nodeIcon(d.type)}</div><b>${d.label}</b><small>${d.description}</small><button class="add-element" data-add="${d.type}">إضافة</button></div>`).join('');grid.onclick=e=>{const b=e.target.closest('[data-add]');if(b)this.engine.addElement(b.dataset.add)};grid.ondragstart=e=>{const c=e.target.closest('[data-type]');if(c)e.dataTransfer.setData('application/bunaa-type',c.dataset.type)}}
 renderLayers(){const page=this.store.activePage();const tree=document.getElementById('layerTree');tree.innerHTML=(page.nodes||[]).map((n,i)=>this.layerHtml(n,i,0)).join('')||'<div class="tips-card">لا توجد عناصر بعد.</div>';tree.querySelectorAll('[data-select-layer]').forEach(b=>b.addEventListener('click',()=>this.store.setUI({selected:b.dataset.selectLayer})));tree.querySelectorAll('[data-layer-action]').forEach(b=>b.addEventListener('click',e=>{const [action,id]=[b.dataset.layerAction,b.dataset.id];if(action==='up'||action==='down')moveNode(this.store,id,action);else if(action==='duplicate')duplicateNode(this.store,id);else if(action==='delete')removeNode(this.store,id);this.engine.render()}));}
 layerHtml(n,index,depth){const hit=n.id===this.store.ui.selected;return `<div class="layer-row ${hit?'selected':''}" style="margin-right:${depth*12}px"><span class="layer-icon">${nodeIcon(n.type)}</span><button class="layer-name" data-select-layer="${n.id}">${escapeHtml(n.props?.label||n.props?.title||n.props?.text||n.type)}<small>${n.type}</small></button><span class="layer-actions"><button data-layer-action="up" data-id="${n.id}">↑</button><button data-layer-action="down" data-id="${n.id}">↓</button><button data-layer-action="duplicate" data-id="${n.id}">＋</button><button data-layer-action="delete" data-id="${n.id}">×</button></span></div>${(n.children||[]).map((c,i)=>this.layerHtml(c,i,depth+1)).join('')}`}
 renderInteractions(){const box=document.getElementById('interactionPanel');const id=this.store.ui.selected;const hit=id?findNodeGlobal(this.store.project,id):null;if(!hit){box.innerHTML='<div class="tips-card"><b>حدد عنصرًا أولًا</b><p>بعد تحديد عنصر، اختر تفاعلًا بسيطًا من هنا.</p></div>';return}const ints=(this.store.project.interactions||[]).filter(i=>i.sourceId===id);box.innerHTML=`<div class="selected-target"><b>العنصر المحدد</b><small>${escapeHtml(hit.node.props?.label||hit.node.props?.text||hit.node.type)}</small></div><button class="advanced-toggle" id="interactionModeBtn">${this.store.ui.interactionMode?'■ إيقاف تجربة التفاعل':'▶ تجربة التفاعل'}</button><div class="interaction-trigger-grid">${triggers.map(([key,label])=>`<button class="interaction-trigger" data-trigger="${key}"><b>${label}</b><small>إضافة سلوك بسيط</small></button>`).join('')}</div><div class="tips-card"><b>التفاعلات الحالية</b><p>${ints.length?ints.map(i=>`${i.trigger} → ${i.action}`).join(' • '):'لا يوجد تفاعل لهذا العنصر.'}</p></div>${ints.map(i=>`<button class="soft-btn" data-remove-int="${i.id}">× ${i.triggerLabel||i.trigger}</button>`).join('')}`;box.querySelector('#interactionModeBtn')?.addEventListener('click',()=>{this.store.setUI({interactionMode:!this.store.ui.interactionMode});this.engine.render();this.renderInteractions()});box.querySelectorAll('[data-trigger]').forEach(b=>b.addEventListener('click',()=>this.addInteraction(b.dataset.trigger)));box.querySelectorAll('[data-remove-int]').forEach(b=>b.addEventListener('click',()=>{this.store.transact('حذف تفاعل',p=>removeInteraction(p,b.dataset.removeInt));this.renderInteractions();this.engine.render()}));}
 addInteraction(trigger){const source=this.store.ui.selected;if(!source)return;const int=makeInteraction(source,trigger,'motion',{motion:trigger==='hover'?'zoom':trigger==='scroll'?'slide':'fade',duration:420});this.store.transact('إضافة تفاعل',p=>upsertInteraction(p,int));this.store.setUI({interactionMode:true});this.renderInteractions();this.engine.render();}
 templatesModal(){const body=`<div class="template-grid">${templates.map((t,i)=>`<article class="template-card"><div class="template-preview"><div class="mock-block mock-wide"></div><div class="mock-block"></div><div class="mock-block mock-short"></div><div class="mock-block"></div></div><div class="template-info"><b>${t.name}</b><small>${t.description}</small><div class="template-actions"><button data-template-add="${i}">إضافة كقسم</button><button class="apply" data-template-apply="${i}">تطبيق كموقع</button></div></div></article>`).join('')}</div>`;const modal=showModal(document.getElementById('modalHost'),{title:'قوالب جاهزة فعلية',body,actions:[]});modal.querySelectorAll('[data-template-apply]').forEach(b=>b.addEventListener('click',()=>{const t=materializeTemplate(templates[Number(b.dataset.templateApply)]);this.store.transact('تطبيق قالب',p=>{p.pages=t.pages;p.activePageId=t.pages[0].id;p.meta.name=t.name;p.meta.updatedAt=new Date().toISOString()});this.store.setUI({selected:null});modal.remove();this.engine.render();this.renderLayers()}));modal.querySelectorAll('[data-template-add]').forEach(b=>b.addEventListener('click',()=>{const t=materializeTemplate(templates[Number(b.dataset.templateAdd)]);const first=t.pages[0];this.store.transact('إضافة قسم من قالب',p=>{const page=p.pages.find(x=>x.id===p.activePageId);page.nodes.push(...first.nodes)});modal.remove();this.engine.render();this.renderLayers()}));}
 assetsModal(){const body=`<div class="field"><label>رفع ملفات إلى المشروع</label><input id="assetUploader" type="file" multiple accept="image/*,video/*,audio/*"></div><div id="assetList" class="asset-grid">${(this.store.project.assets||[]).map(a=>`<div class="asset-card" data-asset-id="${a.id}"><img src="${a.type.startsWith('image/')?a.data:''}" alt=""><div>${escapeHtml(a.name)}</div></div>`).join('')}</div>`;const modal=showModal(document.getElementById('modalHost'),{title:'مكتبة الوسائط',body,actions:[]});modal.querySelectorAll('[data-asset-id]').forEach(card=>card.addEventListener('click',()=>{const a=this.store.project.assets.find(x=>x.id===card.dataset.assetId);const id=this.store.ui.selected;if(a&&id){this.store.transact('تعيين الوسيط',p=>{const h=findNodeGlobal(p,id);if(h&&h.node.type==='image')h.node.props.src=a.data});this.engine.render();modal.remove()}}));modal.querySelector('#assetUploader').addEventListener('change',async e=>{for(const f of e.target.files){const data=await dataUrlFromFile(f);this.store.transact('رفع وسائط',p=>p.assets.push({id:`asset_${Date.now()}_${Math.random().toString(36).slice(2,5)}`,name:f.name,type:f.type,size:f.size,data}));}modal.remove();this.assetsModal()})}
 pagesModal(){const body=`<div class="list-stack">${this.store.project.pages.map(p=>`<div class="page-row ${p.id===this.store.project.activePageId?'active':''}"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.slug)} • ${(p.nodes||[]).length} عناصر</small></div><div class="page-row-actions"><button data-open-page="${p.id}">فتح</button><button data-rename-page="${p.id}">تسمية</button><button data-delete-page="${p.id}">×</button></div></div>`).join('')}</div><div class="modal-actions"><button id="newPageBtn" class="primary-btn">＋ صفحة جديدة</button></div>`;const modal=showModal(document.getElementById('modalHost'),{title:'صفحات الموقع',body,actions:[]});modal.querySelector('#newPageBtn').addEventListener('click',()=>{const name=prompt('اسم الصفحة','صفحة جديدة');if(name){this.store.addPage(name);modal.remove();this.pagesModal();this.engine.sync()}});modal.querySelectorAll('[data-open-page]').forEach(b=>b.addEventListener('click',()=>{this.store.setUI({selected:null});this.store.transact('فتح صفحة',p=>p.activePageId=b.dataset.openPage,{record:false});modal.remove();this.engine.sync()}));modal.querySelectorAll('[data-rename-page]').forEach(b=>b.addEventListener('click',()=>{const name=prompt('الاسم الجديد');if(name)setPageName(this.store,b.dataset.renamePage,name);modal.remove();this.pagesModal();this.engine.sync()}));modal.querySelectorAll('[data-delete-page]').forEach(b=>b.addEventListener('click',()=>{this.store.deletePage(b.dataset.deletePage);modal.remove();this.pagesModal();this.engine.sync()}));return modal}
}
