import {renderPage,nodeHtml} from './renderer.js';
import {escapeHtml,downloadBlob,downloadText,deepClone} from '../core/utils.js';

export function buildPageHtml(page,project){const body=(page.nodes||[]).map(n=>nodeHtml(n,project.theme,project,'desktop')).join('');const replaced=fixExportLinks(body,project);return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(page.seo?.title||page.name)}</title><meta name="description" content="${escapeHtml(page.seo?.description||'')}"><link rel="stylesheet" href="styles.css"></head><body><main>${replaced}</main><script src="script.js"></script></body></html>`}
export function buildHomeHtml(page,project){const body=(page.nodes||[]).map(n=>nodeHtml(n,project.theme,project,'desktop')).join('');return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(page.seo?.title||page.name)}</title><meta name="description" content="${escapeHtml(page.seo?.description||'')}"><link rel="stylesheet" href="styles.css"></head><body><main>${fixExportLinks(body,project)}</main><script src="script.js"></script></body></html>`}
function fixExportLinks(html,project){let out=html;for(const p of project.pages){const file=p.id===project.pages[0].id?'index.html':`${p.slug}.html`;out=out.replaceAll(`href="#page-${p.slug}"`,`href="${file}"`)}return out}
export function runtimeJs(project){return `(()=>{const pages=${JSON.stringify(project.pages.map(p=>({id:p.id,slug:p.slug,name:p.name})))};document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href')||'';if(h.startsWith('#page-')){e.preventDefault();location.href=h.slice(1)+'.html'}})})();`}
export function stylesheet(){return `*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",Tahoma,Arial,sans-serif;color:#171b2a;background:#fff;line-height:1.6}main{max-width:1180px;margin:0 auto}a{color:#5b5ce2}.node-wrap{display:block}.built-button{display:inline-flex;padding:11px 20px;border-radius:11px;background:#5b5ce2;color:#fff;text-decoration:none;font-weight:800}.built-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.built-gallery img{width:100%;height:220px;object-fit:cover;border-radius:12px}.built-card{padding:18px;border:1px solid #e7e9ef;border-radius:14px}.built-card h3{margin:0 0 8px}.built-card p{color:#687084}.built-nav{display:flex;align-items:center;justify-content:space-between;gap:16px}.nav-links{display:flex;gap:16px;flex-wrap:wrap}.built-nav a{text-decoration:none}.built-alert{border-radius:11px}.built-badge{display:inline-block}.built-stats,.built-pricing,.built-timeline{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.built-stats>div,.built-pricing>div,.built-timeline>div{padding:16px;border:1px solid #e7e9ef;border-radius:12px;background:#fff}.built-stats strong,.built-counter{font-size:30px;display:block}.built-progress{position:relative;height:36px;background:#eef0f5;border-radius:12px;overflow:hidden}.built-progress div{height:100%;background:#5b5ce2}.built-progress span{position:absolute;inset:0;display:grid;place-items:center;font-size:10px;color:#fff}.built-chart{display:flex;align-items:flex-end;gap:10px;height:180px}.built-chart i{flex:1;background:#6a6dec;border-radius:7px 7px 2px 2px;min-height:14px}.built-rating{letter-spacing:3px}.built-social{display:flex;gap:12px}.built-form label.field-label{display:block;font-size:11px;color:#757d8e;margin-bottom:5px}.built-form input,.built-form textarea,.built-form select{width:100%;padding:10px;border:1px solid #e2e5ee;border-radius:9px;background:#fff}.built-form textarea{min-height:110px}.check-row{display:flex;align-items:center;gap:7px}.built-accordion details{border-bottom:1px solid #eceef3;padding:10px}.built-carousel{padding:12px;background:#f7f8fb;border-radius:12px}.carousel-controls{display:flex;justify-content:space-between;align-items:center}.carousel-controls button{border:1px solid #e1e4ed;background:#fff;border-radius:8px;width:32px;height:32px}@media(max-width:760px){main{width:auto}.built-gallery,.built-stats,.built-pricing,.built-timeline{grid-template-columns:1fr}.nav-links{gap:8px}}`}
export async function exportZip(project){const files={
 'index.html':buildHomeHtml(project.pages[0],project),
 'styles.css':stylesheet(),
 'script.js':runtimeJs(project),
 'project.json':JSON.stringify(project,null,2),
 'README.md':`# ${project.meta.name}\n\nتم إنشاء هذا المشروع بواسطة بَنّاء V11 Phase 3.\n`,
 ...Object.fromEntries(project.pages.slice(1).map(p=>[`${p.slug}.html`,buildPageHtml(p,project)]))
};const blob=zipBlob(files);downloadBlob(blob,`${safeName(project.meta.name)}.zip`);return Object.keys(files)}
export function exportCurrentHtml(project){downloadText(buildHomeHtml(project.pages.find(p=>p.id===project.activePageId)||project.pages[0],project),'page.html','text/html;charset=utf-8')}
export function exportProjectJson(project){downloadText(JSON.stringify(project,null,2),'bunaa-project.json','application/json;charset=utf-8')}
const safeName=s=>String(s||'project').replace(/[^\w\u0600-\u06ff-]+/g,'-').replace(/-+/g,'-').slice(0,60)||'project';
function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concat(parts){let size=0;parts.forEach(p=>size+=p.length);const out=new Uint8Array(size);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
const te=new TextEncoder();
const table=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function zipBlob(files){const locals=[],centrals=[];let offset=0;const entries=Object.entries(files);for(const [name,data] of entries){const nameB=te.encode(name),dataB=te.encode(data),crc=crc32(dataB);const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(dataB.length),u32(dataB.length),u16(nameB.length),u16(0),nameB,dataB]);locals.push(local);const central=concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(dataB.length),u32(dataB.length),u16(nameB.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nameB]);centrals.push(central);offset+=local.length}const central=concat(centrals),localAll=concat(locals),end=concat([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(localAll.length),u16(0)]);return new Blob([localAll,central,end],{type:'application/zip'})}
