import {deepClone} from '../core/utils.js';

export const triggers=[['click','عند الضغط'],['hover','عند المرور'],['load','عند الظهور'],['focus','عند التركيز'],['input','أثناء الكتابة']];
export const motions=[['fade','ظهور لطيف'],['slide','انزلاق خفيف'],['zoom','تكبير بسيط'],['pulse','نبض'],['glow','وهج'],['shake','اهتزاز'],['bounce','قفزة']];
export function makeInteraction(sourceId,trigger='click',action='motion',options={}){return {id:`int_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`,sourceId,trigger,enabled:true,action,options:{motion:'fade',duration:420,targetId:sourceId,pageId:null,anchor:'',...options}}}
export function upsertInteraction(project,interaction){project.interactions=project.interactions||[];const i=project.interactions.findIndex(x=>x.id===interaction.id);if(i<0)project.interactions.push(deepClone(interaction));else project.interactions[i]=deepClone(interaction)}
export function removeInteraction(project,id){project.interactions=(project.interactions||[]).filter(x=>x.id!==id)}
export function interactionsFor(project,nodeId){return (project.interactions||[]).filter(x=>x.sourceId===nodeId&&x.enabled!==false)}
export function triggerLabel(type){return Object.fromEntries(triggers)[type]||type}
export function motionLabel(type){return Object.fromEntries(motions)[type]||type}
function runMotion(el,motion,duration){if(!el)return;const cls=`motion-${motion}`;el.classList.remove(...Array.from(el.classList).filter(c=>c.startsWith('motion-')));void el.offsetWidth;el.style.animationDuration=`${duration}ms`;el.classList.add(cls);el.addEventListener('animationend',()=>{el.classList.remove(cls);el.style.animationDuration=''}, {once:true})}
export function createRuntime({document,project,navigate,scrollToAnchor}){const listeners=[];const find=id=>document.querySelector(`[data-node-id="${CSS.escape(id)}"]`);const run=interaction=>{const o=interaction.options||{};const target=find(o.targetId||interaction.sourceId);if(interaction.action==='motion')runMotion(target,o.motion||'fade',Number(o.duration||420));else if(interaction.action==='show'&&target)target.hidden=false;else if(interaction.action==='hide'&&target)target.hidden=true;else if(interaction.action==='toggle'&&target)target.hidden=!target.hidden;else if(interaction.action==='scroll'&&o.anchor)scrollToAnchor?.(o.anchor);else if(interaction.action==='page'&&o.pageId)navigate?.(o.pageId)};
  for(const i of project.interactions||[]){if(i.enabled===false)continue;const source=find(i.sourceId);if(!source)continue;const type=i.trigger;if(type==='load')setTimeout(()=>run(i),40);else if(type==='hover'){const a=()=>run(i);source.addEventListener('pointerenter',a);listeners.push([source,'pointerenter',a])}else if(type==='click'){const a=e=>{if(source.tagName==='A'&&source.getAttribute('href')==='#')e.preventDefault();run(i)};source.addEventListener('click',a);listeners.push([source,'click',a])}else if(type==='focus'){const a=()=>run(i);source.addEventListener('focus',a);listeners.push([source,'focus',a])}else if(type==='input'){const a=()=>run(i);source.addEventListener('input',a);listeners.push([source,'input',a])}}
  return()=>listeners.forEach(([el,t,fn])=>el.removeEventListener(t,fn));
}
