#!/usr/bin/env python3
"""Rebuild Bunaa Studio's standalone inline module bundle from mirrored source modules.

No network access, GitHub connection, npm installation, or third-party Python package is needed.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE_ROOT = ROOT / "source" / "src"
MODULE_ROOT = SOURCE_ROOT / "src"
BUNDLE_PATH = ROOT / "bundle-extracted.js"
ENTRY_POINTS = (ROOT / "index.html", ROOT / "Bunaa.html")
MARKER = "/* Bunaa Studio V35 — generated by build_bundle.py */"


def module_id(path: Path) -> str:
    return path.relative_to(SOURCE_ROOT).as_posix()


def read_module(path: Path) -> str:
    raw = path.read_text(encoding="utf-8")
    # The saved source mirror stores each factory body with its original closing `});`.
    body = re.sub(r"\s*\}\);\s*$", "", raw)
    # main.js is the entry source: its factory closure is generated by this script.
    if body == raw and module_id(path) != "src/main.js":
        raise ValueError(f"Source module is missing its expected closing wrapper: {path}")
    return body.rstrip()


def build_bundle() -> str:
    modules = sorted(MODULE_ROOT.rglob("*.js"), key=lambda p: module_id(p))
    if len(modules) != 49:
        raise ValueError(f"Expected 49 source modules, found {len(modules)}")
    ids = [module_id(path) for path in modules]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate module IDs detected")
    if "src/main.js" not in ids:
        raise ValueError("Missing application entry module src/main.js")

    chunks = [
        "(()=>{'use strict';",
        "const __modules=new Map();const __cache=new Map();",
        "const __require=(id)=>{if(__cache.has(id))return __cache.get(id);const factory=__modules.get(id);if(!factory)throw new Error(\"Bunaa module not found: \"+id);const exports={};__cache.set(id,exports);factory(exports,__require);return exports};",
    ]
    # Factories only register here; their contents execute on demand, after all modules are registered.
    for path in modules:
        key = module_id(path)
        body = read_module(path)
        chunks.append(f'__modules.set("{key}",(exports,__require)=>{{\n{body}\n}});')
    chunks.append('const __app=__require("src/main.js");if(typeof window!==\'undefined\'&&__app?.app)window.__BUNAA_APP=__app.app;})();')
    return "\n".join(chunks) + "\n"


def inject_bundle(path: Path, bundle: str) -> None:
    html = path.read_text(encoding="utf-8")
    pattern = re.compile(r"(<script>\s*" + re.escape(MARKER) + r"\s*)(.*?)(</script>)", re.S)
    updated, count = pattern.subn(lambda m: m.group(1) + bundle + m.group(3), html, count=1)
    if count != 1:
        raise ValueError(f"Could not locate the generated app script marker in {path.name}")
    if updated.count(MARKER) != 1:
        raise ValueError(f"Expected one generated app marker in {path.name}")
    path.write_text(updated, encoding="utf-8")


def main() -> int:
    bundle = build_bundle()
    BUNDLE_PATH.write_text(bundle, encoding="utf-8")
    for path in ENTRY_POINTS:
        inject_bundle(path, bundle)
    print(f"Built {len(list(MODULE_ROOT.rglob('*.js')))} modules → {BUNDLE_PATH.name}; updated {', '.join(p.name for p in ENTRY_POINTS)}")
    if "node" in sys.argv:
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
