const {uid,slugify,deepClone} = __require("src/core/utils.js");
const {normalizeVariables} = __require("src/core/variables.js");
const {normalizeAssets} = __require("src/core/assets.js");
const {normalizeInteraction} = __require("src/engine/interaction.js");
const {ensurePageMenu} = __require("src/core/navigation.js");
const SCHEMA_VERSION=30;
const DEFAULT_THEME={
  primary:'#5b5ce2',secondary:'#20a06a',accent:'#f4a340',surface:'#fff',soft:'#f6f7fb',text:'#171b2a',muted:'#6f778b',radius:14,font:'system-ui',
  tokens:{
    container:1180,
    colors:{primary:'#5b5ce2',secondary:'#20a06a',accent:'#f4a340',surface:'#fff',soft:'#f6f7fb',text:'#171b2a',muted:'#6f778b',line:'#e6e8ef'},
    spacing:{xs:4,sm:8,md:12,lg:18,xl:28,xxl:44},
    radii:{sm:8,md:12,lg:16,pill:999},
    shadows:{soft:'0 12px 30px rgba(25,30,55,.08)',medium:'0 20px 50px rgba(25,30,55,.12)'},
    typography:{h1:{size:52,lineHeight:1.08,weight:800},h2:{size:36,lineHeight:1.15,weight:800},h3:{size:26,lineHeight:1.2,weight:750},body:{size:16,lineHeight:1.65,weight:400},small:{size:13,lineHeight:1.5,weight:500}},
    motion:{fast:180,normal:360,slow:720}
  }
};
const DEFAULT_DEVICES={desktop:{width:1180},tablet:{width:768},mobile:{width:390}};
const DEFAULT_SETTINGS={advancedDevices:false,propagateDevices:false,snapToGrid:true,gridSize:8,autoSave:true,autoSaveMs:500};
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value);
function makeNode(type,props={},style={},children=[]){return {id:uid('node'),type,props:{...props},style:{marginTop:0,marginBottom:14,...style},responsive:{},classes:[],attrs:{},semantic:{tag:'div',role:'',ariaLabel:''},layout:{display:'block',direction:'column',gap:0,align:'stretch',justify:'start',wrap:false},visibility:{desktop:true,tablet:true,mobile:true},device:{created:null,touched:[]},locked:false,children:Array.isArray(children)?[...children]:[]}}
function makePage(name='الرئيسية',nodes=[],slug){const pageName=String(name||'الرئيسية').trim()||'الرئيسية';return {id:uid('page'),name:pageName,slug:slug||slugify(pageName),path:`/${slug||slugify(pageName)}`.replace('//','/'),seo:{title:pageName,description:'',image:'',canonical:'',noIndex:false},settings:{showInNav:true,hidden:false,template:false},status:'draft',dataBindings:[],nodes:Array.isArray(nodes)?nodes:[]}}
function makeProject(seed={}){const home=makePage('الرئيسية',seed.nodes||[],'home');const now=new Date().toISOString();const baseTheme=deepClone(DEFAULT_THEME);if(obj(seed.theme))Object.assign(baseTheme,deepClone(seed.theme));return {version:SCHEMA_VERSION,meta:{id:typeof seed.id==='string'?seed.id:uid('project'),name:String(seed.name||'مشروعي'),ownerId:typeof seed.ownerId==='string'?seed.ownerId:null,createdAt:now,updatedAt:now,template:seed.template||'',description:String(seed.description||'')},site:{title:String(seed.site?.title||seed.name||'موقع جديد'),description:String(seed.site?.description||'موقع تم بناؤه باستخدام بَنّاء.'),language:'ar',direction:'rtl',locale:'ar-OM',baseUrl:'',favicon:'',socialImage:'',author:'',brand:{name:'بَنّاء',logo:'',mark:'ب'},analytics:{provider:'none',measurementId:''},indexing:{robots:'index,follow',sitemap:true},links:{email:'',phone:'',whatsapp:''},...(obj(seed.site)?deepClone(seed.site):{})},theme:baseTheme,devices:{...DEFAULT_DEVICES,...(obj(seed.devices)?deepClone(seed.devices):{})},pages:[home],assets:Array.isArray(seed.assets)?deepClone(seed.assets):[],variables:obj(seed.variables)?deepClone(seed.variables):{},interactions:Array.isArray(seed.interactions)?deepClone(seed.interactions):[],navigation:{menus:[{id:'main',name:'الرئيسية',items:[]},{id:'footer',name:'التذييل',items:[]}],headerMenuId:'main',footerMenuId:'footer'},cms:{collections:[]},symbols:{definitions:[]},globals:{header:null,footer:null},styleLibrary:{classes:{},textStyles:{},effects:{}},release:{channel:'draft',status:'draft',version:1,publishedAt:null},seo:{enabled:true,canonicalMode:'auto'},settings:{...DEFAULT_SETTINGS,...(obj(seed.settings)?deepClone(seed.settings):{})},activePageId:home.id,activeNodeId:null}
}
const SAFE_SEMANTIC_TAGS=new Set('div section article aside header footer main nav figure figcaption details summary span p blockquote ul ol li dl dt dd h1 h2 h3 h4 h5 h6'.split(' '));
function normalizeSemantic(raw={}){const source=obj(raw)?raw:{};const rawTag=String(source.tag||'div').toLowerCase();return {tag:SAFE_SEMANTIC_TAGS.has(rawTag)?rawTag:'div',role:String(source.role||''),ariaLabel:String(source.ariaLabel||'')}}
function normalizeNode(raw,ids){const input=obj(raw)?raw:{};const id=typeof input.id==='string'&&!ids.has(input.id)?input.id:uid('node');ids.add(id);const classTokens=Array.isArray(input.classes)?input.classes.flatMap(value=>String(value).split(/\s+/).map(token=>token.trim()).filter(Boolean)):[ ];return {...input,id,type:typeof input.type==='string'&&input.type?input.type:'container',props:obj(input.props)?deepClone(input.props):{},style:{marginTop:0,marginBottom:14,...(obj(input.style)?input.style:{})},responsive:obj(input.responsive)?deepClone(input.responsive):{},classes:[...new Set(classTokens)],attrs:obj(input.attrs)?deepClone(input.attrs):{},semantic:normalizeSemantic(input.semantic),layout:{display:'block',direction:'column',gap:0,align:'stretch',justify:'start',wrap:false,...(obj(input.layout)?deepClone(input.layout):{})},visibility:{desktop:true,tablet:true,mobile:true,...(obj(input.visibility)?deepClone(input.visibility):{})},device:{created:input.device?.created||null,touched:Array.isArray(input.device?.touched)?[...new Set(input.device.touched.map(String))]:[]},locked:Boolean(input.locked),children:(Array.isArray(input.children)?input.children:[]).map(child=>normalizeNode(child,ids))}}
function uniqueSlug(value,used){const base=slugify(value);let candidate=base,index=2;while(used.has(candidate))candidate=`${base}-${index++}`;used.add(candidate);return candidate}
function uniquePath(value,fallbackSlug,used){let base=String(value||`/${fallbackSlug}`).trim().replace(/\s+/g,'-').replace(/\/{2,}/g,'/');if(!base.startsWith('/'))base='/'+base;if(base.length>1)base=base.replace(/\/$/,'');if(!base||base==='/')base='/';let candidate=base,index=2;while(used.has(candidate)){candidate=base==='/'?`/home-${index++}`:`${base}-${index++}`}used.add(candidate);return candidate}
function walkPages(pages,fn){for(const page of pages){walk(page.nodes,fn)}}
function normalizeNavbarLinks(page,allPages){walk(page.nodes,node=>{if(node.type!=='navbar')return;const labels=Array.isArray(node.props?.links)?node.props.links:[];const targets=Array.isArray(node.props?.linkTargets)?node.props.linkTargets:[];node.props.links=labels.map(x=>String(x));node.props.linkTargets=labels.map((label,index)=>{const explicit=targets[index];if(typeof explicit==='string'&&allPages.some(p=>p.id===explicit))return explicit;return allPages.find(p=>p.name===label)?.id||((index<allPages.length)?allPages[index].id:allPages[0]?.id||null)})})}
function mergeTheme(source){const theme=deepClone(DEFAULT_THEME);if(obj(source))Object.assign(theme,source);theme.tokens={...deepClone(DEFAULT_THEME.tokens),...(obj(source?.tokens)?source.tokens:{})};theme.tokens.colors={...DEFAULT_THEME.tokens.colors,...(obj(source?.tokens?.colors)?source.tokens.colors:{})};theme.tokens.spacing={...DEFAULT_THEME.tokens.spacing,...(obj(source?.tokens?.spacing)?source.tokens.spacing:{})};theme.tokens.radii={...DEFAULT_THEME.tokens.radii,...(obj(source?.tokens?.radii)?source.tokens.radii:{})};theme.tokens.shadows={...DEFAULT_THEME.tokens.shadows,...(obj(source?.tokens?.shadows)?source.tokens.shadows:{})};theme.tokens.typography={...deepClone(DEFAULT_THEME.tokens.typography),...(obj(source?.tokens?.typography)?source.tokens.typography:{})};for(const key of Object.keys(DEFAULT_THEME.tokens.typography))theme.tokens.typography[key]={...DEFAULT_THEME.tokens.typography[key],...(obj(source?.tokens?.typography?.[key])?source.tokens.typography[key]:{})};theme.tokens.motion={...DEFAULT_THEME.tokens.motion,...(obj(source?.tokens?.motion)?source.tokens.motion:{})};return theme}
function normalizeProject(project){
  const source=obj(project)?project:makeProject();const now=new Date().toISOString();const normalized=deepClone(source);normalized.version=SCHEMA_VERSION;
  normalized.meta=obj(normalized.meta)?normalized.meta:{};normalized.meta.id=typeof normalized.meta.id==='string'&&normalized.meta.id?normalized.meta.id:uid('project');normalized.meta.name=String(normalized.meta.name||'مشروعي').trim()||'مشروعي';normalized.meta.ownerId=typeof normalized.meta.ownerId==='string'&&normalized.meta.ownerId?normalized.meta.ownerId:null;normalized.meta.createdAt=normalized.meta.createdAt||now;normalized.meta.updatedAt=normalized.meta.updatedAt||now;
  normalized.theme=mergeTheme(normalized.theme);normalized.devices={...DEFAULT_DEVICES,...(obj(normalized.devices)?normalized.devices:{})};normalized.settings={...DEFAULT_SETTINGS,...(obj(normalized.settings)?normalized.settings:{})};normalized.assets=normalizeAssets(normalized.assets);normalized.variables=normalizeVariables(normalized.variables);normalized.site={title:String(normalized.site?.title||normalized.meta.name||'موقع جديد'),description:String(normalized.site?.description||'موقع تم بناؤه باستخدام بَنّاء.'),language:'ar',direction:'rtl',locale:'ar-OM',baseUrl:'',favicon:'',socialImage:'',author:'',brand:{name:'بَنّاء',logo:'',mark:'ب'},analytics:{provider:'none',measurementId:''},indexing:{robots:'index,follow',sitemap:true},links:{email:'',phone:'',whatsapp:''},...(obj(normalized.site)?normalized.site:{})};normalized.navigation={menus:[{id:'main',name:'الرئيسية',items:[]},{id:'footer',name:'التذييل',items:[]}],headerMenuId:'main',footerMenuId:'footer',...(obj(normalized.navigation)?normalized.navigation:{})};normalized.navigation.menus=(Array.isArray(normalized.navigation.menus)?normalized.navigation.menus:[]).map(menu=>({id:String(menu?.id||uid('menu')),name:String(menu?.name||'قائمة'),items:Array.isArray(menu?.items)?menu.items:[]}));normalized.cms={collections:Array.isArray(normalized.cms?.collections)?normalized.cms.collections:[]};normalized.symbols={definitions:Array.isArray(normalized.symbols?.definitions)?normalized.symbols.definitions:[]};normalized.globals={header:null,footer:null,...(obj(normalized.globals)?normalized.globals:{})};normalized.styleLibrary={classes:{},textStyles:{},effects:{},components:{},states:{},...(obj(normalized.styleLibrary)?normalized.styleLibrary:{})};normalized.release={channel:'draft',status:'draft',version:1,publishedAt:null,...(obj(normalized.release)?normalized.release:{})};normalized.seo={enabled:true,canonicalMode:'auto',...(obj(normalized.seo)?normalized.seo:{})};
  normalized.pages=Array.isArray(normalized.pages)&&normalized.pages.length?normalized.pages:[makePage()];const pageIds=new Set(),nodeIds=new Set(),slugs=new Set(),paths=new Set();normalized.pages=normalized.pages.map((raw,index)=>{const page=obj(raw)?raw:{};const name=String(page.name||`صفحة ${index+1}`).trim()||`صفحة ${index+1}`;const id=typeof page.id==='string'&&!pageIds.has(page.id)?page.id:uid('page');pageIds.add(id);const slug=uniqueSlug(page.slug||name,slugs);const pathValue=uniquePath(page.path||`/${slug}`,slug,paths);return {...page,id,name,slug,path:pathValue,type:page.type==='template'?'template':'page',parentId:typeof page.parentId==='string'?page.parentId:null,status:['draft','published','archived'].includes(page.status)?page.status:'draft',dataBindings:Array.isArray(page.dataBindings)?deepClone(page.dataBindings):[],seo:{title:name,description:'',image:'',canonical:'',noIndex:false,...(obj(page.seo)?deepClone(page.seo):{})},settings:{showInNav:true,hidden:false,template:false,...(obj(page.settings)?deepClone(page.settings):{})},nodes:(Array.isArray(page.nodes)?page.nodes:[]).map(node=>normalizeNode(node,nodeIds))}});for(const page of normalized.pages)if(page.parentId===page.id||!pageIds.has(page.parentId))page.parentId=null;normalized.activePageId=normalized.pages.some(page=>page.id===normalized.activePageId)?normalized.activePageId:normalized.pages[0].id;for(const page of normalized.pages)normalizeNavbarLinks(page,normalized.pages);
  const validNodeIds=new Set();const validPageIds=new Set(normalized.pages.map(page=>page.id));walkPages(normalized.pages,node=>validNodeIds.add(node.id));normalized.interactions=(Array.isArray(normalized.interactions)?normalized.interactions:[]).map(normalizeInteraction).filter(Boolean).filter(item=>validNodeIds.has(item.sourceId)).filter(item=>!item.options?.targetId||validNodeIds.has(item.options.targetId)).filter(item=>item.action!=='page'||!item.options?.pageId||validPageIds.has(item.options.pageId));
  const mainMenu=normalized.navigation.menus.find(menu=>menu.id===normalized.navigation.headerMenuId)||normalized.navigation.menus[0];if(mainMenu)ensurePageMenu(normalized,mainMenu.id);normalized.activeNodeId=validNodeIds.has(normalized.activeNodeId)?normalized.activeNodeId:null;return normalized
}
function walk(nodes,fn,parent=null){for(let index=0;index<(nodes||[]).length;index++){const current=nodes[index];fn(current,parent,index,nodes);if(current?.children?.length)walk(current.children,fn,current)}}
function findInPage(page,id){let hit=null;walk(page.nodes,(node,parent,index,nodes)=>{if(node.id===id)hit={node,parent,index,nodes,page}});return hit}
function findNode(project,id){const page=(project.pages||[]).find(item=>item.id===project.activePageId);return page?findInPage(page,id):null}
function findNodeGlobal(project,id){if(!id)return null;for(const page of project.pages||[]){const hit=findInPage(page,id);if(hit)return hit}return null}
function countNodes(project){let count=0;for(const page of project.pages||[])walk(page.nodes,()=>count++);return count}
function collectIds(project){const ids=new Set();for(const page of project.pages||[]){ids.add(page.id);walk(page.nodes,node=>ids.add(node.id))}return ids}
function nextPageName(project){let index=1;while(project.pages.some(page=>page.name===`صفحة ${index}`))index++;return `صفحة ${index}`}
exports.SCHEMA_VERSION = SCHEMA_VERSION;
exports.DEFAULT_THEME = DEFAULT_THEME;
exports.DEFAULT_DEVICES = DEFAULT_DEVICES;
exports.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
exports.makeNode = makeNode;
exports.makePage = makePage;
exports.makeProject = makeProject;
exports.normalizeProject = normalizeProject;
exports.walk = walk;
exports.findNode = findNode;
exports.findNodeGlobal = findNodeGlobal;
exports.countNodes = countNodes;
exports.collectIds = collectIds;
exports.nextPageName = nextPageName;
