#!/usr/bin/env python3
"""Dependency-free static integrity checks for the Bunaa Studio standalone package."""
from __future__ import annotations
import re
import shutil
import subprocess
import sys
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = "/* Bunaa Studio V35 — generated by build_bundle.py */"

class IdParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.ids = []
        self.tags = 0
    def handle_starttag(self, tag, attrs):
        self.tags += 1
        values = dict(attrs)
        if values.get("id"):
            self.ids.append(values["id"])
    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)


def require(condition: bool, message: str):
    if not condition:
        raise AssertionError(message)


def extract_bundle(html: str) -> str:
    match = re.search(r"<script>\s*" + re.escape(MARKER) + r"\s*(.*?)</script>", html, re.S)
    require(match is not None, "Generated application script marker was not found")
    return match.group(1).strip() + "\n"


def main() -> int:
    checks = []
    module_files = sorted((ROOT / "source" / "src" / "src").rglob("*.js"))
    bundle = (ROOT / "bundle-extracted.js").read_text(encoding="utf-8")
    require(len(module_files) == 49, f"Expected 49 source modules, found {len(module_files)}")
    checks.append("49 source modules present")
    module_ids = {p.relative_to(ROOT / "source" / "src").as_posix() for p in module_files}
    require(bundle.count("__modules.set(") == 49, "Embedded bundle module count differs from the source mirror")
    refs = set(re.findall(r'__require\(["\'](src/[^"\']+)["\']\)', bundle))
    missing = sorted(ref for ref in refs if ref not in module_ids)
    require(not missing, f"Missing module imports: {missing}")
    checks.append(f"{len(refs)} static module references resolve")

    html_files = [ROOT / "index.html", ROOT / "Bunaa.html"]
    parsed = {}
    for path in html_files:
        raw = path.read_text(encoding="utf-8")
        parsed[path.name] = raw
        require(extract_bundle(raw) == bundle.strip() + "\n", f"Embedded bundle is stale in {path.name}")
        parser = IdParser(); parser.feed(raw); parser.close()
        duplicates = sorted(k for k,v in Counter(parser.ids).items() if v > 1)
        require(not duplicates, f"Duplicate IDs in {path.name}: {duplicates}")
        require(raw.count('id="previewBtn"') == 1, f"Preview control is missing/duplicated in {path.name}")
        require('class="toolbar-more"' in raw and 'class="toolbar-more-menu"' in raw, f"Compact navigation menu missing in {path.name}")
        require('data-bunaa-version="35"' in raw and 'V35 HTML' in raw, f"Release version metadata is stale in {path.name}")
        require("overflow-x:visible!important" in raw, f"Non-scrolling toolbar override missing in {path.name}")
        secondary_ids = ["managePagesBtn", "siteSettingsBtn", "cmsBtn", "navigationBtn", "designBtn", "releaseBtn", "advancedDevicesBtn", "auditBtn", "backupBtn"]
        for element_id in secondary_ids:
            require(re.search(r'<button[^>]*id="' + re.escape(element_id) + r'"[^>]*class="toolbar-menu-item"', raw) is not None, f"Secondary action {element_id} is no longer in the More menu")
        checks.append(f"{path.name}: {parser.tags} static HTML elements, {len(parser.ids)} IDs, no duplicates")
    require(parsed["index.html"] == parsed["Bunaa.html"], "Standalone HTML entry points differ")
    checks.append("index.html and Bunaa.html are synchronized")
    checks.append("V35 release metadata is consistent and all 9 secondary toolbar actions remain in More")

    required_ids = ["homeBtn","projectMenuBtn","commandBtn","undoBtn","redoBtn","pagePrev","pageSelect","pageNext","managePagesBtn","siteSettingsBtn","cmsBtn","navigationBtn","designBtn","releaseBtn","advancedDevicesBtn","leftToggle","rightToggle","previewBtn","auditBtn","backupBtn","exportBtn"]
    for element_id in required_ids:
        require(parsed["index.html"].count(f'id="{element_id}"') == 1, f"Toolbar element {element_id} is missing or duplicated")
    checks.append(f"{len(required_ids)} existing toolbar action IDs retained")

    build_script = ROOT / "build_bundle.py"
    require(build_script.exists(), "Offline source-to-bundle builder is missing")
    checks.append("offline build script present")
    if shutil.which("node"):
        result = subprocess.run(["node", "--check", str(ROOT / "bundle-extracted.js")], capture_output=True, text=True)
        require(result.returncode == 0, f"JavaScript syntax check failed: {result.stderr}")
        checks.append("node --check: bundle syntax valid")
    else:
        checks.append("node --check skipped (Node.js not installed)")

    for file in [ROOT / "source/src/src/engine/workspace.js", ROOT / "source/src/src/engine/renderer.js"]:
        content = file.read_text(encoding="utf-8")
        require("node-resize-handle" in content or "beginNodeManipulation" in content, f"Expected mouse interaction hooks absent from {file.name}")
    require("didInitialFit" in (ROOT / "source/src/src/engine/workspace.js").read_text(encoding="utf-8") and "transformOrigin='top left'" in (ROOT / "source/src/src/engine/workspace.js").read_text(encoding="utf-8"), "Automatic canvas fit and stable transform origin are missing")
    checks.append("direct mouse move/resize hooks and responsive initial/viewport fit present in source modules")
    renderer_source = (ROOT / "source/src/src/engine/renderer.js").read_text(encoding="utf-8")
    exporter_source = (ROOT / "source/src/src/engine/exporter.js").read_text(encoding="utf-8")
    require("style.width='100%'" in renderer_source and "objectFit" in renderer_source, "Actual image content sizing/object-fit support is incomplete")
    require("collectExportResources" in exporter_source and "EXTERNAL_RESOURCES.md" in exporter_source and "assets/external-" in exporter_source, "Full-media export and external-resource report are incomplete")
    require("buildSingleFileHtml" in exporter_source and 'data-bunaa-single-page' in exporter_source and "exportCurrentHtml" in exporter_source and 'id="htmlPage"' in (ROOT / "source/src/src/ui/dialogs.js").read_text(encoding="utf-8"), "Selected-page single-file HTML export with all-page routing is incomplete")
    checks.append("single-file HTML export includes all linked pages and selected initial page control")
    require(all(f"def('{name}'" in (ROOT / "source/src/src/catalog/components.js").read_text(encoding="utf-8") for name in ("hero-split","blog-grid","product-grid","portfolio-grid","filterable-gallery","testimonial-carousel","contact-form","process-steps","trust-bar","faq-list","team-grid","service-grid","feature-bento","logo-cloud","event-list","review-grid","job-board")), "New component catalog patterns are incomplete")
    checks.append("image fill sizing, object-fit, media-aware ZIP export, CORS report, and seventeen catalog patterns including the new production UI blocks")
    require(len(re.findall(r"case\s*['\"]logo-cloud['\"]\s*:", renderer_source)) == 1, "Duplicate renderer branch may shadow the functional logo cloud renderer")
    checks.append("unique renderer branch for functional logo cloud")
    helper = ROOT / "tools" / "complete_export_assets.py"
    helper_test = ROOT / "tests" / "test_complete_export_assets.py"
    require(helper.exists() and helper_test.exists() and (ROOT / "tools" / "Complete-Website-Export.bat").exists(), "External media completion tool and launcher are missing")
    helper_test_result = subprocess.run([sys.executable, str(helper_test)], capture_output=True, text=True)
    require(helper_test_result.returncode == 0, f"External media helper test failed: {helper_test_result.stdout} {helper_test_result.stderr}")
    checks.append("external media completion helper, launcher, and mocked offline end-to-end test pass")
    require(all(f"['{edge}'" in renderer_source for edge in ("n", "e", "s", "w", "ne", "nw", "se", "sw")), "All eight resize grips are not defined")
    checks.append("all eight north/east/south/west/corner resize grips are present")
    dialogs_source = (ROOT / "source/src/src/ui/dialogs.js").read_text(encoding="utf-8")
    require("preview-iframe" in dialogs_source and "data-preview-device" in dialogs_source and "frame.srcdoc=this.previewHtml(key)" in dialogs_source and "this.previewHtml(currentDevice)" in dialogs_source, "Functional interactive preview controls are incomplete")
    require("preview-frame-shell" in parsed["index.html"] and "min-height:420px" in parsed["index.html"] and "preview-device-switcher" in parsed["index.html"], "Visible responsive preview layout styles are missing")
    checks.append("real iframe preview, desktop/tablet/mobile controls, refresh and pop-out hooks present")
    inspector_source = (ROOT / "source/src/src/ui/inspector.js").read_text(encoding="utf-8")
    workspace_source = (ROOT / "source/src/src/engine/workspace.js").read_text(encoding="utf-8")
    require("data-gradient-editor" in inspector_source and "gradientAddStop" in inspector_source and "radial-gradient" in inspector_source, "Multi-stop gradient editor controls are incomplete")
    require("fitPageHeight()" in workspace_source and "scheduleContentHeight()" in workspace_source and "canvasHeightByDevice" in workspace_source and "measureResizedNodeBottom" in workspace_source and "const desired=Math.max(320,Math.min(5000,Number(this.deviceWidth())||1180))" in workspace_source, "Manual-only vertical expansion and fixed device width contract is incomplete")
    fit_width_source = workspace_source[workspace_source.index("fitPageWidth(){"):workspace_source.index("fitPageHeight(){")]
    fit_height_source = workspace_source[workspace_source.index("fitPageHeight(){"):workspace_source.index("measureResizedNodeBottom(")]
    schedule_source = workspace_source[workspace_source.index("scheduleContentHeight(){"):workspace_source.index("reflowHost(){")]
    require("getBoundingClientRect" not in fit_width_source and "maxRight" not in fit_width_source, "Artboard width must not be inferred from element overflow")
    require("getBoundingClientRect" not in fit_height_source and "maxBottom" not in fit_height_source, "Page height must not be recomputed automatically from content")
    require("fitPageHeight()" not in schedule_source, "Content observer must not trigger page-height extension")
    checks.append("artboard width is device-fixed; only explicit vertical resize can persist extra canvas height")
    require("min-height:360px" in parsed["index.html"], "Content-sized canvas minimum-height contract is missing")
    checks.append("multi-stop linear/radial gradient and manual-only vertical extension contracts present")
    preview_runtime_source = (ROOT / "source/src/src/engine/preview-router.js").read_text(encoding="utf-8")
    require("!important" in exporter_source and "transform:translate3d" in exporter_source and "max-width:100%!important" in exporter_source, "Responsive export sizing/position overrides are incomplete")
    require("project.assets||[]" in dialogs_source and "stylesheet(theme,project)" in dialogs_source, "Preview does not use the real project stylesheet/assets")
    require("Bunaa Studio V35" in exporter_source and "deviceFrame?.offsetHeight" in workspace_source and "pageCanvas?.offsetHeight" in workspace_source, "Export/runtime version or scaled page scroll-height support is stale")
    require(all(term in preview_runtime_source for term in ("dblclick", "hoverleave", "focusout", "change", "keydown", "contextmenu", "setAttribute", "mediaPlay", "downloadAsset", "conditionPasses")), "Preview interaction coverage does not match the editor action vocabulary")
    require(all(term in preview_runtime_source for term in ("data-cart-add", "data-portfolio-filter", "data-carousel-move", "data-local-contact-form", "__BUNAA_CART")), "Built-in commerce, portfolio, carousel, or local form interactions are missing from preview")
    checks.append("preview and exported runtime share functional cart, filter, carousel, and form interactions")
    checks.append("device-responsive dimensions/positions and shared multi-trigger interactions are wired")
    checks.append("exported page metadata uses V35; fixed device width and saved user-triggered vertical extension are wired")
    for line in checks:
        print("PASS", line)
    print(f"RESULT: {len(checks)} integrity groups passed")
    return 0

if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        raise SystemExit(1)
