const {findNodeGlobal} = __require("src/core/model.js");
const {DEVICES,propagateStyle} = __require("src/engine/layout.js");
const {applyDevicePreset,deviceLabel} = __require("src/core/device-presets.js");
const {updateProps,updateStyle} = __require("src/core/commands.js");
const {showModal} = __require("src/ui/modal.js");
const {nodeHtml} = __require("src/engine/renderer.js");
const {listVariables} = __require("src/core/variables.js");
const {mixColors,gradientColors,contrastRatio,bestTextColor,hexToRgb} = __require("src/core/color-mixer.js");
const {findAsset,assetForNodeType} = __require("src/core/assets.js");
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const nativeHex=value=>{const v=String(value||'').trim();if(/^#[0-9a-f]{6}$/i.test(v))return v;if(/^#[0-9a-f]{3}$/i.test(v))return '#'+[...v.slice(1)].map(x=>x+x).join('');const m=v.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);if(m)return '#'+[m[1],m[2],m[3]].map(x=>Math.max(0,Math.min(255,Number(x))).toString(16).padStart(2,'0')).join('');return '#000000'};
const colorPalette=theme=>[theme?.primary,theme?.secondary,theme?.accent,theme?.surface,theme?.soft,theme?.text,theme?.muted,...Object.values(theme?.tokens?.colors||{}),'#ffffff','#000000','#ef4444','#f97316','#eab308','#22c55e','#06b6d4','#3b82f6','#8b5cf6','#ec4899'].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);

const STYLE_KEYS=new Set(['color','background','fontSize','radius','marginTop','marginBottom','width','height','minHeight','maxWidth','gap','opacity','paddingY','paddingX']);
function mediaKindForNode(node){return assetForNodeType(node?.type||'')}
function mediaAccept(kind){return kind==='image'?'image/*':kind==='video'?'video/*':kind==='audio'?'audio/*':kind==='document'?'.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.zip':kind==='font'?'.woff,.woff2,.ttf,.otf':'image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.md,.json,.zip,.woff,.woff2,.ttf,.otf'}
function colorMixerHtml(){return `<div class="color-mixer-box"><div class="color-mixer-head"><div><b>مزج الألوان</b><small>امزج لونين، وشاهد النتيجة مباشرة.</small></div><span class="mix-result-swatch" data-mix-result></span></div><div class="color-mix-grid"><label class="field"><span>اللون الأول</span><div class="mix-color-input"><input type="color" id="mixA" value="#5B5CE2"><input id="mixAText" value="#5B5CE2"></div></label><label class="field"><span>اللون الثاني</span><div class="mix-color-input"><input type="color" id="mixB" value="#20A06A"><input id="mixBText" value="#20A06A"></div></label></div><div class="field"><label>نسبة المزج <output id="mixRatioOut">50%</output></label><input id="mixRatio" type="range" min="0" max="100" value="50"></div><div class="field"><label>طريقة المزج</label><select id="mixSpace"><option value="rgb">RGB — متوازن</option><option value="hsl">HSL — ناعم</option></select></div><div class="mix-preview-row"><div><small>النتيجة</small><b id="mixHex">#6D7E76</b></div><div><small>تباين مع الأبيض</small><b id="mixContrast">—</b></div><button type="button" class="secondary-btn" id="mixCopy">نسخ اللون</button></div><div class="field"><label>Gradient جاهز</label><div class="gradient-preview" data-gradient-preview></div><code data-gradient-value>linear-gradient(90deg, #5B5CE2 0%, #20A06A 100%)</code><div class="mix-action-row"><button type="button" class="secondary-btn" data-apply-gradient>استخدم الـGradient في الخلفية</button><button type="button" class="secondary-btn" data-save-mix>حفظ اللون في ألوان الموقع</button></div></div></div>`}
class Inspector{
  constructor(store){this.store=store;this.device='desktop';this.advanced=false}
  mount(el){this.el=el;this.el.__assetService=this.assetService;this.render()}
  setDevice(d){if(!DEVICES.includes(d))return;this.device=d;const id=this.store.ui.selected;const hit=id?findNodeGlobal(this.store.project,id):null;if(hit&&!hit.node.responsive?.[d])this.store.transact('تهيئة إعدادات الجهاز',project=>{const current=findNodeGlobal(project,id);if(current)applyDevicePreset(current.node,d,{onlyMissing:true})});this.render()}
  field(label,key,value,type='text'){return `<div class="field"><label>${label}</label><input data-key="${key}" data-type="${type}" value="${esc(value)}"></div>`}
  textareaField(label,key,value,placeholder=''){return `<div class="field"><label>${label}</label><textarea data-key="${key}" rows="6" placeholder="${esc(placeholder)}">${esc(value)}</textarea></div>`}
  multiAssetField(node,kind,label){
    const current=Array.isArray(node.props?.assetIds)?node.props.assetIds:[];const assets=this.store.project.assets.filter(a=>kind==='mixed'||a.kind===kind);const preview=current.length?`${current.length} ملف محدد`:'لم يتم اختيار ملفات بعد';
    const choices=assets.map(a=>`<label class="asset-choice"><input type="checkbox" data-media-item value="${esc(a.id)}" ${current.includes(a.id)?'checked':''}><span><b>${esc(a.name)}.${esc(a.extension||'bin')}</b><small>${esc(a.originalName||a.kind)} • ${esc(a.kind)}</small></span></label>`).join('');
    return `<section class="media-binding multi-media-binding"><div class="media-binding-head"><div><b>${esc(label)}</b><small data-media-count>${esc(preview)}</small></div><span class="asset-current-icon">${current.length||'＋'}</span></div><div class="asset-choice-grid">${choices||'<div class="asset-choice-empty">لا توجد ملفات من هذا النوع حتى الآن. استخدم زر الرفع أو افتح المكتبة.</div>'}</div><div class="media-binding-actions"><button type="button" class="primary-btn" data-media-upload-multi>＋ رفع ملفات متعددة</button><button type="button" class="secondary-btn" data-open-assets>اختيار من مكتبة الوسائط</button></div><small class="media-help">علّم على الملفات التي تريد عرضها. لا تحتاج إلى الضغط على Ctrl أو Cmd.</small></section>`
  }
  pageEmbedField(node){
    const props=node.props||{};const pages=this.store.project.pages||[];const target=pages.find(page=>page.id===props.pageId)||pages.find(page=>page.id!==this.store.project.activePageId)||pages[0];
    const pageOptions=pages.map(page=>`<option value="${esc(page.id)}" ${target?.id===page.id?'selected':''}>${esc(page.name)}</option>`).join('');
    const nodes=[];const visit=list=>(list||[]).forEach(item=>{nodes.push(item);visit(item.children)});if(target)visit(target.nodes);
    const nodeOptions=`<option value="">اختر القسم</option>`+nodes.map(item=>`<option value="${esc(item.id)}" ${props.nodeId===item.id?'selected':''}>${esc(item.props?.title||item.props?.text||item.type)} (${esc(item.type)})</option>`).join('');
    return `<section class="page-embed-settings"><div class="field"><label>الصفحة المطلوبة</label><select data-key="pageId" data-embed-page>${pageOptions}</select></div><div class="field"><label>ماذا تريد أن تعرض؟</label><select data-key="mode"><option value="full" ${(!props.mode||props.mode==='full')?'selected':''}>الصفحة كاملة</option><option value="section" ${props.mode==='section'?'selected':''}>قسم أو عنصر محدد</option><option value="text" ${props.mode==='text'?'selected':''}>النص فقط</option></select></div><div class="field"><label>القسم / العنصر (اختياري)</label><select data-key="nodeId">${nodeOptions}</select></div>${this.field('الحد الأقصى للنص','textLimit',props.textLimit??1800,'number')}<small>إذا كانت الصفحة تحتوي على إدراج متبادل، يوقف النظام الحلقة تلقائيًا لتجنب التعليق.</small></section>`;
  }

  colorField(label,key,value,theme,device){
    const hex=nativeHex(value);const palette=colorPalette(theme);const swatches=palette.map((c,i)=>`<button type="button" class="color-swatch" title="${esc(c)}" data-color-value="${esc(c)}" style="background:${esc(c)}"></button>`).join('');
    return `<div class="field color-field" data-color-key="${esc(key)}"><label>${esc(label)}</label><div class="color-control"><button type="button" class="color-preview" data-color-trigger data-color-key="${esc(key)}" title="اختيار لون" style="background:${esc(value||hex)}"><span></span></button><input type="color" data-color-native data-color-key="${esc(key)}" value="${hex}" aria-label="${esc(label)}"><input class="color-text" data-color-text data-color-key="${esc(key)}" value="${esc(value||'')}" placeholder="#5b5ce2 أو rgba(...)" spellcheck="false"><button type="button" class="color-action" data-color-transparent>شفاف</button><button type="button" class="color-action" data-color-eyedropper ${globalThis.EyeDropper?'':'disabled'}>◉</button><button type="button" class="color-action" data-color-mix>مزج</button></div><div class="color-swatches">${swatches}</div><small>اضغط مربع اللون للاختيار، أو اكتب HEX / RGB / RGBA. يمكنك اختيار لون جاهز أو قطّارة النظام.</small></div>`;
  }
  destinationField(node,props){const options=[`<option value="#" ${!props.url||props.url==='#'?'selected':''}>بدون وجهة</option>`,...this.store.project.pages.map(page=>`<option value="page:${page.id}" ${props.url===`page:${page.id}`?'selected':''}>صفحة: ${esc(page.name)}</option>`),`<option value="__external__" ${props.url&&/^https?:\/\//i.test(props.url)?'selected':''}>رابط خارجي</option>`].join('');const external=this.field('الرابط الخارجي','url',/^https?:\/\//i.test(props.url||'')?props.url:'');return `<div class="field"><label>الوجهة</label><select data-destination-for="${node.id}">${options}</select></div><div data-external-wrap="${node.id}" class="${props.url&&/^https?:\/\//i.test(props.url)?'':'hidden'}">${external}</div>`}
  semanticText(label,key,value){return `<div class="field"><label>${label}</label><input data-semantic-text="${key}" value="${esc(value)}"></div>`}
  semanticField(label,key,value,options){return `<div class="field"><label>${label}</label><select data-semantic-key="${key}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`}
  layoutControl(label,key,value,options){return `<div class="field"><label>${label}</label><select data-layout-key="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`}
  mediaField(node){
    const kind=mediaKindForNode(node); if(!['image','video','audio','document','any','mixed','font','other'].includes(kind)) return '';
    const current=findAsset(this.store.project,node.props?.assetId); const assets=this.store.project.assets.filter(a=>kind==='any'||kind==='mixed'||a.kind===kind||(kind==='document'&&a.kind==='other')); const preview=current?(current.kind==='image'?`<img src="${esc(current.data)}" alt="${esc(current.alt||current.name)}">`:current.kind==='video'?`<span class="asset-current-icon">▶ VIDEO</span>`:current.kind==='audio'?`<span class="asset-current-icon">♫ AUDIO</span>`:`<span class="asset-current-icon">${esc((current.extension||'FILE').toUpperCase())}</span>`):'<span class="asset-current-icon">＋</span>';
    return `<section class="media-binding" data-media-kind="${kind}"><div class="media-binding-head"><div><b>الملف المرتبط</b><small>${current?`مرتبط بـ ${esc(current.name)} • ${esc(current.originalName)}`:'لم يتم اختيار ملف بعد'}</small></div><span class="asset-current-preview">${preview}</span></div><div class="media-binding-actions"><select data-media-select><option value="">${current?'تغيير الملف…':'اختر من المكتبة…'}</option>${assets.map(a=>`<option value="${esc(a.id)}" ${current?.id===a.id?'selected':''}>${esc(a.name)}.${esc(a.extension||'bin')} — ${esc(a.originalName)}</option>`).join('')}</select><button type="button" class="secondary-btn" data-media-upload>رفع من الجهاز</button><button type="button" class="secondary-btn" data-open-assets>فتح المكتبة</button></div><small class="media-help">الملف يُحفظ في مكتبة المشروع، ويمكن استخدامه في أكثر من عنصر.</small></section>`;
  }
  render(){
    if(!this.el)return;const id=this.store.ui.selected,hit=id?findNodeGlobal(this.store.project,id):null;if(!hit){this.el.classList.add('hidden');document.getElementById('inspectorEmpty').classList.remove('hidden');return}document.getElementById('inspectorEmpty').classList.add('hidden');this.el.classList.remove('hidden');
    const n=hit.node,p=n.props||{},s={...(n.style||{}),...(n.responsive?.[this.device]||{})},layout=n.layout||{};let content='';
    if(['heading','text','quote','badge','alert','button','link','marquee','gradient','glass'].includes(n.type))content+=this.field('النص','text',p.text||'');
    if(['button','link'].includes(n.type))content+=this.destinationField(n,p);
    if(n.type==='image')content+=this.mediaField(n)+this.field('الوصف البديل','alt',p.alt||'');
    if(['video','video-card','audio','download','document-viewer','file-card','avatar','logo','image-text'].includes(n.type))content+=this.mediaField(n);
    if(n.type==='gallery'||n.type==='image-carousel')content+=this.multiAssetField(n,'image','صور المعرض');
    if(n.type==='media-grid')content+=this.multiAssetField(n,'mixed','الوسائط المعروضة');
    if(n.type==='video-gallery')content+=this.multiAssetField(n,'video','مقاطع الفيديو');
    if(n.type==='audio-playlist')content+=this.multiAssetField(n,'audio','الملفات الصوتية');
    if(['gallery','media-grid','video-gallery'].includes(n.type))content+=this.field('عدد الأعمدة','columns',p.columns??(n.type==='gallery'?3:2),'number');
    if(n.type==='gallery')content+=this.field('عدد الصور الافتراضي','count',p.count??6,'number');
    if(['video-gallery','audio-playlist'].includes(n.type))content+=this.field('عنوان المجموعة','title',p.title||'');
    if(['document-viewer','file-card'].includes(n.type))content+=this.field('العنوان','title',p.title||'')+this.field('النص المساعد','text',p.text||'')+(n.type==='document-viewer'?this.field('ارتفاع العارض','height',p.height??640,'number'):this.field('نص الزر','button',p.button||''));
    if(n.type==='video-card')content+=this.field('عنوان الفيديو','title',p.title||'فيديو')+this.field('المدة','duration',p.duration||'');
    if(n.type==='page-embed')content+=this.pageEmbedField(n);
    if(n.type==='html-snippet')content+=this.textareaField('محتوى HTML (آمن)','html',p.html||'','اكتب فقرة أو عناوين أو جدولًا بسيطًا…')+'<div class="tips-card">تُحذف تلقائيًا السكربتات والروابط الخطرة والـiframe داخل هذا العنصر.</div>';
    if(n.type==='card')content+=this.field('العنوان','title',p.title||'')+this.field('الوصف','text',p.text||'')+this.field('نص الزر','button',p.button||'')+this.destinationField(n,p);
    if(n.type==='product')content+=this.field('الاسم','name',p.name||'')+this.field('السعر','price',p.price||'')+this.field('العملة','currency',p.currency||'')+this.destinationField(n,p);
    if(['input','textarea','select','search','file'].includes(n.type))content+=this.field('عنوان الحقل','label',p.label||'')+this.field('النص المساعد','placeholder',p.placeholder||'');
    if(n.type==='faq')content+=this.field('السؤال','question',p.question||'')+this.field('الإجابة','answer',p.answer||'');
    if(n.type==='navbar')content+=this.field('العلامة','brand',p.brand||'');
    if(n.type==='collection-list'){const opts=[`<option value="">اختر مجموعة…</option>`,...(this.store.project.cms?.collections||[]).map(c=>`<option value="${esc(c.id)}" ${p.collectionId===c.id?'selected':''}>${esc(c.name)}</option>`)].join('');content+=`<div class="field"><label>مجموعة CMS</label><select data-cms-collection="${n.id}">${opts}</select></div>`+this.field('عدد العناصر','limit',p.limit??6,'number')}
    const variables=listVariables(this.store.project);
    const boundTypes=new Set(['heading','text','button','link','image','card','product']);
    if(boundTypes.has(n.type)){content+=`<div class="field"><label>ربط محتوى بمتغير</label><select data-variable-bind><option value="">بدون</option>${variables.map(v=>`<option value="${esc(v.key)}" ${p.bindingVariable===v.key?'selected':''}>${esc(v.name)}</option>`).join('')}</select></div>`}
    if(n.type==='symbol-instance')content+=`<div class="tips-card"><b>مكون مشترك</b><p>تستخدم هذه النسخة تعريفًا مشتركًا. عدّل الأصل لتطبيق التغييرات على كل النسخ.</p></div>`;
    const classOptions=Object.keys(this.store.project.styleLibrary?.classes||{});const textStyleOptions=Object.keys(this.store.project.styleLibrary?.textStyles||{});const libraryPanel=`<div class="field-row"><div class="field"><label>Text Style</label><select data-style-library-text><option value="">بدون</option>${textStyleOptions.map(name=>`<option value="${esc(name)}" ${p.textStyle===name?'selected':''}>${esc(name)}</option>`).join('')}</select></div><div class="field"><label>Effect / State</label><select data-style-library-effect><option value="">بدون</option>${Object.keys(this.store.project.styleLibrary?.effects||{}).map(name=>`<option value="${esc(name)}" ${p.effect===name?'selected':''}>${esc(name)}</option>`).join('')}</select></div></div><div class="class-chips">${classOptions.length?classOptions.map(name=>`<button type="button" data-class-toggle="${esc(name)}" class="${(n.classes||[]).includes(name)?'active':''}">.${esc(name)}</button>`).join(''):'<small>أنشئ Classes من Design System لإعادة استخدامها.</small>'}</div>`;const semantic=`<div class="field-row">${this.semanticField('وسم HTML','tag',n.semantic?.tag||'div',[['div','div'],['section','section'],['header','header'],['main','main'],['nav','nav'],['article','article'],['aside','aside'],['footer','footer'],['button','button']])}${this.semanticField('الدور ARIA','role',n.semantic?.role||'', [['','افتراضي'],['banner','banner'],['navigation','navigation'],['main','main'],['contentinfo','contentinfo'],['article','article'],['region','region']])}</div>${this.semanticText('اسم ARIA','ariaLabel',n.semantic?.ariaLabel||'')}<div class="field"><label>Classes</label><input data-class-list value="${esc((n.classes||[]).join(', '))}"><small>افصل بين أسماء الكلاسات بفاصلة.</small></div>${libraryPanel}`;
    if(!content)content=this.field('اسم وصفي','label',p.label||'');
    const style=this.colorField('لون النص','color',s.color||'',this.store.project.theme,this.device)+this.colorField('الخلفية','background',s.background||'',this.store.project.theme,this.device)+`<div class="field-row">${this.field('حجم النص','fontSize',s.fontSize??'','number')}${this.field('الاستدارة','radius',s.radius??'','number')}</div><div class="field-row">${this.field('هامش أعلى','marginTop',s.marginTop??0,'number')}${this.field('هامش أسفل','marginBottom',s.marginBottom??14,'number')}</div>`;
    const structure=`<div class="field-row">${this.layoutControl('العرض', 'display', layout.display||'block', [['block','Block'],['flex','Flex'],['grid','Grid']])}${this.layoutControl('اتجاه', 'direction', layout.direction||'column', [['column','عمودي'],['row','أفقي']])}</div><div class="field-row">${this.layoutControl('المحاذاة','align',layout.align||'stretch',[['stretch','Stretch'],['start','Start'],['center','Center'],['end','End']])}${this.layoutControl('التوزيع','justify',layout.justify||'start',[['start','Start'],['center','Center'],['between','Between'],['end','End']])}</div><div class="field-row">${this.field('الفجوة','gap',s.gap??layout.gap??0,'number')}${this.layoutControl('التفاف','wrap',layout.wrap?'1':'0',[['0','لا'],['1','نعم']])}</div>`;
    const visibility=`<div class="visibility-grid">${DEVICES.map(d=>`<label><input type="checkbox" data-visibility-device="${d}" ${n.visibility?.[d]!==false?'checked':''}>${d}</label>`).join('')}</div>`;
    const createdLabel=n.device?.created?deviceLabel(n.device.created):'قبل تحديد الجهاز';
    this.el.innerHTML=`<div class="device-context"><b>المعاينة الآن: ${esc(deviceLabel(this.device))}</b><small>تمت تهيئة العنصر عند إنشائه على: ${esc(createdLabel)} • يمكنك تخصيص كل جهاز بشكل مستقل.</small></div><section class="inspector-section"><header><b>المحتوى</b><span>${n.type}</span></header><div class="inspector-body">${content}</div></section><section class="inspector-section"><header><b>المظهر</b><span>${this.device}</span></header><div class="inspector-body">${style}</div></section><section class="inspector-section"><header><b>البنية</b><span>Layout</span></header><div class="inspector-body">${structure}</div></section><section class="inspector-section"><header><b>Responsive</b><span>إظهار العنصر</span></header><div class="inspector-body">${visibility}<div class="segmented">${DEVICES.map(d=>`<button data-device="${d}" class="${d===this.device?'active':''}">${d}</button>`).join('')}</div><label class="sync-row"><span>مزامنة نسبية</span><input id="propagate" type="checkbox" ${this.store.project.settings.propagateDevices?'checked':''}></label></div></section><button id="toggleAdvanced" class="advanced-toggle">${this.advanced?'إخفاء التخصيص المتقدم':'التخصيص المتقدم'}</button>${this.advanced?`<section class="inspector-section"><div class="inspector-body">${this.field('العرض','width',s.width??'')}${this.field('الحد الأقصى','maxWidth',s.maxWidth??'')}${this.field('الارتفاع','height',s.height??'','number')}${this.field('الارتفاع الأدنى','minHeight',s.minHeight??'','number')}${this.field('العتامة','opacity',s.opacity??1,'number')}</div></section>`:''}${this.store.ui.mode==='trainee'?'<button id="codeBtn" class="advanced-toggle">&lt;/&gt; كود العنصر</button>':''}`;
    this.wire(n.id);
  }
  openColorMixer(fieldKey,wrap){
    const base=wrap.querySelector('[data-color-text]')?.value||'#5B5CE2';
    const body=colorMixerHtml(); const modal=showModal(document.getElementById('modalHost'),{title:'مزج الألوان',body,wide:true,actions:[{label:'إلغاء'},{label:'تطبيق النتيجة',kind:'primary',onClick:()=>{const color=modal.querySelector('#mixHex')?.textContent?.trim();if(color) {const input=wrap.querySelector('[data-color-text]');if(input){input.value=color;input.dispatchEvent(new Event('change',{bubbles:true}))}}modal.remove()}}]});
    const a=modal.querySelector('#mixA'),b=modal.querySelector('#mixB'),at=modal.querySelector('#mixAText'),bt=modal.querySelector('#mixBText'),ratio=modal.querySelector('#mixRatio'),space=modal.querySelector('#mixSpace');a.value=/^#[0-9a-f]{6}$/i.test(base)?base:'#5B5CE2';at.value=a.value;
    const update=()=>{const c=mixColors(at.value,bt.value,Number(ratio.value)/100,space.value)||'#000000';modal.querySelector('[data-mix-result]').style.background=c;modal.querySelector('#mixHex').textContent=c;modal.querySelector('#mixRatioOut').textContent=`${ratio.value}%`;const cr=contrastRatio(c,'#FFFFFF');modal.querySelector('#mixContrast').textContent=`${cr.toFixed(2)}:1`;const grad=gradientColors([{color:at.value,position:0},{color:bt.value,position:100}],90);modal.querySelector('[data-gradient-preview]').style.background=grad;modal.querySelector('[data-gradient-value]').textContent=grad};
    modal.querySelector('[data-apply-gradient]')?.addEventListener('click',()=>{const grad=modal.querySelector('[data-gradient-value]')?.textContent||'';if(fieldKey==='background'&&grad){const input=wrap.querySelector('[data-color-text]');if(input){input.value=grad;input.dispatchEvent(new Event('change',{bubbles:true}))}modal.remove()}});
    modal.querySelector('[data-save-mix]')?.addEventListener('click',()=>{const color=modal.querySelector('#mixHex')?.textContent?.trim();if(!color)return;this.store.transact('حفظ لون ممزوج',project=>{project.theme.tokens=project.theme.tokens||{};project.theme.tokens.colors={...(project.theme.tokens.colors||{})};let n=1;while(project.theme.tokens.colors[`mix${n}`]&&n<999)n++;project.theme.tokens.colors[`mix${n}`]=color});this.render();modal.remove()});
    a.oninput=()=>{at.value=a.value.toUpperCase();update()};b.oninput=()=>{bt.value=b.value.toUpperCase();update()};at.onchange=()=>{const v=/^#[0-9a-f]{6}$/i.test(at.value)?at.value:'#5B5CE2';at.value=v.toUpperCase();a.value=v;update()};bt.onchange=()=>{const v=/^#[0-9a-f]{6}$/i.test(bt.value)?bt.value:'#20A06A';bt.value=v.toUpperCase();b.value=v;update()};ratio.oninput=update;space.onchange=update;modal.querySelector('#mixCopy')?.addEventListener('click',()=>navigator.clipboard?.writeText(modal.querySelector('#mixHex').textContent||''));update();
  }

  wire(id){
    for(const input of this.el.querySelectorAll('[data-key]'))input.addEventListener('change',()=>{const key=input.dataset.key,type=input.dataset.type;let value=input.value;if(type==='number')value=value===''?0:Number(value);if(STYLE_KEYS.has(key)){updateStyle(this.store,id,{[key]:value},this.device);if(this.store.project.settings.propagateDevices)propagateStyle(findNodeGlobal(this.store.project,id)?.node,this.device,{[key]:value})}else updateProps(this.store,id,{[key]:value})});
    this.el.querySelector('[data-class-list]')?.addEventListener('change',event=>{const classes=[...new Set(String(event.target.value||'').split(',').map(x=>x.trim()).filter(Boolean))];updateProps(this.store,id,{classes})});
    this.el.querySelectorAll('[data-class-toggle]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.classToggle;this.store.transact('تبديل Class',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;const classes=new Set(hit.node.classes||[]);classes.has(name)?classes.delete(name):classes.add(name);hit.node.classes=[...classes]})}));
    this.el.querySelector('[data-style-library-text]')?.addEventListener('change',event=>updateProps(this.store,id,{textStyle:event.target.value}));
    this.el.querySelector('[data-style-library-effect]')?.addEventListener('change',event=>updateProps(this.store,id,{effect:event.target.value}));
    this.el.querySelectorAll('[data-semantic-text]').forEach(input=>input.addEventListener('change',()=>{const key=input.dataset.semanticText;this.store.transact('تعديل الدلالة والوصول',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;hit.node.semantic={tag:'div',role:'',ariaLabel:'',...(hit.node.semantic||{}),[key]:input.value}})}));
    this.el.querySelectorAll('[data-semantic-key]').forEach(select=>select.addEventListener('change',()=>{const key=select.dataset.semanticKey;this.store.transact('تعديل الدلالة والوصول',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;hit.node.semantic={tag:'div',role:'',ariaLabel:'',...(hit.node.semantic||{}),[key]:select.value}})}));
    this.el.querySelector('[data-variable-bind]')?.addEventListener('change',event=>updateProps(this.store,id,{bindingVariable:event.target.value}));
    this.el.querySelector('[data-media-select]')?.addEventListener('change',event=>{const assetId=event.target.value;if(assetId&&this.el.__assetService){this.el.__assetService.assignToNode(id,assetId);this.render()}});
    this.el.querySelector('[data-media-upload]')?.addEventListener('click',()=>{const input=document.createElement('input');input.type='file';input.accept=mediaAccept(mediaKindForNode(n));input.multiple=false;input.onchange=async()=>{const file=input.files?.[0];if(!file||!this.el.__assetService)return;try{const asset=await this.el.__assetService.addFile(file,{purpose:mediaKindForNode(n),attachTo:id,alt:file.name.replace(/\.[^.]+$/,'')});if(asset){this.render();this.store.setUI({selected:id})}}catch(error){globalThis.__BUNAA_APP?.toast?.(error.message||'تعذر رفع الملف')}};input.click()});
    this.el.querySelectorAll('[data-media-item]').forEach(control=>control.addEventListener('change',()=>{const selected=[...this.el.querySelectorAll('[data-media-item]:checked')].map(input=>input.value);this.el.__assetService?.assignMany(id,selected);const count=this.el.querySelector('[data-media-count]');if(count)count.textContent=selected.length?`${selected.length} ملف محدد`:'لم يتم اختيار ملفات بعد';const badge=this.el.querySelector('.asset-current-icon');if(badge)badge.textContent=selected.length||'＋';}));
    this.el.querySelector('[data-media-upload-multi]')?.addEventListener('click',()=>{const kind=mediaKindForNode(n);const input=document.createElement('input');input.type='file';input.accept=mediaAccept(kind);input.multiple=true;input.onchange=async()=>{try{const added=[];for(const file of [...(input.files||[])]){const asset=await this.el.__assetService?.addFile(file,{purpose:kind,alt:file.name.replace(/\.[^.]+$/,'')});if(asset)added.push(asset.id)}if(added.length){this.el.__assetService?.assignMany(id,[...(n.props?.assetIds||[]),...added]);this.render();this.store.setUI({selected:id})}}catch(error){globalThis.__BUNAA_APP?.toast?.(error.message||'تعذر رفع الملفات')}};input.click()});
    this.el.querySelector('[data-open-assets]')?.addEventListener('click',()=>document.getElementById('openAssetsBtn')?.click());
    this.el.querySelector('[data-embed-page]')?.addEventListener('change',()=>setTimeout(()=>this.render(),0));

    this.el.querySelectorAll('[data-cms-collection]').forEach(select=>select.addEventListener('change',()=>updateProps(this.store,id,{collectionId:select.value})));
    this.el.querySelectorAll('[data-destination-for]').forEach(select=>select.addEventListener('change',()=>{const value=select.value;if(value==='__external__'){const current=this.store.find(id)?.node?.props?.url||'';updateProps(this.store,id,{url:/^https?:\/\//i.test(current)?current:'https://'});this.el.querySelector(`[data-external-wrap="${id}"]`)?.classList.remove('hidden')}else{updateProps(this.store,id,{url:value});this.el.querySelector(`[data-external-wrap="${id}"]`)?.classList.add('hidden')}}));

    const applyColor=(key,value)=>{updateStyle(this.store,id,{[key]:value},this.device);if(this.store.project.settings.propagateDevices)propagateStyle(findNodeGlobal(this.store.project,id)?.node,this.device,{[key]:value});};
    this.el.querySelectorAll('.color-field').forEach(wrap=>{
      const text=wrap.querySelector('[data-color-text]'),native=wrap.querySelector('[data-color-native]'),preview=wrap.querySelector('[data-color-trigger]');
      const fieldKey=wrap.dataset.colorKey||text?.dataset?.colorKey||native?.dataset?.colorKey||preview?.dataset?.colorKey||'color';
      const sync=value=>{if(text)text.value=value;if(native&&/^#[0-9a-f]{6}$/i.test(nativeHex(value)))native.value=nativeHex(value);if(preview)preview.style.background=value||nativeHex(value)};
      native?.addEventListener('input',e=>{sync(e.target.value);applyColor(fieldKey,e.target.value)});
      text?.addEventListener('change',e=>{const value=String(e.target.value||'').trim();sync(value);applyColor(fieldKey,value)});
      preview?.addEventListener('click',()=>native?.click());
      wrap.querySelector('[data-color-transparent]')?.addEventListener('click',()=>{sync('transparent');applyColor(fieldKey,'transparent')});
      wrap.querySelectorAll('[data-color-value]').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.colorValue;sync(value);applyColor(fieldKey,value)}));
      wrap.querySelector('[data-color-eyedropper]')?.addEventListener('click',async()=>{if(!globalThis.EyeDropper)return;try{const result=await new EyeDropper().open();if(result?.sRGBHex){sync(result.sRGBHex);applyColor(fieldKey,result.sRGBHex)}}catch{}});
      wrap.querySelector('[data-color-mix]')?.addEventListener('click',()=>this.openColorMixer(fieldKey,wrap));

    });
    this.el.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>this.setDevice(b.dataset.device));
    this.el.querySelectorAll('[data-layout-key]').forEach(select=>select.addEventListener('change',()=>{const key=select.dataset.layoutKey;const value=key==='wrap'?select.value==='1':select.value;this.store.transact('تعديل بنية العنصر',p=>{const hit=findNodeGlobal(p,id);if(hit)hit.node.layout={...(hit.node.layout||{}),[key]:value}})}));
    this.el.querySelectorAll('[data-visibility-device]').forEach(input=>input.addEventListener('change',()=>this.store.transact('تعديل الظهور responsive',p=>{const hit=findNodeGlobal(p,id);if(hit)hit.node.visibility={...(hit.node.visibility||{}),[input.dataset.visibilityDevice]:input.checked}})));
    this.el.querySelector('#propagate')?.addEventListener('change',e=>this.store.transact('إعداد مزامنة',p=>p.settings.propagateDevices=e.target.checked));this.el.querySelector('#toggleAdvanced')?.addEventListener('click',()=>{this.advanced=!this.advanced;this.render()});
    this.el.querySelector('#codeBtn')?.addEventListener('click',()=>{const hit=this.store.find(id);if(hit)showModal(document.getElementById('modalHost'),{title:'كود العنصر',body:`<div class="field"><textarea readonly style="height:260px">${esc(nodeHtml(hit.node,this.store.project.theme,this.store.project,this.device))}</textarea></div>`})});
  }
}
exports.Inspector = Inspector;
