const {makeNode,makePage,normalizeProject} = __require("src/core/model.js");
const {uid,deepClone} = __require("src/core/utils.js");
const {factory} = __require("src/catalog/components.js");
const localImage=()=>factory('image');const hero=()=>factory('hero');const card=()=>factory('card');const heading=text=>makeNode('heading',{text},{fontSize:38,fontWeight:800,color:'#171b2a',align:'right'});const bodyText=text=>makeNode('text',{text},{fontSize:14,color:'#636c7e',lineHeight:1.8,align:'right'});const button=(text,url='#')=>makeNode('button',{text,url,action:'url'},{background:'#5b5ce2',color:'#fff',fontSize:12,fontWeight:800,paddingY:10,paddingX:18,radius:10,align:'right'});const section=(children,style={})=>makeNode('section',{}, {background:'#fff',padding:42,...style},children);const grid=(children,count=3)=>makeNode('grid',{count,gap:16},{display:'grid',gridTemplateColumns:`repeat(${count},minmax(0,1fr))`,gap:16},children);const navbar=()=>makeNode('navbar',{brand:'بَنّاء',links:['الرئيسية','الخدمات','من نحن','تواصل']},{background:'#fff',paddingY:14,paddingX:22,borderBottom:'1px solid #e7e9ef'});const footer=()=>makeNode('footer',{brand:'بَنّاء',text:'كل الحقوق محفوظة.'},{background:'#151924',color:'#fff',padding:28});
function landing(){return {name:'Landing احترافي',description:'صفحة هبوط كاملة للشركات والمنتجات.',thumbnail:'linear',pages:[makePage('الرئيسية',[navbar(),hero(),section([heading('لماذا بَنّاء؟'),bodyText('كل ما تحتاجه لبناء موقع سريع وواضح وقابل للتخصيص.'),grid([card(),card(),card()])]),section([heading('جاهز للانطلاق؟'),bodyText('حوّل فكرتك إلى موقع يعمل الآن.'),button('ابدأ مجانًا')],{background:'#f5f6ff'}),footer()],'home')]}}
function agency(){return {name:'شركة وخدمات',description:'صفحة شركة مع خدمات وأرقام وشهادات.',thumbnail:'agency',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('خدماتنا'),grid([card(),card(),card()],3)]),section([heading('نتائج نعتز بها'),factory('stats'),factory('testimonial')],{background:'#f7f8fb'}),footer()]),makePage('الخدمات',[navbar(),section([heading('الخدمات'),bodyText('مجموعة خدمات عملية يمكنك تعديلها.'),grid([card(),card(),card(),card()],2)]),footer()]),makePage('تواصل',[navbar(),section([heading('تواصل معنا'),factory('form')]),footer()])]}}
function portfolio(){return {name:'معرض أعمال',description:'صفحة أعمال ومشاريع قابلة للعرض.',thumbnail:'portfolio',pages:[makePage('الرئيسية',[navbar(),hero(),section([heading('أعمال مختارة'),grid([localImage(),localImage(),localImage(),localImage()],2)]),section([heading('من عملائنا'),factory('testimonial'),factory('rating')]),footer()])]}}
function store(){return {name:'متجر بسيط',description:'واجهة متجر ببطاقات منتجات وأسعار.',thumbnail:'store',pages:[makePage('الرئيسية',[navbar(),section([heading('منتجات مختارة'),bodyText('اختر ما يناسبك بسهولة.'),grid([factory('product'),factory('product'),factory('product')])]),section([heading('الأسئلة الشائعة'),factory('accordion')]),footer()]),makePage('منتج',[navbar(),section([localImage(),heading('منتج مميز'),bodyText('وصف المنتج وسعره ومعلوماته.'),button('أضف إلى السلة')]),footer()])]}}
function education(){return {name:'تعليمي',description:'صفحة تعليمية مع وحدات ومراحل.',thumbnail:'edu',pages:[makePage('الدروس',[navbar(),section([heading('تعلم خطوة بخطوة'),factory('progress'),grid([card(),card(),card()],3)]),section([heading('الأسئلة الشائعة'),factory('faq'),factory('faq')]),footer()]),makePage('عن الدورة',[navbar(),section([hero()]),section([heading('المحتوى'),factory('timeline')]),footer()])]}}
function blog(){return {name:'مدونة',description:'قالب مقالات مع بطاقات وتصنيفات.',thumbnail:'blog',pages:[makePage('الرئيسية',[navbar(),section([heading('آخر المقالات'),grid([card(),card(),card(),card()],2)]),section([heading('اشترك'),factory('input'),button('اشتراك')],{background:'#f7f8fb'}),footer()]),makePage('مقال',[navbar(),section([heading('عنوان المقال'),bodyText('محتوى المقال التجريبي…'),bodyText('يمكنك استبدال النص وإضافة صور ومحتويات أخرى.')]),footer()])]}}
function dashboard(){return {name:'لوحة تحكم',description:'واجهة بيانات وإحصاءات.',thumbnail:'dashboard',pages:[makePage('لوحة البيانات',[navbar(),section([heading('ملخص اليوم'),factory('stats'),grid([factory('chart'),factory('chart')],2)]),section([heading('العمليات الأخيرة'),factory('table')]),footer()])]}}
function restaurant(){return {name:'مطعم',description:'صفحة مطعم مع قائمة وطريقة تواصل.',thumbnail:'food',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('قائمة اليوم'),grid([card(),card(),card(),card()],2)]),section([heading('احجز طاولتك'),factory('form')]),footer()])]}}
function personal(){return {name:'شخصي',description:'صفحة تعريفية شخصية أنيقة.',thumbnail:'personal',pages:[makePage('الرئيسية',[section([heading('مرحبًا، أنا صاحب المشروع'),bodyText('نبذة قصيرة يمكن تعديلها بسهولة.'),button('تواصل معي')]),section([heading('مهاراتي'),factory('progress'),factory('progress'),factory('progress')],{background:'#f7f8fb'}),footer()])]}}
function saas(){return {name:'SaaS منتج رقمي',description:'واجهة منتج اشتراكي مع مزايا وأسعار وشهادات.',thumbnail:'saas',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('مزايا المنتج'),grid([factory('feature-list'),factory('feature-list'),factory('highlight')],3)]),section([heading('الأسعار'),factory('pricing')],{background:'#f7f8fb'}),section([heading('لماذا نحن؟'),grid([factory('testimonial'),factory('testimonial')])]),section([factory('newsletter')]),footer()]),makePage('التسعير',[navbar(),section([heading('الخطط والأسعار'),factory('pricing'),factory('compare')]),footer()])]}}
function startup(){return {name:'Startup',description:'صفحة إطلاق شركة ناشئة سريعة.',thumbnail:'startup',pages:[makePage('الرئيسية',[navbar(),factory('announcement'),section([hero()]),section([heading('أرقام سريعة'),factory('stats')]),section([heading('كيف نعمل'),factory('stepper')],{background:'#f7f8fb'}),section([factory('cta')]),footer()])]}}
function event(){return {name:'فعالية',description:'صفحة فعالية أو مؤتمر مع برنامج وتسجيل.',thumbnail:'event',pages:[navbarPage(),makePage('البرنامج',[navbar(),section([heading('البرنامج'),factory('timeline'),factory('schedule')]),footer()]),makePage('التسجيل',[navbar(),section([heading('سجل حضورك'),factory('lead-form')]),footer()])]}}
function clinic(){return {name:'عيادة وخدمة',description:'موقع عيادة مع خدمات ومواعيد وتواصل.',thumbnail:'clinic',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('خدماتنا'),grid([card(),card(),card()],3)]),section([heading('احجز موعدًا'),factory('lead-form')],{background:'#f7f8fb'}),footer()]),makePage('الخدمات',[navbar(),section([heading('الخدمات'),grid([card(),card(),card(),card()],2)]),footer()])]}}
function realEstate(){return {name:'عقارات',description:'واجهة عقارية مع بطاقات وقائمة.',thumbnail:'realestate',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('عقارات مختارة'),grid([factory('product'),factory('product'),factory('product')],3)]),section([heading('لماذا نحن'),factory('feature-list')],{background:'#f7f8fb'}),footer()]),makePage('تفاصيل',[navbar(),section([heading('تفاصيل العقار'),factory('image'),factory('compare'),factory('lead-form')]),footer()])]}}
function cv(){return {name:'سيرة شخصية',description:'صفحة شخصية للعمل والأعمال.',thumbnail:'cv',pages:[makePage('الرئيسية',[section([factory('logo'),heading('مرحبًا، أنا صاحب الملف'),bodyText('مصمم ومطور يهتم بالتجارب الرقمية الواضحة.'),factory('social-proof'),button('تواصل معي')]),section([heading('المهارات'),factory('progress'),factory('progress'),factory('progress')],{background:'#f7f8fb'}),section([heading('أعمال مختارة'),grid([localImage(),localImage(),localImage()],3)]),footer()])]}}
function navbarPage(){return makePage('التسجيل',[navbar(),section([hero()]),footer()])}
function ecommerce(){return {name:'متجر متكامل',description:'واجهة متجر متعددة الصفحات مع منتج وسلة وFAQ.',thumbnail:'ecommerce',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('الأكثر مبيعًا'),grid([factory('product'),factory('product'),factory('product'),factory('product')],4)]),section([factory('logo-row'),factory('social-proof')],{background:'#f7f8fb'}),footer()]),makePage('المنتجات',[navbar(),section([heading('كل المنتجات'),factory('collection-list'),grid([factory('product'),factory('product'),factory('product'),factory('product')],4)]),footer()]),makePage('السلة',[navbar(),section([heading('مراجعة الطلب'),factory('table'),factory('cta')]),footer()])]}}
function creator(){return {name:'صانع محتوى',description:'صفحة منشئ محتوى مع أعمال واشتراك وشبكات اجتماعية.',thumbnail:'creator',pages:[makePage('الرئيسية',[navbar(),section([factory('avatar'),heading('مرحبًا، أنا صانع المحتوى'),bodyText('نبذة عنك وعن المجال الذي تقدمه.'),factory('social-links'),button('تواصل')]),section([heading('أحدث الأعمال'),grid([factory('video-card'),factory('video-card'),factory('video-card')],3)]),section([factory('newsletter')]),footer()])]}}
function nonprofit(){return {name:'مؤسسة غير ربحية',description:'موقع مبادرة أو مؤسسة مع أهداف وتبرعات ونتائج.',thumbnail:'nonprofit',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('أثرنا'),factory('stats'),factory('feature-grid')],{background:'#f7f8fb'}),section([heading('قصص المجتمع'),factory('testimonial-card'),factory('image-text')]),section([factory('cta')]),footer()]),makePage('عن المبادرة',[navbar(),section([heading('من نحن'),factory('richtext')]),footer()]),makePage('تبرع',[navbar(),section([heading('ادعم المبادرة'),factory('pricing-card'),factory('lead-form')]),footer()])]}}
function course(){return {name:'دورة مدفوعة',description:'موقع دورة احترافي مع دروس وأسعار وتسجيل.',thumbnail:'course',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('ماذا ستتعلم؟'),factory('feature-grid')]),section([heading('المنهج'),factory('stepper'),factory('timeline')],{background:'#f7f8fb'}),section([factory('pricing-card')]),footer()]),makePage('المنهج',[navbar(),section([heading('المحتوى الكامل'),factory('accordion'),factory('progress')]),footer()]),makePage('التسجيل',[navbar(),section([heading('ابدأ التعلم'),factory('lead-form')]),footer()])]}}
function freelancer(){return {name:'مستقل وخدمات',description:'عرض خدمات مستقل مع مشاريع وتسعير وتواصل.',thumbnail:'freelance',pages:[makePage('الرئيسية',[navbar(),section([factory('avatar'),heading('أحوّل الأفكار إلى منتجات رقمية'),bodyText('خدمات تصميم وتطوير وتجارب رقمية.'),factory('cta')]),section([heading('الخدمات'),grid([factory('card'),factory('card'),factory('card')],3)]),section([heading('أعمال مختارة'),grid([factory('image-text'),factory('image-text')],2)]),footer()]),makePage('الخدمات',[navbar(),section([heading('الخدمات'),factory('feature-grid'),factory('pricing')]),footer()]),makePage('تواصل',[navbar(),section([heading('تواصل معنا'),factory('contact-card'),factory('lead-form')]),footer()])]}}
function appLanding(){return {name:'منتج تطبيق',description:'صفحة تطبيق جوال مع مزايا ولقطات وأسئلة.',thumbnail:'app',pages:[makePage('الرئيسية',[navbar(),section([hero(),factory('download')]),section([heading('داخل التطبيق'),grid([localImage(),localImage(),localImage()],3)]),section([heading('لماذا التطبيق؟'),factory('feature-grid')]),section([factory('faq'),factory('cta')]),footer()])]}}
function conference(){return {name:'مؤتمر',description:'مؤتمر متعدد الصفحات مع متحدثين وجدول وتسجيل.',thumbnail:'conference',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('المتحدثون'),factory('team')]),section([heading('لماذا تحضر؟'),factory('feature-grid')]),section([factory('cta')]),footer()]),makePage('البرنامج',[navbar(),section([heading('البرنامج'),factory('schedule'),factory('timeline')]),footer()]),makePage('التسجيل',[navbar(),section([heading('سجل الآن'),factory('lead-form'),factory('contact-card')]),footer()])]}}
function hospitality(){return {name:'فندق وإقامة',description:'موقع إقامة مع غرف ومزايا وحجز.',thumbnail:'hotel',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('الغرف'),grid([factory('image-text'),factory('image-text')],2)]),section([heading('الخدمات'),factory('feature-grid')],{background:'#f7f8fb'}),section([heading('احجز'),factory('lead-form')]),footer()]),makePage('الغرف',[navbar(),section([heading('الغرف والأجنحة'),factory('gallery'),grid([factory('pricing-card'),factory('pricing-card')],2)]),footer()])]}}
function jobBoard(){return {name:'وظائف وتوظيف',description:'واجهة وظائف وصفحات شركة وتقديم.',thumbnail:'jobs',pages:[makePage('الرئيسية',[navbar(),section([hero()]),section([heading('الوظائف المفتوحة'),factory('collection-list'),grid([factory('card'),factory('card'),factory('card')],3)]),section([heading('لماذا تعمل معنا؟'),factory('feature-grid')]),footer()]),makePage('الوظيفة',[navbar(),section([heading('مسمى وظيفي'),factory('richtext'),factory('lead-form')]),footer()])]}}
const baseTemplates=[landing(),agency(),portfolio(),store(),education(),blog(),dashboard(),restaurant(),personal(),saas(),startup(),event(),clinic(),realEstate(),cv(),ecommerce(),creator(),nonprofit(),course(),freelancer(),appLanding(),conference(),hospitality(),jobBoard()];
const templates=baseTemplates;
const templateByName=name=>templates.find(template=>template.name===name);
function materializeTemplate(template){const t=deepClone(template);for(const page of t.pages){page.id=uid('page');page.slug=undefined;page.seo={title:page.name,description:'',image:''};page.nodes=(page.nodes||[]).map(remapTree)}const project=normalizeProject({version:12,meta:{name:t.name},pages:t.pages,theme:t.theme,devices:t.devices,assets:t.assets,variables:t.variables,interactions:t.interactions,settings:t.settings,activePageId:t.pages[0].id});for(const page of project.pages){page.nodes=page.nodes||[]}return {name:t.name,description:t.description,pages:project.pages,theme:project.theme,devices:project.devices,assets:project.assets,variables:project.variables,interactions:project.interactions,settings:project.settings,activePageId:project.activePageId}}
function remapTree(node){const copy=deepClone(node);copy.id=uid('node');copy.children=(copy.children||[]).map(remapTree);return copy}
const validateTemplate=t=>Boolean(t?.name&&Array.isArray(t.pages)&&t.pages.length>0&&t.pages.every(p=>p.name&&Array.isArray(p.nodes)));
exports.templates = templates;
exports.templateByName = templateByName;
exports.materializeTemplate = materializeTemplate;
exports.validateTemplate = validateTemplate;
});
