const {findNodeGlobal} = __require("src/core/model.js");
const {DEVICES,propagateStyle} = __require("src/engine/layout.js");
const {applyDevicePreset,deviceLabel} = __require("src/core/device-presets.js");
const {updateProps,updateStyle} = __require("src/core/commands.js");
const {showModal} = __require("src/ui/modal.js");
const {nodeHtml} = __require("src/engine/renderer.js");
const {listVariables} = __require("src/core/variables.js");
const {mixColors,gradientColors,contrastRatio,bestTextColor,hexToRgb} = __require("src/core/color-mixer.js");
const {findAsset,assetForNodeType} = __require("src/core/assets.js");
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const nativeHex=value=>{const v=String(value||'').trim();if(/^#[0-9a-f]{6}$/i.test(v))return v;if(/^#[0-9a-f]{3}$/i.test(v))return '#'+[...v.slice(1)].map(x=>x+x).join('');const m=v.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);if(m)return '#'+[m[1],m[2],m[3]].map(x=>Math.max(0,Math.min(255,Number(x))).toString(16).padStart(2,'0')).join('');return '#000000'};
const colorPalette=theme=>[theme?.primary,theme?.secondary,theme?.accent,theme?.surface,theme?.soft,theme?.text,theme?.muted,...Object.values(theme?.tokens?.colors||{}),'#ffffff','#000000','#ef4444','#f97316','#eab308','#22c55e','#06b6d4','#3b82f6','#8b5cf6','#ec4899'].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);
const parseGradientColor=value=>{const v=String(value||'').trim();return /^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(v)||/^rgba?\(/i.test(v)?nativeHex(v):null};
function splitGradientParts(value){const parts=[];let depth=0,start=0;for(let i=0;i<value.length;i++){if(value[i]==='(')depth++;else if(value[i]===')')depth=Math.max(0,depth-1);else if(value[i]===','&&depth===0){parts.push(value.slice(start,i).trim());start=i+1}}parts.push(value.slice(start).trim());return parts.filter(Boolean)}
function parseGradientValue(value,theme={}){
  const match=String(value||'').trim().match(/^(linear|radial)-gradient\((.*)\)$/i);
  const fallbackA=parseGradientColor(value)||parseGradientColor(theme.primary)||'#5B5CE2';
  const fallbackB=parseGradientColor(theme.secondary)||'#20A06A';
  if(!match)return {type:'linear',angle:135,stops:[{color:fallbackA,position:0},{color:fallbackB,position:100}]};
  const type=match[1].toLowerCase(),parts=splitGradientParts(match[2]);let angle=135,start=0;
  if(parts.length&&type==='linear'){
    const head=parts[0];const deg=head.match(/^(-?\d+(?:\.\d+)?)deg$/i);
    const directionAngles={'to top':0,'to right':90,'to bottom':180,'to left':270,'to top right':45,'to right top':45,'to bottom right':135,'to right bottom':135,'to bottom left':225,'to left bottom':225,'to top left':315,'to left top':315};
    if(deg){angle=((Number(deg[1])%360)+360)%360;start=1}else if(directionAngles[head.toLowerCase()]!==undefined){angle=directionAngles[head.toLowerCase()];start=1}
  }else if(parts.length&&type==='radial'&&!parseGradientColor(parts[0]))start=1;
  const stops=parts.slice(start).map((part,index,all)=>{
    const positioned=part.match(/\s+(-?\d+(?:\.\d+)?)%\s*$/);const rawColor=positioned?part.slice(0,positioned.index).trim():part;
    const color=parseGradientColor(rawColor);if(!color)return null;
    return {color,position:positioned?Math.min(100,Math.max(0,Number(positioned[1]))):(index/Math.max(1,all.length-1))*100};
  }).filter(Boolean).slice(0,8);
  if(stops.length<2)return {type:'linear',angle:135,stops:[{color:fallbackA,position:0},{color:fallbackB,position:100}]};
  return {type,angle,stops:stops.sort((a,b)=>a.position-b.position)};
}
function gradientValue(type,angle,stops){
  const list=[...stops].sort((a,b)=>Number(a.position)-Number(b.position)).map(stop=>`${parseGradientColor(stop.color)||'#000000'} ${Math.min(100,Math.max(0,Number(stop.position)||0))}%`).join(', ');
  return type==='radial'?`radial-gradient(circle at center, ${list})`:`linear-gradient(${Math.round(Math.min(360,Math.max(0,Number(angle)||0)))}deg, ${list})`;
}

const STYLE_KEYS=new Set(['color','background','fontSize','radius','marginTop','marginBottom','width','height','minHeight','maxWidth','gap','opacity','paddingY','paddingX']);
function mediaKindForNode(node){return assetForNodeType(node?.type||'')}
function mediaAccept(kind){return kind==='image'?'image/*':kind==='video'?'video/*':kind==='audio'?'audio/*':kind==='document'?'.pdf,.doc,.docx,.txt,.zip':'*/*'}
function colorMixerHtml(){return `<div class="color-mixer-box"><div class="color-mixer-head"><div><b>مزج الألوان</b><small>امزج لونين، وشاهد النتيجة مباشرة.</small></div><span class="mix-result-swatch" data-mix-result></span></div><div class="color-mix-grid"><label class="field"><span>اللون الأول</span><div class="mix-color-input"><input type="color" id="mixA" value="#5B5CE2"><input id="mixAText" value="#5B5CE2"></div></label><label class="field"><span>اللون الثاني</span><div class="mix-color-input"><input type="color" id="mixB" value="#20A06A"><input id="mixBText" value="#20A06A"></div></label></div><div class="field"><label>نسبة المزج <output id="mixRatioOut">50%</output></label><input id="mixRatio" type="range" min="0" max="100" value="50"></div><div class="field"><label>طريقة المزج</label><select id="mixSpace"><option value="rgb">RGB — متوازن</option><option value="hsl">HSL — ناعم</option></select></div><div class="mix-preview-row"><div><small>النتيجة</small><b id="mixHex">#6D7E76</b></div><div><small>تباين مع الأبيض</small><b id="mixContrast">—</b></div><button type="button" class="secondary-btn" id="mixCopy">نسخ اللون</button></div><div class="field"><label>Gradient جاهز</label><div class="gradient-preview" data-gradient-preview></div><code data-gradient-value>linear-gradient(90deg, #5B5CE2 0%, #20A06A 100%)</code><div class="mix-action-row"><button type="button" class="secondary-btn" data-apply-gradient>استخدم الـGradient في الخلفية</button><button type="button" class="secondary-btn" data-save-mix>حفظ اللون في ألوان الموقع</button></div></div></div>`}
class Inspector{
  constructor(store){this.store=store;this.device='desktop';this.advanced=false}
  mount(el){this.el=el;this.el.__assetService=this.assetService;this.render()}
  setDevice(d){if(!DEVICES.includes(d))return;this.device=d;const id=this.store.ui.selected;const hit=id?findNodeGlobal(this.store.project,id):null;if(hit&&!hit.node.responsive?.[d])this.store.transact('تهيئة إعدادات الجهاز',project=>{const current=findNodeGlobal(project,id);if(current)applyDevicePreset(current.node,d,{onlyMissing:true})});this.render()}
  field(label,key,value,type='text'){return `<div class="field"><label>${label}</label><input data-key="${key}" data-type="${type}" value="${esc(value)}"></div>`}
  recordsText(node){const items=Array.isArray(node.props?.items)?node.props.items:[];return items.map(item=>{if(Array.isArray(item))return item.join(' | ');if(item&&typeof item==='object'){if(node.type==='team-grid')return [item.name||'',item.role||'',item.image||'',item.url||'',item.bio||''].join(' | ');if(['blog-grid','product-grid','portfolio-grid','filterable-gallery','feature-bento'].includes(node.type))return [item.name||item.title||'',item.price||item.excerpt||item.description||item.text||'',item.image||item.src||'',item.url||'',item.category||''].join(' | ');if(node.type==='service-grid')return [item.icon||'✦',item.title||item.name||'',item.description||'',item.url||''].join(' | ');if(node.type==='logo-cloud')return [item.name||item.label||item||'',item.image||'',item.url||''].join(' | ');if(node.type==='event-list')return [item.date||'',item.title||'',item.description||'',item.location||'',item.url||''].join(' | ');if(node.type==='review-grid')return [item.quote||item.text||'',item.name||'',item.company||'',item.rating||5].join(' | ');if(node.type==='job-board')return [item.title||'',item.location||'',item.type||'',item.description||'',item.url||''].join(' | ');if(node.type==='testimonial-carousel')return [item.quote||item.text||'',item.name||'',item.role||''].join(' | ');if(node.type==='process-steps')return [item.title||item.name||'',item.description||item.text||''].join(' | ');if(node.type==='faq-list')return [item.question||item.title||'',item.answer||item.text||''].join(' | ');return [item.label||item.name||item.value||'',item.value||item.description||''].join(' | ')}return String(item??'')}).join('\n')}
  recordsField(node){const type=node.type;let hint='كل سطر عنصر جديد وافصل حقوله بعلامة |';if(type==='team-grid')hint='كل سطر: اسم العضو | الصفة | رابط الصورة | رابط الملف | نبذة قصيرة';else if(['blog-grid','product-grid','portfolio-grid','filterable-gallery','feature-bento'].includes(type))hint='كل سطر: الاسم/العنوان | الوصف/السعر | رابط الصورة | رابط الوجهة | الفئة';else if(type==='service-grid')hint='كل سطر: الأيقونة | عنوان الخدمة | الوصف | رابط الوجهة';else if(type==='logo-cloud')hint='كل سطر: اسم العلامة | رابط صورة الشعار (اختياري) | رابط العلامة';else if(type==='event-list')hint='كل سطر: التاريخ | عنوان الفعالية | الوصف | المكان | رابط التسجيل';else if(type==='review-grid')hint='كل سطر: نص التقييم | الاسم | الجهة | عدد النجوم';else if(type==='job-board')hint='كل سطر: عنوان الوظيفة | المكان | نوع الدوام | الوصف | رابط التقديم';else if(type==='testimonial-carousel')hint='كل سطر: نص الشهادة | الاسم | الصفة';else if(type==='process-steps')hint='كل سطر: عنوان الخطوة | الوصف';else if(type==='faq-list')hint='كل سطر: السؤال | الإجابة';else if(type==='trust-bar')hint='كل سطر: اسم الشريك أو العلامة';return `<div class="field"><label>العناصر (سطر لكل عنصر)</label><textarea data-key="items" data-type="records" rows="5" spellcheck="false">${esc(this.recordsText(node))}</textarea><small>${esc(hint)}</small></div>`}

  colorField(label,key,value,theme,device){
    const hex=parseGradientColor(value)||parseGradientColor(theme?.primary)||'#5B5CE2';const palette=colorPalette(theme);const swatches=palette.map((c,i)=>`<button type="button" class="color-swatch" title="${esc(c)}" data-color-value="${esc(c)}" style="background:${esc(c)}"></button>`).join('');
    const gradientAction=key==='background'?'<button type="button" class="secondary-btn" data-gradient-editor style="width:100%;height:30px;margin:5px 0 3px">◩ تدرج الألوان — لونان أو أكثر</button>':'';
    return `<div class="field color-field" data-color-key="${esc(key)}"><label>${esc(label)}</label><div class="color-control"><button type="button" class="color-preview" data-color-trigger data-color-key="${esc(key)}" title="اختيار لون" style="background:${esc(value||hex)}"><span></span></button><input type="color" data-color-native data-color-key="${esc(key)}" value="${hex}" aria-label="${esc(label)}"><input class="color-text" data-color-text data-color-key="${esc(key)}" value="${esc(value||'')}" placeholder="#5b5ce2 أو rgba(...)" spellcheck="false"><button type="button" class="color-action" data-color-transparent>شفاف</button><button type="button" class="color-action" data-color-eyedropper ${globalThis.EyeDropper?'':'disabled'}>◉</button><button type="button" class="color-action" data-color-mix>مزج</button></div><div class="color-swatches">${swatches}</div>${gradientAction}<small>اضغط مربع اللون للاختيار، أو اكتب HEX / RGB / RGBA. يمكن ضبط تدرج متعدد الألوان للخلفية.</small></div>`;
  }
  destinationField(node,props){const options=[`<option value="#" ${!props.url||props.url==='#'?'selected':''}>بدون وجهة</option>`,...this.store.project.pages.map(page=>`<option value="page:${page.id}" ${props.url===`page:${page.id}`?'selected':''}>صفحة: ${esc(page.name)}</option>`),`<option value="__external__" ${props.url&&/^https?:\/\//i.test(props.url)?'selected':''}>رابط خارجي</option>`].join('');const external=this.field('الرابط الخارجي','url',/^https?:\/\//i.test(props.url||'')?props.url:'');return `<div class="field"><label>الوجهة</label><select data-destination-for="${node.id}">${options}</select></div><div data-external-wrap="${node.id}" class="${props.url&&/^https?:\/\//i.test(props.url)?'':'hidden'}">${external}</div>`}
  semanticText(label,key,value){return `<div class="field"><label>${label}</label><input data-semantic-text="${key}" value="${esc(value)}"></div>`}
  semanticField(label,key,value,options){return `<div class="field"><label>${label}</label><select data-semantic-key="${key}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`}
  layoutControl(label,key,value,options){return `<div class="field"><label>${label}</label><select data-layout-key="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`}
  mediaField(node){
    const kind=mediaKindForNode(node); if(!['image','video','audio','document'].includes(kind)) return '';
    const current=findAsset(this.store.project,node.props?.assetId); const assets=this.store.project.assets.filter(a=>a.kind===kind); const preview=current?(current.kind==='image'?`<img src="${esc(current.data)}" alt="${esc(current.alt||current.name)}">`:`<span class="asset-current-icon">${esc(current.kind.toUpperCase())}</span>`):'<span class="asset-current-icon">＋</span>';
    return `<section class="media-binding" data-media-kind="${kind}"><div class="media-binding-head"><div><b>وسيط العنصر</b><small>${current?`مرتبط بـ ${esc(current.name)} • ${esc(current.originalName)}`:'لم يتم اختيار ملف بعد'}</small></div><span class="asset-current-preview">${preview}</span></div><div class="media-binding-actions"><select data-media-select><option value="">${current?'تغيير الوسيط…':'اختر من الموقع…'}</option>${assets.map(a=>`<option value="${esc(a.id)}" ${current?.id===a.id?'selected':''}>${esc(a.name)} — ${esc(a.originalName)}</option>`).join('')}</select><button type="button" class="secondary-btn" data-media-upload>رفع من الجهاز</button><button type="button" class="secondary-btn" data-open-assets>المكتبة</button></div><small class="media-help">عند الرفع يُحفظ الملف داخل المشروع ويأخذ اسمًا تلقائيًا مثل <b>${kind==='image'?'img1':kind==='video'?'video1':kind==='audio'?'audio1':'file1'}</b>.</small></section>`;
  }
  render(){
    if(!this.el)return;const id=this.store.ui.selected,hit=id?findNodeGlobal(this.store.project,id):null;if(!hit){this.el.classList.add('hidden');document.getElementById('inspectorEmpty').classList.remove('hidden');return}document.getElementById('inspectorEmpty').classList.add('hidden');this.el.classList.remove('hidden');
    const n=hit.node,p=n.props||{},s={...(n.style||{}),...(n.responsive?.[this.device]||{})},layout=n.layout||{};let content='';
    if(['heading','text','quote','badge','alert','button','link','marquee','gradient','glass'].includes(n.type))content+=this.field('النص','text',p.text||'');
    if(['button','link'].includes(n.type))content+=this.destinationField(n,p);
    if(n.type==='image')content+=this.mediaField(n)+this.field('الوصف البديل','alt',p.alt||'');
    if(n.type==='image')content+=`<div class="field"><label>ملاءمة الصورة</label><select data-key="objectFit"><option value="cover" ${((p.objectFit||'cover')==='cover')?'selected':''}>تغطية الإطار — Cover</option><option value="contain" ${p.objectFit==='contain'?'selected':''}>عرض الصورة كاملة — Contain</option><option value="fill" ${p.objectFit==='fill'?'selected':''}>ملء الإطار — Fill</option><option value="none" ${p.objectFit==='none'?'selected':''}>الحجم الأصلي — None</option></select></div>`;
    if(['video','audio','file','download'].includes(n.type))content+=this.mediaField(n);
    if(n.type==='card')content+=this.field('العنوان','title',p.title||'')+this.field('الوصف','text',p.text||'')+this.field('نص الزر','button',p.button||'')+this.destinationField(n,p);
    if(n.type==='product')content+=this.field('الاسم','name',p.name||'')+this.field('السعر','price',p.price||'')+this.field('العملة','currency',p.currency||'')+this.destinationField(n,p);
    if(['input','textarea','select','search','file'].includes(n.type))content+=this.field('عنوان الحقل','label',p.label||'')+this.field('النص المساعد','placeholder',p.placeholder||'');
    if(n.type==='faq')content+=this.field('السؤال','question',p.question||'')+this.field('الإجابة','answer',p.answer||'');
    if(n.type==='navbar')content+=this.field('العلامة','brand',p.brand||'');
    if(['hero-split','blog-grid','product-grid','portfolio-grid','filterable-gallery','testimonial-carousel','contact-form','process-steps','trust-bar','faq-list','team-grid','service-grid','feature-bento','logo-cloud','event-list','review-grid','job-board'].includes(n.type)){
      if(['hero-split','contact-form','blog-grid','faq-list','team-grid','service-grid','feature-bento','logo-cloud','event-list','review-grid','job-board'].includes(n.type))content+=this.field('العنوان','title',p.title||'');
      if(['hero-split','contact-form'].includes(n.type))content+=this.field('الوصف','text',p.text||'');
      if(n.type==='hero-split')content+=this.field('النص الصغير','eyebrow',p.eyebrow||'')+this.field('رابط الزر','url',p.url||'#')+this.field('نص الزر','button',p.button||'')+this.field('الصورة','image',p.image||'');
      if(n.type==='contact-form')content+=this.field('نص الإرسال','button',p.button||'إرسال');
      if(n.type==='product-grid')content+=this.field('نص زر السلة','cartLabel',p.cartLabel||'أضف للسلة');
      if(n.type==='trust-bar')content+=this.field('التقييم','rating',p.rating||'');
      content+=this.recordsField(n);
    }
    if(n.type==='collection-list'){const opts=[`<option value="">اختر مجموعة…</option>`,...(this.store.project.cms?.collections||[]).map(c=>`<option value="${esc(c.id)}" ${p.collectionId===c.id?'selected':''}>${esc(c.name)}</option>`)].join('');content+=`<div class="field"><label>مجموعة CMS</label><select data-cms-collection="${n.id}">${opts}</select></div>`+this.field('عدد العناصر','limit',p.limit??6,'number')}
    const variables=listVariables(this.store.project);
    const boundTypes=new Set(['heading','text','button','link','image','card','product']);
    if(boundTypes.has(n.type)){content+=`<div class="field"><label>ربط محتوى بمتغير</label><select data-variable-bind><option value="">بدون</option>${variables.map(v=>`<option value="${esc(v.key)}" ${p.bindingVariable===v.key?'selected':''}>${esc(v.name)}</option>`).join('')}</select></div>`}
    if(n.type==='symbol-instance')content+=`<div class="tips-card"><b>مكون مشترك</b><p>تستخدم هذه النسخة تعريفًا مشتركًا. عدّل الأصل لتطبيق التغييرات على كل النسخ.</p></div>`;
    const classOptions=Object.keys(this.store.project.styleLibrary?.classes||{});const textStyleOptions=Object.keys(this.store.project.styleLibrary?.textStyles||{});const libraryPanel=`<div class="field-row"><div class="field"><label>Text Style</label><select data-style-library-text><option value="">بدون</option>${textStyleOptions.map(name=>`<option value="${esc(name)}" ${p.textStyle===name?'selected':''}>${esc(name)}</option>`).join('')}</select></div><div class="field"><label>Effect / State</label><select data-style-library-effect><option value="">بدون</option>${Object.keys(this.store.project.styleLibrary?.effects||{}).map(name=>`<option value="${esc(name)}" ${p.effect===name?'selected':''}>${esc(name)}</option>`).join('')}</select></div></div><div class="class-chips">${classOptions.length?classOptions.map(name=>`<button type="button" data-class-toggle="${esc(name)}" class="${(n.classes||[]).includes(name)?'active':''}">.${esc(name)}</button>`).join(''):'<small>أنشئ Classes من Design System لإعادة استخدامها.</small>'}</div>`;const semantic=`<div class="field-row">${this.semanticField('وسم HTML','tag',n.semantic?.tag||'div',[['div','div'],['section','section'],['header','header'],['main','main'],['nav','nav'],['article','article'],['aside','aside'],['footer','footer'],['button','button']])}${this.semanticField('الدور ARIA','role',n.semantic?.role||'', [['','افتراضي'],['banner','banner'],['navigation','navigation'],['main','main'],['contentinfo','contentinfo'],['article','article'],['region','region']])}</div>${this.semanticText('اسم ARIA','ariaLabel',n.semantic?.ariaLabel||'')}<div class="field"><label>Classes</label><input data-class-list value="${esc((n.classes||[]).join(', '))}"><small>افصل بين أسماء الكلاسات بفاصلة.</small></div>${libraryPanel}`;
    if(!content)content=this.field('اسم وصفي','label',p.label||'');
    const style=this.colorField('لون النص','color',s.color||'',this.store.project.theme,this.device)+this.colorField('الخلفية','background',s.background||'',this.store.project.theme,this.device)+`<div class="field-row">${this.field('حجم النص','fontSize',s.fontSize??'','number')}${this.field('الاستدارة','radius',s.radius??'','number')}</div><div class="field-row">${this.field('هامش أعلى','marginTop',s.marginTop??0,'number')}${this.field('هامش أسفل','marginBottom',s.marginBottom??14,'number')}</div>`;
    const structure=`<div class="field-row">${this.layoutControl('العرض', 'display', layout.display||'block', [['block','Block'],['flex','Flex'],['grid','Grid']])}${this.layoutControl('اتجاه', 'direction', layout.direction||'column', [['column','عمودي'],['row','أفقي']])}</div><div class="field-row">${this.layoutControl('المحاذاة','align',layout.align||'stretch',[['stretch','Stretch'],['start','Start'],['center','Center'],['end','End']])}${this.layoutControl('التوزيع','justify',layout.justify||'start',[['start','Start'],['center','Center'],['between','Between'],['end','End']])}</div><div class="field-row">${this.field('الفجوة','gap',s.gap??layout.gap??0,'number')}${this.layoutControl('التفاف','wrap',layout.wrap?'1':'0',[['0','لا'],['1','نعم']])}</div>`;
    const visibility=`<div class="visibility-grid">${DEVICES.map(d=>`<label><input type="checkbox" data-visibility-device="${d}" ${n.visibility?.[d]!==false?'checked':''}>${d}</label>`).join('')}</div>`;
    const createdLabel=n.device?.created?deviceLabel(n.device.created):'قبل تحديد الجهاز';
    this.el.innerHTML=`<div class="device-context"><b>المعاينة الآن: ${esc(deviceLabel(this.device))}</b><small>تمت تهيئة العنصر عند إنشائه على: ${esc(createdLabel)} • يمكنك تخصيص كل جهاز بشكل مستقل.</small></div><section class="inspector-section"><header><b>المحتوى</b><span>${n.type}</span></header><div class="inspector-body">${content}</div></section><section class="inspector-section"><header><b>المظهر</b><span>${this.device}</span></header><div class="inspector-body">${style}</div></section><section class="inspector-section"><header><b>البنية</b><span>Layout</span></header><div class="inspector-body">${structure}</div></section><section class="inspector-section"><header><b>Responsive</b><span>إظهار العنصر</span></header><div class="inspector-body">${visibility}<div class="segmented">${DEVICES.map(d=>`<button data-device="${d}" class="${d===this.device?'active':''}">${d}</button>`).join('')}</div><label class="sync-row"><span>مزامنة نسبية</span><input id="propagate" type="checkbox" ${this.store.project.settings.propagateDevices?'checked':''}></label></div></section><button id="toggleAdvanced" class="advanced-toggle">${this.advanced?'إخفاء التخصيص المتقدم':'التخصيص المتقدم'}</button>${this.advanced?`<section class="inspector-section"><div class="inspector-body">${this.field('العرض','width',s.width??'')}${this.field('الحد الأقصى','maxWidth',s.maxWidth??'')}${this.field('الارتفاع','height',s.height??'','number')}${this.field('الارتفاع الأدنى','minHeight',s.minHeight??'','number')}${this.field('العتامة','opacity',s.opacity??1,'number')}</div></section>`:''}${this.store.ui.mode==='trainee'?'<button id="codeBtn" class="advanced-toggle">&lt;/&gt; كود العنصر</button>':''}`;
    this.wire(n.id);
  }
  openGradientEditor(fieldKey,wrap){
    if(fieldKey!=='background')return;
    const current=wrap.querySelector('[data-color-text]')?.value||'';
    const settings=parseGradientValue(current,this.store.project.theme);
    let stops=settings.stops.map(stop=>({...stop})),type=settings.type,angle=settings.angle;
    const body=`<div class="gradient-editor" style="display:grid;gap:12px">
      <div data-gradient-live style="height:96px;border:1px solid #e2e5ee;border-radius:12px;background:linear-gradient(135deg,#5b5ce2,#20a06a)"></div>
      <div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px;align-items:end">
        <label class="field"><span>نوع التدرج</span><select id="gradientType"><option value="linear">خطي — Linear</option><option value="radial">دائري — Radial</option></select></label>
        <label class="field" id="gradientAngleWrap"><span>زاوية التدرج <output id="gradientAngleOut">135°</output></span><input id="gradientAngle" type="range" min="0" max="360" value="135" style="width:100%"></label>
      </div>
      <div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><b>نقاط الألوان <small id="gradientStopCount" style="font-weight:400;color:#7b8293">(2–8 ألوان)</small></b><div style="display:flex;gap:6px"><button type="button" class="secondary-btn" id="gradientReverse">عكس الاتجاه</button><button type="button" class="primary-btn" id="gradientAddStop">＋ لون</button></div></div>
      <div id="gradientStops" style="display:grid;gap:8px"></div>
      <div style="display:grid;gap:5px"><small style="color:#737b8e">CSS الناتج — يُحفظ مع المشروع ويظهر في المعاينة والتصدير</small><code id="gradientCss" style="display:block;padding:9px;background:#f5f6fa;border:1px solid #e5e8f0;border-radius:8px;white-space:normal;overflow-wrap:anywhere;font-size:11px"></code></div>
    </div>`;
    let modal;
    const apply=()=>{const value=gradientValue(type,angle,stops);const input=wrap.querySelector('[data-color-text]');if(input){input.value=value;input.dispatchEvent(new Event('change',{bubbles:true}))}modal?.remove()};
    modal=showModal(document.getElementById('modalHost'),{title:'تدرج الألوان',body,wide:false,actions:[{label:'إلغاء'},{label:'تطبيق التدرج',kind:'primary',onClick:apply}]});
    const typeInput=modal.querySelector('#gradientType'),angleInput=modal.querySelector('#gradientAngle'),angleOut=modal.querySelector('#gradientAngleOut'),angleWrap=modal.querySelector('#gradientAngleWrap'),stopHost=modal.querySelector('#gradientStops'),preview=modal.querySelector('[data-gradient-live]'),cssOut=modal.querySelector('#gradientCss'),countOut=modal.querySelector('#gradientStopCount'),addButton=modal.querySelector('#gradientAddStop');
    typeInput.value=type;angleInput.value=String(angle);
    const update=()=>{const value=gradientValue(type,angle,stops);preview.style.background=value;cssOut.textContent=value;angleOut.textContent=`${angle}°`;angleWrap.hidden=type==='radial';countOut.textContent=`(${stops.length}/8 ألوان)`;addButton.disabled=stops.length>=8;};
    const renderStops=()=>{stopHost.innerHTML=stops.map((stop,index)=>`<div data-gradient-stop="${index}" style="display:grid;grid-template-columns:36px minmax(0,1fr) 64px 30px;gap:8px;align-items:center;border:1px solid #e3e6ef;border-radius:9px;padding:8px"><input type="color" data-stop-color="${index}" value="${parseGradientColor(stop.color)||'#5B5CE2'}" aria-label="لون التوقف ${index+1}" style="width:32px;height:30px;border:0;background:transparent;padding:0"><div style="min-width:0"><b style="font-size:11px;display:block;margin-bottom:3px">اللون ${index+1}</b><input type="range" data-stop-position="${index}" min="0" max="100" value="${Math.round(stop.position)}" aria-label="موضع اللون ${index+1}" style="width:100%"></div><output data-stop-output="${index}" style="font-size:11px;text-align:center">${Math.round(stop.position)}%</output><button type="button" data-remove-stop="${index}" ${stops.length<=2?'disabled':''} title="حذف اللون" aria-label="حذف اللون ${index+1}" style="height:29px;border:1px solid #e5e8ef;border-radius:7px;background:#fff;color:#a33">−</button></div>`).join('');
      stopHost.querySelectorAll('[data-stop-color]').forEach(input=>input.addEventListener('input',()=>{const index=Number(input.dataset.stopColor);if(stops[index])stops[index].color=input.value.toUpperCase();update()}));
      stopHost.querySelectorAll('[data-stop-position]').forEach(input=>input.addEventListener('input',()=>{const index=Number(input.dataset.stopPosition);if(stops[index])stops[index].position=Number(input.value);const output=stopHost.querySelector(`[data-stop-output="${index}"]`);if(output)output.textContent=`${input.value}%`;update()}));
      stopHost.querySelectorAll('[data-remove-stop]').forEach(button=>button.addEventListener('click',()=>{if(stops.length<=2)return;stops.splice(Number(button.dataset.removeStop),1);renderStops();update()}));
      update();
    };
    angleInput.addEventListener('input',()=>{angle=Number(angleInput.value);update()});
    typeInput.addEventListener('change',()=>{type=typeInput.value==='radial'?'radial':'linear';update()});
    addButton.addEventListener('click',()=>{if(stops.length>=8)return;const ordered=[...stops].sort((a,b)=>a.position-b.position);const points=[{position:0,color:ordered[0].color},...ordered,{position:100,color:ordered[ordered.length-1].color}];let best=null;for(let i=0;i<points.length-1;i++){const gap=points[i+1].position-points[i].position;if(gap>0&&(!best||gap>best.gap))best={left:points[i],right:points[i+1],gap}}if(!best)return;const position=Math.round((best.left.position+best.right.position)/2);const color=mixColors(best.left.color,best.right.color,.5)||'#8B5CF6';stops.push({color,position});stops.sort((a,b)=>a.position-b.position);renderStops()});
    modal.querySelector('#gradientReverse').addEventListener('click',()=>{stops=stops.map(stop=>({...stop,position:100-stop.position})).sort((a,b)=>a.position-b.position);angle=(angle+180)%360;angleInput.value=String(angle);renderStops()});
    renderStops();
  }
  openColorMixer(fieldKey,wrap){
    const base=wrap.querySelector('[data-color-text]')?.value||'#5B5CE2';
    const body=colorMixerHtml(); const modal=showModal(document.getElementById('modalHost'),{title:'مزج الألوان',body,wide:true,actions:[{label:'إلغاء'},{label:'تطبيق النتيجة',kind:'primary',onClick:()=>{const color=modal.querySelector('#mixHex')?.textContent?.trim();if(color) {const input=wrap.querySelector('[data-color-text]');if(input){input.value=color;input.dispatchEvent(new Event('change',{bubbles:true}))}}modal.remove()}}]});
    const a=modal.querySelector('#mixA'),b=modal.querySelector('#mixB'),at=modal.querySelector('#mixAText'),bt=modal.querySelector('#mixBText'),ratio=modal.querySelector('#mixRatio'),space=modal.querySelector('#mixSpace');a.value=/^#[0-9a-f]{6}$/i.test(base)?base:'#5B5CE2';at.value=a.value;
    const update=()=>{const c=mixColors(at.value,bt.value,Number(ratio.value)/100,space.value)||'#000000';modal.querySelector('[data-mix-result]').style.background=c;modal.querySelector('#mixHex').textContent=c;modal.querySelector('#mixRatioOut').textContent=`${ratio.value}%`;const cr=contrastRatio(c,'#FFFFFF');modal.querySelector('#mixContrast').textContent=`${cr.toFixed(2)}:1`;const grad=gradientColors([{color:at.value,position:0},{color:bt.value,position:100}],90);modal.querySelector('[data-gradient-preview]').style.background=grad;modal.querySelector('[data-gradient-value]').textContent=grad};
    modal.querySelector('[data-apply-gradient]')?.addEventListener('click',()=>{const grad=modal.querySelector('[data-gradient-value]')?.textContent||'';if(fieldKey==='background'&&grad){const input=wrap.querySelector('[data-color-text]');if(input){input.value=grad;input.dispatchEvent(new Event('change',{bubbles:true}))}modal.remove()}});
    modal.querySelector('[data-save-mix]')?.addEventListener('click',()=>{const color=modal.querySelector('#mixHex')?.textContent?.trim();if(!color)return;this.store.transact('حفظ لون ممزوج',project=>{project.theme.tokens=project.theme.tokens||{};project.theme.tokens.colors={...(project.theme.tokens.colors||{})};let n=1;while(project.theme.tokens.colors[`mix${n}`]&&n<999)n++;project.theme.tokens.colors[`mix${n}`]=color});this.render();modal.remove()});
    a.oninput=()=>{at.value=a.value.toUpperCase();update()};b.oninput=()=>{bt.value=b.value.toUpperCase();update()};at.onchange=()=>{const v=/^#[0-9a-f]{6}$/i.test(at.value)?at.value:'#5B5CE2';at.value=v.toUpperCase();a.value=v;update()};bt.onchange=()=>{const v=/^#[0-9a-f]{6}$/i.test(bt.value)?bt.value:'#20A06A';bt.value=v.toUpperCase();b.value=v;update()};ratio.oninput=update;space.onchange=update;modal.querySelector('#mixCopy')?.addEventListener('click',()=>navigator.clipboard?.writeText(modal.querySelector('#mixHex').textContent||''));update();
  }

  wire(id){
    for(const input of this.el.querySelectorAll('[data-key]'))input.addEventListener('change',()=>{const key=input.dataset.key,type=input.dataset.type;let value=input.value;if(type==='number')value=value===''?0:Number(value);if(type==='records'){const node=this.store.find(id)?.node;const typeName=node?.type||'';const lines=String(value||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const parse=line=>line.split('|').map(part=>part.trim());if(['blog-grid','product-grid','portfolio-grid','filterable-gallery','team-grid','feature-bento'].includes(typeName)){value=lines.map((line,index)=>{const [name,detail,image,url,category]=parse(line);if(typeName==='product-grid')return {id:`product-${index+1}`,name:name||`منتج ${index+1}`,price:detail||'',description:'',image:image||'',url:url||'#',category:category||'',cta:'التفاصيل'};if(typeName==='team-grid')return {name:name||`عضو ${index+1}`,role:detail||'',image:image||'',url:url||'#',bio:category||''};return {title:name||`عنصر ${index+1}`,...(typeName==='blog-grid'?{excerpt:detail||''}:{description:detail||''}),image:image||'',url:url||'#',category:category||''}})}else if(typeName==='testimonial-carousel')value=lines.map(line=>{const [quote,name,role]=parse(line);return {quote:quote||'',name:name||'',role:role||''}});else if(typeName==='process-steps')value=lines.map(line=>{const [title,description]=parse(line);return {title:title||'',description:description||''}});else if(typeName==='faq-list')value=lines.map(line=>{const [question,answer]=parse(line);return {question:question||'',answer:answer||''}});else if(typeName==='trust-bar')value=lines.map(line=>line.split('|')[0].trim());updateProps(this.store,id,{items:value});return}if(STYLE_KEYS.has(key)){updateStyle(this.store,id,{[key]:value},this.device);if(this.store.project.settings.propagateDevices)propagateStyle(findNodeGlobal(this.store.project,id)?.node,this.device,{[key]:value})}else updateProps(this.store,id,{[key]:value})});
    this.el.querySelector('[data-class-list]')?.addEventListener('change',event=>{const classes=[...new Set(String(event.target.value||'').split(',').map(x=>x.trim()).filter(Boolean))];updateProps(this.store,id,{classes})});
    this.el.querySelectorAll('[data-class-toggle]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.classToggle;this.store.transact('تبديل Class',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;const classes=new Set(hit.node.classes||[]);classes.has(name)?classes.delete(name):classes.add(name);hit.node.classes=[...classes]})}));
    this.el.querySelector('[data-style-library-text]')?.addEventListener('change',event=>updateProps(this.store,id,{textStyle:event.target.value}));
    this.el.querySelector('[data-style-library-effect]')?.addEventListener('change',event=>updateProps(this.store,id,{effect:event.target.value}));
    this.el.querySelectorAll('[data-semantic-text]').forEach(input=>input.addEventListener('change',()=>{const key=input.dataset.semanticText;this.store.transact('تعديل الدلالة والوصول',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;hit.node.semantic={tag:'div',role:'',ariaLabel:'',...(hit.node.semantic||{}),[key]:input.value}})}));
    this.el.querySelectorAll('[data-semantic-key]').forEach(select=>select.addEventListener('change',()=>{const key=select.dataset.semanticKey;this.store.transact('تعديل الدلالة والوصول',project=>{const hit=findNodeGlobal(project,id);if(!hit)return;hit.node.semantic={tag:'div',role:'',ariaLabel:'',...(hit.node.semantic||{}),[key]:select.value}})}));
    this.el.querySelector('[data-variable-bind]')?.addEventListener('change',event=>updateProps(this.store,id,{bindingVariable:event.target.value}));    this.el.querySelector('[data-media-select]')?.addEventListener('change',event=>{const assetId=event.target.value;if(assetId&&this.el.__assetService)this.el.__assetService.assignToNode(id,assetId)});
    this.el.querySelector('[data-media-upload]')?.addEventListener('click',()=>{const input=document.createElement('input');input.type='file';input.accept=mediaAccept(mediaKindForNode(n));input.multiple=false;input.onchange=async()=>{const file=input.files?.[0];if(!file||!this.el.__assetService)return;const asset=await this.el.__assetService.addFile(file,{purpose:mediaKindForNode(n),attachTo:id,alt:file.name.replace(/\.[^.]+$/,'')});if(asset){this.render();this.store.setUI({selected:id})}};input.click()});
    this.el.querySelector('[data-open-assets]')?.addEventListener('click',()=>document.getElementById('openAssetsBtn')?.click());

    this.el.querySelectorAll('[data-cms-collection]').forEach(select=>select.addEventListener('change',()=>updateProps(this.store,id,{collectionId:select.value})));
    this.el.querySelectorAll('[data-destination-for]').forEach(select=>select.addEventListener('change',()=>{const value=select.value;if(value==='__external__'){const current=this.store.find(id)?.node?.props?.url||'';updateProps(this.store,id,{url:/^https?:\/\//i.test(current)?current:'https://'});this.el.querySelector(`[data-external-wrap="${id}"]`)?.classList.remove('hidden')}else{updateProps(this.store,id,{url:value});this.el.querySelector(`[data-external-wrap="${id}"]`)?.classList.add('hidden')}}));

    const applyColor=(key,value)=>{updateStyle(this.store,id,{[key]:value},this.device);if(this.store.project.settings.propagateDevices)propagateStyle(findNodeGlobal(this.store.project,id)?.node,this.device,{[key]:value});};
    this.el.querySelectorAll('.color-field').forEach(wrap=>{
      const text=wrap.querySelector('[data-color-text]'),native=wrap.querySelector('[data-color-native]'),preview=wrap.querySelector('[data-color-trigger]');
      const fieldKey=wrap.dataset.colorKey||text?.dataset?.colorKey||native?.dataset?.colorKey||preview?.dataset?.colorKey||'color';
      const sync=value=>{if(text)text.value=value;const validSolid=/^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(String(value||'').trim())||/^rgba?\(/i.test(String(value||'').trim());if(native&&validSolid)native.value=nativeHex(value);if(preview)preview.style.background=value||nativeHex(value)};
      native?.addEventListener('input',e=>{sync(e.target.value);applyColor(fieldKey,e.target.value)});
      text?.addEventListener('change',e=>{const value=String(e.target.value||'').trim();sync(value);applyColor(fieldKey,value)});
      preview?.addEventListener('click',()=>native?.click());
      wrap.querySelector('[data-color-transparent]')?.addEventListener('click',()=>{sync('transparent');applyColor(fieldKey,'transparent')});
      wrap.querySelectorAll('[data-color-value]').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.colorValue;sync(value);applyColor(fieldKey,value)}));
      wrap.querySelector('[data-color-eyedropper]')?.addEventListener('click',async()=>{if(!globalThis.EyeDropper)return;try{const result=await new EyeDropper().open();if(result?.sRGBHex){sync(result.sRGBHex);applyColor(fieldKey,result.sRGBHex)}}catch{}});
      wrap.querySelector('[data-color-mix]')?.addEventListener('click',()=>this.openColorMixer(fieldKey,wrap));
      wrap.querySelector('[data-gradient-editor]')?.addEventListener('click',()=>this.openGradientEditor(fieldKey,wrap));

    });
    this.el.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>this.setDevice(b.dataset.device));
    this.el.querySelectorAll('[data-layout-key]').forEach(select=>select.addEventListener('change',()=>{const key=select.dataset.layoutKey;const value=key==='wrap'?select.value==='1':select.value;this.store.transact('تعديل بنية العنصر',p=>{const hit=findNodeGlobal(p,id);if(hit)hit.node.layout={...(hit.node.layout||{}),[key]:value}})}));
    this.el.querySelectorAll('[data-visibility-device]').forEach(input=>input.addEventListener('change',()=>this.store.transact('تعديل الظهور responsive',p=>{const hit=findNodeGlobal(p,id);if(hit)hit.node.visibility={...(hit.node.visibility||{}),[input.dataset.visibilityDevice]:input.checked}})));
    this.el.querySelector('#propagate')?.addEventListener('change',e=>this.store.transact('إعداد مزامنة',p=>p.settings.propagateDevices=e.target.checked));this.el.querySelector('#toggleAdvanced')?.addEventListener('click',()=>{this.advanced=!this.advanced;this.render()});
    this.el.querySelector('#codeBtn')?.addEventListener('click',()=>{const hit=this.store.find(id);if(hit)showModal(document.getElementById('modalHost'),{title:'كود العنصر',body:`<div class="field"><textarea readonly style="height:260px">${esc(nodeHtml(hit.node,this.store.project.theme,this.store.project,this.device))}</textarea></div>`})});
  }
}
exports.Inspector = Inspector;
});
