const {renderPage} = __require("src/engine/renderer.js");
const {createRuntime} = __require("src/engine/interaction.js");
const {addNode,insertNodeAtDrop,moveNodeByDrop,moveNodeToEnd,groupNodes,updateStyle} = __require("src/core/commands.js");
const {clamp} = __require("src/core/utils.js");
const {pageFromAnchor} = __require("src/engine/routing.js");
const {showModal} = __require("src/ui/modal.js");
const CONTAINER_TYPES=new Set(['section','container','grid','columns','stack','spaced','hero','card','form','group','navbar','footer']);
const SIZE_HANDLES=[['e','e'],['s','s'],['se','se']];
class WorkspaceEngine{
 constructor(store,inspector,panels){this.store=store;this.inspector=inspector;this.panels=panels;this.runtimeCleanup=null;this.runtimeKey='';this.wired=false;this.space=false;this.gesture=null;this.selectedIds=new Set();this.selectionPageId=null;this.ignoreClickUntil=0;this.marqueeEl=null;this.internalSelectionUpdate=false;this.lastStoreSelection=null;this.onPointerMove=e=>this.moveGesture(e);this.onPointerUp=e=>this.endGesture(e);this.onPointerCancel=e=>this.cancelGesture(e)}
 mount(){this.pageCanvas=document.getElementById('pageCanvas');this.deviceFrame=document.getElementById('deviceFrame');this.viewport=document.getElementById('canvasViewport');this.stage=document.getElementById('canvasStage');this.host=document.getElementById('canvasStageHost');this.wireCanvas();this.wireControls();this.resizeObserver=globalThis.ResizeObserver?new ResizeObserver(()=>{this.reflowHost();this.centerStage()}):null;this.resizeObserver?.observe(this.viewport)}
 wireCanvas(){if(this.wired)return;this.wired=true;
  this.pageCanvas.addEventListener('pointerdown',e=>this.startGesture(e));
  window.addEventListener('pointermove',this.onPointerMove,{passive:false});window.addEventListener('pointerup',this.onPointerUp);window.addEventListener('pointercancel',this.onPointerCancel);
  this.pageCanvas.addEventListener('click',e=>{if(Date.now()<this.ignoreClickUntil){e.preventDefault();return}const link=e.target.closest('a');const w=e.target.closest('.node-wrap');if(this.store.ui.interactionMode){if(w){const sourceId=w.dataset.nodeId;const ownsClick=this.store.project.interactions?.some(i=>i.sourceId===sourceId&&i.enabled!==false&&i.trigger==='click');if(ownsClick){if(link)e.preventDefault();return}}if(link){const target=link.dataset.pageTarget||pageFromAnchor(link.getAttribute('href'),this.store.project)?.id;if(target){e.preventDefault();this.store.setActivePage(target);this.store.setUI({leftTab:'elements'});return}}return}if(!w){if(!(e.shiftKey||e.ctrlKey||e.metaKey)){this.selectedIds.clear();this.store.setUI({selected:null})}return}e.preventDefault();const id=w.dataset.nodeId;if(e.shiftKey||e.ctrlKey||e.metaKey){if(this.selectedIds.has(id))this.selectedIds.delete(id);else this.selectedIds.add(id);const primary=[...this.selectedIds].at(-1)||null;this.setSelectionUI({selected:primary,rightOpen:true})}else{this.selectedIds=new Set([id]);this.setSelectionUI({selected:id,rightOpen:true})}this.syncSelectionUI()});
  this.pageCanvas.addEventListener('dragover',e=>e.preventDefault());this.pageCanvas.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer?.getData('application/bunaa-type');if(!type)return;insertNodeAtDrop(this.store,type,e.target.closest('.node-wrap')?.dataset.nodeId||null);this.selectedIds=new Set(this.store.ui.selected?[this.store.ui.selected]:[]);this.panels.setTab('layers')});
  document.getElementById('dropFooter')?.addEventListener('drop',e=>{e.preventDefault();const type=e.dataTransfer?.getData('application/bunaa-type');if(type)this.addElement(type)});
 }
 wireControls(){document.getElementById('zoomIn')?.addEventListener('click',()=>this.setZoom(this.store.ui.zoom+.1));document.getElementById('zoomOut')?.addEventListener('click',()=>this.setZoom(this.store.ui.zoom-.1));document.getElementById('zoomFit')?.addEventListener('click',()=>this.fit());document.getElementById('gridBtn')?.addEventListener('click',()=>this.store.setUI({grid:!this.store.ui.grid}));document.getElementById('structureBtn')?.addEventListener('click',()=>this.panels.setTab('layers'));document.getElementById('focusBtn')?.addEventListener('click',()=>this.store.setUI({focus:!this.store.ui.focus}));document.getElementById('groupSelectionBtn')?.addEventListener('click',()=>this.chooseGroupLayout());this.setupPan()}
 setupPan(){let pan=null;const stop=()=>{pan=null;this.viewport.style.cursor=''};this.viewport.addEventListener('pointerdown',e=>{const allow=e.button===1||(e.button===0&&this.space);if(!allow||!e.target.closest('#canvasStage')||e.target.closest('.node-resize-handle'))return;pan={x:e.clientX,y:e.clientY,sx:this.viewport.scrollLeft,sy:this.viewport.scrollTop};try{this.viewport.setPointerCapture(e.pointerId)}catch{}this.viewport.style.cursor='grabbing';e.preventDefault()});this.viewport.addEventListener('pointermove',e=>{if(!pan)return;this.viewport.scrollLeft=pan.sx-(e.clientX-pan.x);this.viewport.scrollTop=pan.sy-(e.clientY-pan.y)});this.viewport.addEventListener('pointerup',stop);this.viewport.addEventListener('pointercancel',stop);window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!e.target.matches('input,textarea,select,[contenteditable="true"]'))this.space=true});window.addEventListener('keyup',e=>{if(e.code==='Space')this.space=false});window.addEventListener('blur',()=>{this.space=false;stop()});this.viewport.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();this.setZoom(this.store.ui.zoom+(e.deltaY<0?.08:-.08))},{passive:false});window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='PageDown')this.viewport.scrollBy({top:Math.max(240,this.viewport.clientHeight*.8),behavior:'smooth'});else if(e.key==='PageUp')this.viewport.scrollBy({top:-Math.max(240,this.viewport.clientHeight*.8),behavior:'smooth'});else if(e.key==='Home'&&this.store.ui.focus)this.viewport.scrollTo({top:0,behavior:'smooth'});else if(e.key==='End'&&this.store.ui.focus)this.viewport.scrollTo({top:this.viewport.scrollHeight,behavior:'smooth'});})}
 setSelectionUI(patch){this.internalSelectionUpdate=true;try{this.store.setUI(patch);this.lastStoreSelection=this.store.ui.selected}finally{this.internalSelectionUpdate=false}}
 setZoom(z){this.store.setUI({zoom:clamp(Number(z)||1,.2,1.5)})}
 setDevice(device){if(!['desktop','tablet','mobile'].includes(device))return;this.store.setUI({device,zoom:1});this.inspector?.setDevice?.(device);requestAnimationFrame(()=>this.fit())}
 deviceWidth(){return this.store.project.devices[this.store.ui.device]?.width||1180}
 fit(){const base=this.deviceWidth(),available=Math.max(260,this.viewport.clientWidth-96);this.setZoom(clamp(available/base,.2,1.2));requestAnimationFrame(()=>{this.centerStage();this.viewport.scrollTop=0})}
 centerStage(){if(!this.viewport)return;const maxX=Math.max(0,this.viewport.scrollWidth-this.viewport.clientWidth);this.viewport.scrollLeft=Math.round(maxX/2)}
 addElement(type){const node=addNode(this.store,type);this.selectedIds=new Set(node?.id?[node.id]:[]);this.panels.setTab('layers')}
 toast(message){globalThis.__BUNAA_APP?.toast?.(message)}
 startGesture(e){if(this.store.ui.interactionMode||this.space||e.button!==0)return;const handle=e.target.closest('.node-resize-handle');if(handle){const wrap=handle.closest('.node-wrap');if(!wrap||wrap.dataset.locked==='1')return;e.preventDefault();e.stopPropagation();const z=this.store.ui.zoom||1;this.gesture={kind:'resize',pointerId:e.pointerId,id:wrap.dataset.nodeId,wrap,dir:handle.dataset.dir,startX:e.clientX,startY:e.clientY,startW:wrap.offsetWidth,startH:wrap.offsetHeight,z,width:wrap.offsetWidth,height:wrap.offsetHeight,moved:false};try{handle.setPointerCapture(e.pointerId)}catch{}return}const nodeWrap=e.target.closest('.node-wrap');if(nodeWrap){if(nodeWrap.dataset.locked==='1'||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;this.gesture={kind:'pending-node',pointerId:e.pointerId,id:nodeWrap.dataset.nodeId,wrap:nodeWrap,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,originalTransform:nodeWrap.style.transform};try{e.target.setPointerCapture(e.pointerId)}catch{}if(!e.target.closest('a,button'))e.preventDefault();return}if(e.target.closest('button,input,textarea,select,a'))return;this.gesture={kind:'pending-marquee',pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};try{this.pageCanvas.setPointerCapture(e.pointerId)}catch{}e.preventDefault()}
 moveGesture(e){const g=this.gesture;if(!g||g.pointerId!==e.pointerId)return;const dx=e.clientX-g.startX,dy=e.clientY-g.startY,z=g.z||this.store.ui.zoom||1;g.lastX=e.clientX;g.lastY=e.clientY;if(g.kind==='pending-node'&&Math.hypot(dx,dy)>4){g.kind='drag-node';g.moved=true;g.wrap.classList.add('is-dragging');g.wrap.style.pointerEvents='none';g.wrap.style.willChange='transform';this.selectedIds=new Set([g.id]);g.wrap.classList.add('selected')}if(g.kind==='drag-node'){g.wrap.style.transform=`translate(${dx/z}px,${dy/z}px)`;return}if(g.kind==='pending-marquee'&&Math.hypot(dx,dy)>4){g.kind='marquee';g.moved=true;this.marqueeEl=document.createElement('div');this.marqueeEl.className='selection-marquee';document.body.appendChild(this.marqueeEl)}if(g.kind==='marquee'&&this.marqueeEl){const left=Math.min(g.startX,e.clientX),top=Math.min(g.startY,e.clientY);this.marqueeEl.style.left=`${left}px`;this.marqueeEl.style.top=`${top}px`;this.marqueeEl.style.width=`${Math.abs(dx)}px`;this.marqueeEl.style.height=`${Math.abs(dy)}px`;return}if(g.kind==='resize'){const minW=28,minH=22;g.width=Math.max(minW,Math.min(this.deviceWidth(),g.startW+((g.dir.includes('e'))?dx/z:0)));g.height=Math.max(minH,Math.min(3000,g.startH+((g.dir.includes('s'))?dy/z:0)));if(g.dir.includes('e')){g.wrap.style.width=`${g.width}px`;const content=g.wrap.querySelector(':scope > .node-content');if(content)content.style.width=`${g.width}px`}if(g.dir.includes('s')){g.wrap.style.height=`${g.height}px`;const content=g.wrap.querySelector(':scope > .node-content');if(content)content.style.height=`${g.height}px`}g.moved=true;e.preventDefault()}}
 endGesture(e){const g=this.gesture;if(!g||g.pointerId!==e.pointerId)return;this.gesture=null;if(g.kind==='resize'){if(g.dir.includes('e'))g.wrap.style.width='';if(g.dir.includes('s'))g.wrap.style.height='';const content=g.wrap.querySelector(':scope > .node-content');if(content){if(g.dir.includes('e'))content.style.width='';if(g.dir.includes('s'))content.style.height=''}if(g.moved){const patch={};if(g.dir.includes('e'))patch.width=Math.round(g.width);if(g.dir.includes('s'))patch.height=Math.round(g.height);updateStyle(this.store,g.id,patch,this.store.ui.device);this.selectedIds=new Set([g.id]);this.ignoreClickUntil=Date.now()+200}return}if(g.kind==='marquee'){this.marqueeEl?.remove();this.marqueeEl=null;const left=Math.min(g.startX,e.clientX),right=Math.max(g.startX,e.clientX),top=Math.min(g.startY,e.clientY),bottom=Math.max(g.startY,e.clientY);let candidates=[...this.pageCanvas.querySelectorAll('.node-wrap[data-node-id]')].filter(w=>{if(w.hidden)return false;const r=w.getBoundingClientRect();return r.width>0&&r.height>0&&r.right>=left&&r.left<=right&&r.bottom>=top&&r.top<=bottom});candidates=candidates.filter(w=>!candidates.some(other=>other!==w&&w.contains(other)));this.selectedIds=new Set(candidates.map(w=>w.dataset.nodeId));this.setSelectionUI({selected:[...this.selectedIds].at(-1)||null,rightOpen:true});this.syncSelectionUI();this.ignoreClickUntil=Date.now()+200;return}if(g.kind==='drag-node'){const wrap=g.wrap;const targetEl=document.elementFromPoint(e.clientX,e.clientY);const targetWrap=targetEl?.closest?.('.node-wrap[data-node-id]');wrap.style.transform=g.originalTransform||'';wrap.style.pointerEvents='';wrap.style.willChange='';wrap.classList.remove('is-dragging');this.selectedIds=new Set([g.id]);let moved=false;if(targetWrap&&targetWrap.dataset.nodeId!==g.id){const type=targetWrap.dataset.bunaaType;const rect=targetWrap.getBoundingClientRect();const parent=targetWrap.parentElement;const cs=parent?getComputedStyle(parent):null;const vertical=!!cs&&/column/.test(cs.flexDirection||'');let before;if(vertical)before=e.clientY<rect.top+rect.height/2;else{const rtl=(cs?.direction||getComputedStyle(this.pageCanvas).direction)==='rtl';before=rtl?e.clientX>rect.left+rect.width/2:e.clientX<rect.left+rect.width/2}const relX=(e.clientX-rect.left)/Math.max(1,rect.width),relY=(e.clientY-rect.top)/Math.max(1,rect.height);const center=relX>.2&&relX<.8&&relY>.2&&relY<.8;const into=CONTAINER_TYPES.has(type)&&center;moved=moveNodeByDrop(this.store,g.id,targetWrap.dataset.nodeId,before,this.store.ui.device,into)}else moved=moveNodeToEnd(this.store,g.id);if(!moved)this.store.setUI({selected:g.id,rightOpen:true});this.ignoreClickUntil=Date.now()+250;this.syncSelectionUI();return}}
 cancelGesture(e){if(!this.gesture)return;const g=this.gesture;if(g.kind==='resize'){g.wrap.style.width='';g.wrap.style.height='';const content=g.wrap.querySelector(':scope > .node-content');if(content){content.style.width='';content.style.height=''}}if(g.wrap){g.wrap.style.transform=g.originalTransform||'';g.wrap.style.pointerEvents='';g.wrap.style.willChange='';g.wrap.classList.remove('is-dragging')}this.marqueeEl?.remove();this.marqueeEl=null;this.gesture=null}
 syncSelectionUI(){if(!this.pageCanvas)return;const all=[...this.pageCanvas.querySelectorAll('.node-wrap[data-node-id]')];all.forEach(w=>{const yes=this.selectedIds.has(w.dataset.nodeId);w.classList.toggle('multi-selected',yes&&this.selectedIds.size>1);if(this.selectedIds.size>1)w.classList.toggle('selected',yes);});this.renderSelectionHandles();const button=document.getElementById('groupSelectionBtn');if(button){button.disabled=this.selectedIds.size<2;button.textContent=this.selectedIds.size>1?`▧ تجميع (${this.selectedIds.size})`:'▧ تجميع';button.title=this.selectedIds.size>1?'تجميع العناصر المحددة في حاوية':'حدّد عنصرين أو أكثر بالماوس أولًا'}if(this.selectedIds.size>1){const info=document.getElementById('selectionInfo');if(info)info.textContent=`تم تحديد ${this.selectedIds.size} عناصر`} }
 renderSelectionHandles(){if(!this.pageCanvas)return;this.pageCanvas.querySelectorAll('.node-resize-handle').forEach(h=>h.remove());if(this.store.ui.interactionMode||this.selectedIds.size!==1)return;const id=[...this.selectedIds][0],wrap=[...this.pageCanvas.querySelectorAll('.node-wrap[data-node-id]')].find(w=>w.dataset.nodeId===id);if(!wrap||wrap.dataset.locked==='1')return;for(const [cls,dir] of SIZE_HANDLES){const handle=document.createElement('button');handle.type='button';handle.className=`node-resize-handle resize-${cls}`;handle.dataset.dir=dir;handle.setAttribute('aria-label',dir==='e'?'تغيير العرض':dir==='s'?'تغيير الارتفاع':'تغيير العرض والارتفاع');handle.tabIndex=-1;wrap.appendChild(handle)}}
 chooseGroupLayout(){const ids=[...this.selectedIds];if(ids.length<2){this.toast('حدّد عنصرين أو أكثر أولًا، ويمكنك سحب الماوس فوقهما.');return}const body='<p class="group-layout-intro">سيتم جمع العناصر المحددة في حاوية واحدة مع الحفاظ على محتواها وترتيبها. اختَر طريقة ترتيب العناصر داخل الحاوية.</p><div class="group-layout-options"><label class="group-layout-option"><input type="radio" name="groupLayout" value="row" checked><span class="group-layout-icon">↔</span><span><b>أفقي مرن</b><small>العناصر بجانب بعضها وتنتقل للسطر التالي عند الحاجة.</small></span></label><label class="group-layout-option"><input type="radio" name="groupLayout" value="column"><span class="group-layout-icon">↕</span><span><b>رأسي</b><small>كل عنصر أسفل العنصر السابق.</small></span></label><label class="group-layout-option"><input type="radio" name="groupLayout" value="grid"><span class="group-layout-icon">▦</span><span><b>شبكة</b><small>صفوف وأعمدة متساوية قابلة للتجاوب.</small></span></label><label class="group-layout-option"><input type="radio" name="groupLayout" value="stack"><span class="group-layout-icon">▤</span><span><b>مكدّس</b><small>ترتيب رأسي متراص مناسب للعناصر القصيرة.</small></span></label></div><p class="group-layout-hint">ملاحظة: التجميع يتطلب أن تكون العناصر في المستوى نفسه؛ لن يتم نقل العناصر أو حذفها إذا اختلفت الحاويات الأب.</p>';let modal;modal=showModal(document.getElementById('modalHost'),{title:'إنشاء حاوية من العناصر المحددة',body,wide:true,actions:[{label:'إلغاء'},{label:'إنشاء الحاوية',kind:'primary',onClick:()=>{const mode=modal.querySelector('input[name="groupLayout"]:checked')?.value||'row';const group=groupNodes(this.store,ids,mode);modal.remove();if(!group){this.toast('تعذّر التجميع: حدّد عنصرين على الأقل في المستوى نفسه داخل الصفحة. لم يتم حذف أي عنصر.');return}this.selectedIds=new Set([group.id]);this.store.setUI({selected:group.id,rightOpen:true});this.panels.setTab('layers');this.toast('تم إنشاء الحاوية؛ يمكنك تغيير ترتيبها وحجمها بالماوس.')}}]})}
 syncRuntime(){if(!this.store.ui.interactionMode){this.runtimeCleanup?.();this.runtimeCleanup=null;this.runtimeKey='';return}const key=JSON.stringify([this.store.project.activePageId,this.store.project.interactions,this.store.ui.device]);if(key===this.runtimeKey&&this.runtimeCleanup)return;this.runtimeCleanup?.();this.runtimeCleanup=createRuntime({document,project:this.store.project,navigate:id=>{if(this.store.project.pages.some(p=>p.id===id))this.store.setActivePage(id)}});this.runtimeKey=key}
 render(){const page=this.store.activePage();if(!page)return;const samePage=this.selectionPageId===page.id;const savedScrollTop=samePage?(this.viewport?.scrollTop||0):0;const savedScrollLeft=samePage?(this.viewport?.scrollLeft||0):0;if(!samePage){this.selectedIds.clear();this.selectionPageId=page.id;this.lastStoreSelection=this.store.ui.selected}else if(!this.internalSelectionUpdate&&this.store.ui.selected!==this.lastStoreSelection){this.selectedIds=this.store.ui.selected?new Set([this.store.ui.selected]):new Set()}this.lastStoreSelection=this.store.ui.selected;for(const id of [...this.selectedIds])if(!this.store.find(id))this.selectedIds.delete(id);renderPage(page,this.pageCanvas,{project:this.store.project,theme:this.store.project.theme,styleLibrary:this.store.project.styleLibrary,device:this.store.ui.device,selectedId:this.store.ui.interactionMode?null:this.store.ui.selected});this.deviceFrame.className=`site-frame ${this.store.ui.device}`;this.pageCanvas.classList.toggle('show-grid',this.store.ui.grid);document.getElementById('canvasPageTitle').textContent=page.name;document.getElementById('canvasModeLabel').textContent=this.store.ui.interactionMode?'وضع تجربة التفاعل':'وضع البناء';const hit=this.store.ui.selected?this.store.find(this.store.ui.selected):null;document.getElementById('selectionInfo').textContent=hit?`العنصر: ${hit.node.props?.label||hit.node.props?.title||hit.node.type}`:'لم يتم تحديد عنصر';document.getElementById('pageCountLabel').textContent=`${this.store.project.pages.length} صفحة`;document.getElementById('elementCountLabel').textContent=`${this.store.nodeCount()} عنصر`;document.getElementById('dropEmpty').classList.toggle('hidden',page.nodes.length>0);document.getElementById('gridBtn').classList.toggle('active',this.store.ui.grid);this.applyZoom();if(samePage&&this.viewport){const maxTop=Math.max(0,this.viewport.scrollHeight-this.viewport.clientHeight);this.viewport.scrollTop=Math.min(savedScrollTop,maxTop);this.viewport.scrollLeft=savedScrollLeft}this.syncSelectionUI();this.syncRuntime()}
 reflowHost(){const z=this.store.ui.zoom,base=this.deviceWidth();this.host.style.width=`${Math.ceil(base*z)}px`;this.host.style.height=`${Math.ceil(Math.max(this.stage.offsetHeight*z,760*z)+70)}px`}
 applyZoom(){const z=this.store.ui.zoom,base=this.deviceWidth();this.stage.style.width=`${base}px`;this.stage.style.maxWidth=`${base}px`;this.stage.style.transform=`scale(${z})`;this.stage.style.transformOrigin='top center';this.reflowHost();document.getElementById('zoomLabel').textContent=`${Math.round(z*100)}%`}
 sync(){this.render();document.body.classList.toggle('focus-canvas',this.store.ui.focus);this.refreshPages()}
 refreshPages(){const select=document.getElementById('pageSelect');if(!select)return;select.replaceChildren(...this.store.project.pages.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o}));select.value=this.store.project.activePageId}
 cleanup(){this.runtimeCleanup?.();this.runtimeCleanup=null;this.resizeObserver?.disconnect?.();window.removeEventListener('pointermove',this.onPointerMove);window.removeEventListener('pointerup',this.onPointerUp);window.removeEventListener('pointercancel',this.onPointerCancel);this.marqueeEl?.remove()}
}
exports.WorkspaceEngine = WorkspaceEngine;
});
