(function(w){
'use strict';
const U=w.Bunaa.Core,M=w.Bunaa.Model,S=w.Bunaa.Store.singleton,R=w.Bunaa.Renderer,X=w.Bunaa.Interactions,UI=w.Bunaa.UI,E={};
let started=false,drag=null,resize=null,spacePan=false,panning=null,rendering=false;
function page(){return S.activePage()}function selectedIds(){return S.ui.selectedIds.slice()}function node(id){return S.find(id)}function dom(id){return U.qa('.canvas-node',U.get('canvas')).find(el=>el.dataset.nodeId===id)||null}function canvasPoint(clientX,clientY){const r=U.get('canvas').getBoundingClientRect();return {x:(clientX-r.left)/S.ui.zoom,y:(clientY-r.top)/S.ui.zoom}}
function render(){if(rendering)return;rendering=true;const canvas=U.get('canvas');R.render(canvas,page(),selectedIds(),S.ui.preview);R.measure(canvas,S);applyViewport();UI.renderLibrary(S);UI.renderLayers(S);UI.renderInspector(S);UI.renderInteractions(S);UI.refresh(S);document.body.classList.toggle('preview-mode',S.ui.preview);U.get('previewBtn').textContent=S.ui.preview?'⏹ إنهاء المعاينة':'▶ معاينة';rendering=false}
function applyViewport(){const vp=U.get('viewport'),frame=U.get('deviceFrame'),layer=U.get('zoomLayer'),stage=U.get('stage'),sizes={desktop:[1120,810],tablet:[820,810],mobile:[390,850]},[w0,h0]=sizes[S.ui.device]||sizes.desktop;const z=S.ui.zoom;frame.className='device-frame '+S.ui.device;frame.style.width=w0+'px';frame.style.minHeight=h0+'px';frame.style.transform=`scale(${z})`;layer.style.width=(w0*z)+'px';layer.style.height=(Math.max(h0,U.get('canvas').offsetHeight)*z)+'px';stage.style.width=Math.max(w0*z,vp.clientWidth-70)+'px';stage.style.height=Math.max(h0*z,vp.clientHeight-30)+'px';U.get('zoomLabel').textContent=Math.round(z*100)+'%';U.get('gridBtn').classList.toggle('active',S.ui.grid);U.get('snapBtn').classList.toggle('active',S.ui.snap);vp.classList.toggle('no-grid',!S.ui.grid);U.qa('.device-btn').forEach(b=>b.classList.toggle('active',b.dataset.device===S.ui.device));U.get('canvasPageName').parentElement.querySelector('.canvas-size').textContent=w0+'×'+h0}
function setSelection(ids){const unique=[...new Set(ids.filter(Boolean))];S.setUi({selectedIds:unique});render()}
function select(id,add=false){if(!id)return;const cur=selectedIds();if(add){if(cur.includes(id))setSelection(cur.filter(x=>x!==id));else setSelection([...cur,id])}else setSelection([id])}
function add(type,parentId=null,point=null){const created=M.create(type),target=parentId||(selectedIds().length===1&&node(selectedIds()[0])?.allowChildren?selectedIds()[0]:null);S.commit('إضافة '+M.label(type),project=>{const p=project.pages.find(x=>x.id===project.activePageId),parent=target?M.find(p.nodes,target):null,arr=parent?.allowChildren?parent.children:p.nodes;created.layout.x=point?.x??(parent?18+arr.length*12:50);created.layout.y=point?.y??(parent?18+arr.length*12:50);created.layout.z=arr.length+1;if(parent&&parent.layout.display!=='block'){created.layout.order=arr.length;created.layout.position='relative'}arr.push(created)});S.setUi({selectedIds:[created.id],insertParentId:null});render();UI.toast(target?'تمت الإضافة داخل العنصر':'تمت إضافة العنصر');return created.id}
function removeMany(ids){if(!ids.length)return;S.commit('حذف العناصر',project=>{const p=project.pages.find(x=>x.id===project.activePageId);ids.slice().forEach(id=>M.remove(p.nodes,id))});S.setUi({selectedIds:[]});render();UI.toast('تم حذف العناصر')}
function cloneTree(original){const copy=U.clone(original),map={};M.walk([copy],n=>{const old=n.id;n.id=U.uid('node');map[old]=n.id;n.interactions=(n.interactions||[]).map(rule=>{const x=U.clone(rule);x.id=U.uid('int');if(x.targetId) x.targetId=map[x.targetId]||x.targetId;return x})});copy.name=(original.name||M.label(original.type))+' — نسخة';return copy}
function duplicate(ids){if(!ids.length)return;const copies=[];S.commit('نسخ العناصر',project=>{const p=project.pages.find(x=>x.id===project.activePageId);ids.forEach(id=>{const original=M.find(p.nodes,id);if(!original)return;const copy=cloneTree(original);const parent=M.parentOf(p.nodes,id),arr=parent?parent.children:p.nodes,idx=arr.findIndex(x=>x.id===id);copy.layout.x+=24;copy.layout.y+=24;arr.splice(idx+1,0,copy);copies.push(copy.id)})});S.setUi({selectedIds:copies});render()}
function moveBy(dx,dy){const ids=selectedIds();if(!ids.length)return;const step=S.ui.snap?8:1;S.commit('تحريك',project=>{ids.forEach(id=>{const n=M.find(project.pages.find(x=>x.id===project.activePageId).nodes,id);if(!n||n.layout.position==='relative')return;n.layout.x+=dx*step;n.layout.y+=dy*step})});render()}
function align(kind){const ids=selectedIds().map(node).filter(Boolean);if(ids.length<2)return;const primary=ids[0];S.commit('محاذاة العناصر',project=>{const p=project.pages.find(x=>x.id===project.activePageId),live=ids.map(n=>M.find(p.nodes,n.id)).filter(Boolean);if(kind==='left'){const x=Math.min(...live.map(n=>n.layout.x));live.forEach(n=>n.layout.x=x)}else if(kind==='center'){const center=primary.layout.x+(U.num(primary.layout.width,120)/2);live.forEach(n=>n.layout.x=center-U.num(n.layout.width,120)/2)}else if(kind==='right'){const right=Math.max(...live.map(n=>n.layout.x+U.num(n.layout.width,120)));live.forEach(n=>n.layout.x=right-U.num(n.layout.width,120))}else if(kind==='top'){const y=Math.min(...live.map(n=>n.layout.y));live.forEach(n=>n.layout.y=y)}else if(kind==='middle'){const c=primary.layout.y+U.num(primary.layout.height,80)/2;live.forEach(n=>n.layout.y=c-U.num(n.layout.height,80)/2)}else if(kind==='bottom'){const b=Math.max(...live.map(n=>n.layout.y+U.num(n.layout.height,80)));live.forEach(n=>n.layout.y=b-U.num(n.layout.height,80))}else if(kind==='horizontal'){live.sort((a,b)=>a.layout.x-b.layout.x);const first=live[0],last=live[live.length-1],total=live.reduce((s,n)=>s+U.num(n.layout.width,120),0),gap=(last.layout.x-first.layout.x+U.num(last.layout.width,120)-total)/(live.length-1);let x=first.layout.x;live.forEach(n=>{n.layout.x=x;x+=U.num(n.layout.width,120)+gap})}else if(kind==='vertical'){live.sort((a,b)=>a.layout.y-b.layout.y);const first=live[0],last=live[live.length-1],total=live.reduce((s,n)=>s+U.num(n.layout.height,60),0),gap=(last.layout.y-first.layout.y+U.num(last.layout.height,60)-total)/(live.length-1);let y=first.layout.y;live.forEach(n=>{n.layout.y=y;y+=U.num(n.layout.height,60)+gap})}});render()}
function reparentProject(project,id,parentId){const p=project.pages.find(x=>x.id===project.activePageId);if(!p||id===parentId)return false;const moving=M.find(p.nodes,id);const target=parentId?M.find(p.nodes,parentId):null;if(!moving)return false;if(target&&(!target.allowChildren||M.contains(moving,parentId)))return false;M.remove(p.nodes,id);if(target){target.children.push(moving);moving.layout.position=target.layout.display==='block'?'absolute':'relative';moving.layout.order=target.children.length-1;if(moving.layout.position==='relative'){moving.layout.x=0;moving.layout.y=0}else{moving.layout.x=18;moving.layout.y=18}}else{p.nodes.push(moving);moving.layout.position='absolute';moving.layout.x=50;moving.layout.y=50}return true}
function reparent(id,parentId){S.commit('تغيير الحاوية',project=>reparentProject(project,id,parentId));render();UI.toast(parentId?'تم إدخال العنصر داخل الحاوية':'تم إخراج العنصر')}
function saveInspector(){const id=selectedIds()[0];if(!id)return;const g=k=>U.get(k);S.commit('تعديل الخصائص',project=>{const n=M.find(project.pages.find(x=>x.id===project.activePageId).nodes,id);if(!n)return;const L=n.layout,sty=n.style=n.style||{},P=n.props=n.props||{};n.name=g('pName').value.trim()||M.label(n.type);n.text=g('pText').value;L.display=g('pDisplay').value;L.position=g('pPosition').value;L.widthMode=g('pWidthMode').value;L.heightMode=g('pHeightMode').value;L.width=L.widthMode==='fixed'?Math.max(20,U.num(g('pWidth').value,120)):null;L.height=L.heightMode==='fixed'?Math.max(1,U.num(g('pHeight').value,60)):null;L.x=U.num(g('pX').value,0);L.y=U.num(g('pY').value,0);L.minWidth=g('pMinW').value===''?null:U.num(g('pMinW').value,0);L.maxWidth=g('pMaxW').value===''?null:U.num(g('pMaxW').value,0);L.minHeight=g('pMinH').value===''?null:U.num(g('pMinH').value,0);L.maxHeight=g('pMaxH').value===''?null:U.num(g('pMaxH').value,0);L.gap=U.num(g('pGap').value,0);L.gridColumns=Math.max(1,Math.round(U.num(g('pCols').value,3)));L.direction=g('pDirection').value;L.align=g('pAlign').value;L.justify=g('pJustify').value;L.overflow=g('pOverflow').value;L.wrap=g('pWrap').checked;L.locked=g('pLocked').checked;L.aspectLocked=g('pAspect').checked;sty.paddingTop=U.num(g('pPT').value,0);sty.paddingRight=U.num(g('pPR').value,0);sty.paddingBottom=U.num(g('pPB').value,0);sty.paddingLeft=U.num(g('pPL').value,0);sty.fontSize=U.num(g('pFont').value,16);sty.radius=U.num(g('pRadius').value,0);sty.background=g('pBg').value;sty.color=g('pColor').value;sty.border=g('pBorder').value;sty.shadow=g('pShadow').value;sty.opacity=U.clamp(g('pOpacity').value,0,1);if(g('pHref'))P.href=g('pHref').value;if(g('pSrc'))P.src=g('pSrc').value;if(g('pAlt'))P.alt=g('pAlt').value;if(g('pPlaceholder'))P.placeholder=g('pPlaceholder').value;if(g('pLabel'))P.label=g('pLabel').value});render();UI.toast('تم حفظ الخصائص')}
function addInteraction(){const n=selectedIds().length===1?node(selectedIds()[0]):null;if(!n)return;const r={id:U.uid('int'),event:U.get('intEvent').value,action:U.get('intAction').value};if(r.action==='animate')r.effect=U.get('intEffect').value;if(r.action==='navigate')r.targetPageId=U.get('intPage').value;if(r.action==='url')r.url=U.get('intUrl').value;if(r.action==='text')r.value=U.get('intValue').value;if(['show','hide','toggle'].includes(r.action))r.targetId=U.get('intTarget').value;S.commit('إضافة تفاعل',project=>M.find(project.pages.find(x=>x.id===project.activePageId).nodes,n.id).interactions.push(r));render();UI.toast('تمت إضافة التفاعل')}
function bind(){const canvas=U.get('canvas');X.attach(canvas,S,render);
 U.get('bootActions')?.addEventListener('click',e=>{if(e.target.dataset.mode)w.BunaaApp.open(e.target.dataset.mode)});
 U.get('elementSearch').addEventListener('input',e=>{S.setUi({search:e.target.value});UI.renderLibrary(S)});U.get('categoryBar').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){S.setUi({category:b.dataset.category});UI.renderLibrary(S)}});
 U.get('library').addEventListener('click',e=>{const b=e.target.closest('[data-add-type]');if(b)add(b.dataset.addType)});
 U.get('library').addEventListener('dragstart',e=>{const b=e.target.closest('[data-add-type]');if(b)e.dataTransfer.setData('text/bunaa-type',b.dataset.addType)});
 U.qa('[data-quick-type]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.quickType)));
 U.get('canvas').addEventListener('click',e=>{if(S.ui.preview)return;const handle=e.target.closest('.resize-handle,.drag-grip');if(handle)return;if(U.isField(e.target))return;const n=e.target.closest('.canvas-node');if(n)select(n.dataset.nodeId,e.shiftKey);else setSelection([])});
 canvas.addEventListener('pointerdown',onPointerDown);window.addEventListener('pointermove',onPointerMove);window.addEventListener('pointerup',onPointerUp);
 canvas.addEventListener('dragover',e=>{if(!e.dataTransfer.types.includes('text/bunaa-type'))return;e.preventDefault();const target=dropTarget(e.clientX,e.clientY);U.qa('.drop-target',canvas).forEach(x=>x.classList.remove('drop-target'));target?.classList.add('drop-target')});canvas.addEventListener('dragleave',e=>{if(e.target===canvas)U.qa('.drop-target',canvas).forEach(x=>x.classList.remove('drop-target'))});canvas.addEventListener('drop',e=>{const type=e.dataTransfer.getData('text/bunaa-type');if(!type)return;e.preventDefault();const target=dropTarget(e.clientX,e.clientY);U.qa('.drop-target',canvas).forEach(x=>x.classList.remove('drop-target'));const pt=canvasPoint(e.clientX,e.clientY);add(type,target?.dataset.nodeId||null,pt)});
 U.get('zoomIn').onclick=()=>zoomBy(.1);U.get('zoomOut').onclick=()=>zoomBy(-.1);U.get('zoomReset').onclick=()=>setZoom(1);U.get('fitBtn').onclick=fit;U.get('gridBtn').onclick=()=>{S.setUi({grid:!S.ui.grid});render()};U.get('snapBtn').onclick=()=>{S.setUi({snap:!S.ui.snap});render()};
 U.get('viewport').addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoomBy(e.deltaY<0?.1:-.1,{clientX:e.clientX,clientY:e.clientY})}else if(spacePan){e.preventDefault();U.get('viewport').scrollLeft+=e.deltaX;U.get('viewport').scrollTop+=e.deltaY}}, {passive:false}); U.get('viewport').addEventListener('pointerdown',e=>{if(spacePan||e.button===1){panning={x:e.clientX,y:e.clientY,scrollLeft:U.get('viewport').scrollLeft,scrollTop:U.get('viewport').scrollTop};U.get('viewport').setPointerCapture?.(e.pointerId);e.preventDefault()}});window.addEventListener('pointerup',e=>{if(panning){try{U.get('viewport').releasePointerCapture?.(e.pointerId)}catch{}panning=null}});
 U.get('undoBtn').onclick=()=>{S.undo();render()};U.get('redoBtn').onclick=()=>{S.redo();render()};U.get('previewBtn').onclick=()=>{S.setUi({preview:!S.ui.preview,selectedIds:S.ui.preview?[]:S.ui.selectedIds});render()};U.get('exportBtn').onclick=()=>w.Bunaa.Exporter.download(S);U.get('homeBtn').onclick=()=>w.BunaaApp.resetToBoot();U.get('newPageBtn').onclick=()=>addPage();U.get('pageSelect').onchange=e=>{S.commit('تغيير الصفحة',p=>p.activePageId=e.target.value);S.setUi({selectedIds:[],preview:false});render()};
 U.qa('.device-btn').forEach(b=>b.onclick=()=>{S.setUi({device:b.dataset.device});applyViewport();fit()});U.qa('[data-align]').forEach(b=>b.onclick=()=>align(b.dataset.align));
 U.qa('[data-tab]').forEach(b=>b.onclick=()=>{S.setUi({tab:b.dataset.tab});UI.renderLibrary(S);UI.renderLayers(S);UI.renderInteractions(S)});
 U.get('layers').addEventListener('click',onLayerClick);U.get('collapseLayers').onclick=()=>{const ids=S.all().map(x=>x.node.id),allOpen=ids.some(id=>S.ui.collapsedLayers[id]===true);const next={};ids.forEach(id=>next[id]=!allOpen);S.setUi({collapsedLayers:next});UI.renderLayers(S)};
 U.get('inspector').addEventListener('click',e=>{if(e.target.id==='saveLayout'||e.target.id==='saveProps')saveInspector();if(e.target.id==='duplicateNode')duplicate(selectedIds());if(e.target.id==='deleteNode')removeMany(selectedIds());if(e.target.id==='focusElement'){const d=dom(selectedIds()[0]);d?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'});d?.classList.add('focus-pulse');setTimeout(()=>d?.classList.remove('focus-pulse'),700)}if(e.target.id==='addChildNode')add('container',selectedIds()[0]);if(e.target.id==='detachNode')reparent(selectedIds()[0],null)});U.get('inspector').addEventListener('input',e=>{if(e.target.matches('#pWidthMode,#pHeightMode'))return});U.get('inspector').addEventListener('change',e=>{if(e.target.id==='pWidthMode'){const input=U.get('pWidth');input.disabled=e.target.value!=='fixed';}if(e.target.id==='pHeightMode'){const input=U.get('pHeight');input.disabled=e.target.value!=='fixed';}});
 U.get('interactionPanel').addEventListener('click',e=>{if(e.target.id==='addInteraction')addInteraction();const b=e.target.closest('[data-remove-interaction]');if(b){const n=node(selectedIds()[0]);S.commit('حذف تفاعل',p=>M.find(p.pages.find(x=>x.id===p.activePageId).nodes,n.id).interactions.splice(Number(b.dataset.removeInteraction),1));render()}});U.get('interactionPanel').addEventListener('change',e=>{if(e.target.id==='intAction')UI.renderInteractionExtra(S)});
 document.addEventListener('keydown',onKeyDown);document.addEventListener('keyup',e=>{if(e.code==='Space'){spacePan=false;document.body.classList.remove('space-pan')}});
 window.addEventListener('resize',U.debounce(()=>{applyViewport()},80));S.subscribe(()=>{if(!started)return;render()});
}
function addPage(){const pg={id:U.uid('page'),name:'صفحة جديدة',slug:'page-'+Date.now().toString(36),nodes:[M.create('section',{name:'قسم جديد',layout:{x:50,y:50,widthMode:'fixed',width:700}})]};S.commit('إضافة صفحة',p=>p.pages.push(pg));S.setUi({selectedIds:[pg.nodes[0].id]});S.commit('تفعيل الصفحة',p=>p.activePageId=pg.id);render()}
function onLayerClick(e){const row=e.target.closest('[data-layer-id]');if(!row)return;const id=row.dataset.layerId;if(e.target.closest('[data-layer-toggle]')){S.setUi({collapsedLayers:{...S.ui.collapsedLayers,[id]:S.ui.collapsedLayers[id]!==true}});UI.renderLayers(S);return}const action=e.target.closest('[data-layer-action]')?.dataset.layerAction;if(action){if(action==='delete')return removeMany([id]);if(action==='duplicate')return duplicate([id]);const parent=S.parentOf(id),arr=parent?parent.children:page().nodes,idx=arr.findIndex(x=>x.id===id);if(action==='up'&&idx>0)S.commit('ترتيب الطبقات',p=>{const pp=M.parentOf(p.pages.find(x=>x.id===p.activePageId).nodes,id),a=pp?pp.children:p.pages.find(x=>x.id===p.activePageId).nodes;[a[idx-1],a[idx]]=[a[idx],a[idx-1]]});if(action==='down'&&idx<a.length-1)S.commit('ترتيب الطبقات',p=>{const pp=M.parentOf(p.pages.find(x=>x.id===p.activePageId).nodes,id),a=pp?pp.children:p.pages.find(x=>x.id===p.activePageId).nodes;[a[idx+1],a[idx]]=[a[idx],a[idx+1]]});render();return}select(id,e.shiftKey)}
function dropTarget(x,y){const els=U.qa('.canvas-node.is-container',U.get('canvas'));let best=null,bestArea=Infinity;for(const el of els){if(selectedIds().includes(el.dataset.nodeId))continue;const r=el.getBoundingClientRect();if(U.pointInRect(x,y,r)){const area=r.width*r.height;if(area<bestArea){best=el;bestArea=area}}}return best}
function onPointerDown(e){if(S.ui.preview)return;const handle=e.target.closest('.resize-handle');if(handle){const d=e.target.closest('.canvas-node');if(!d)return;const n=node(d.dataset.nodeId);if(!n||n.layout.locked)return;const r=d.getBoundingClientRect();resize={id:n.id,dir:handle.dataset.resize,startX:e.clientX,startY:e.clientY,startW:r.width/S.ui.zoom,startH:r.height/S.ui.zoom,startLeft:n.layout.x,startTop:n.layout.y,before:S.begin('تغيير حجم '+M.label(n.type))};e.preventDefault();return}if(e.code==='Space'||spacePan)return;const grip=e.target.closest('.drag-grip');const d=e.target.closest('.canvas-node');if(!d||U.isField(e.target))return;if(e.button!==0)return;const n=node(d.dataset.nodeId);if(!n||n.layout.locked)return;const pflow=S.parentOf(n.id)?.layout?.display;const rel=['flex','grid','inline-flex'].includes(pflow)&&n.layout.position==='relative';if(rel){return}if(!selectedIds().includes(n.id))select(n.id,e.shiftKey);const ids=selectedIds().includes(n.id)?selectedIds():[n.id];const pt=canvasPoint(e.clientX,e.clientY);drag={ids,startX:e.clientX,startY:e.clientY,start:dragSnapshot(ids),before:S.begin('تحريك العناصر'),alt:e.altKey,started:false};e.preventDefault()}
function dragSnapshot(ids){return ids.map(id=>{const n=node(id);return {id,x:n?.layout.x||0,y:n?.layout.y||0}})}
function onPointerMove(e){if(resize){const dx=(e.clientX-resize.startX)/S.ui.zoom,dy=(e.clientY-resize.startY)/S.ui.zoom;const ratio=resize.startW/Math.max(1,resize.startH);let w=resize.startW,h=resize.startH,x=resize.startLeft,y=resize.startTop;if(resize.dir.includes('e'))w=resize.startW+dx;if(resize.dir.includes('w')){w=resize.startW-dx;x=resize.startLeft+dx}if(resize.dir.includes('s'))h=resize.startH+dy;if(resize.dir.includes('n')){h=resize.startH-dy;y=resize.startTop+dy}const n=node(resize.id);if(n?.layout.aspectLocked){if(Math.abs(dx)>Math.abs(dy))h=w/ratio;else w=h*ratio}w=Math.max(20,w);h=Math.max(1,h);S.draft(resize.before,p=>{const live=M.find(p.pages.find(x=>x.id===p.activePageId).nodes,resize.id);live.layout.widthMode='fixed';live.layout.heightMode='fixed';live.layout.width=Math.round(w);live.layout.height=Math.round(h);live.layout.x=Math.round(x);live.layout.y=Math.round(y)});render();return}if(drag){const dx=(e.clientX-drag.startX)/S.ui.zoom,dy=(e.clientY-drag.startY)/S.ui.zoom;if(!drag.started&&Math.hypot(dx,dy)<3)return;drag.started=true;const step=S.ui.snap?8:1,sx=Math.round(dx/step)*step,sy=Math.round(dy/step)*step;S.draft(drag.before,p=>{const pg=p.pages.find(x=>x.id===p.activePageId);drag.start.forEach(snap=>{const live=M.find(pg.nodes,snap.id);if(live&&live.layout.position!=='relative'){live.layout.x=Math.round(snap.x+sx);live.layout.y=Math.round(snap.y+sy)}})});render();return}if(panning){const vp=U.get('viewport');vp.scrollLeft=panning.scrollLeft-(e.clientX-panning.x);vp.scrollTop=panning.scrollTop-(e.clientY-panning.y)}}
function onPointerUp(e){if(resize){S.end(resize.before);resize=null;render();return}if(drag){const moved=drag.started;const target=dropTarget(e.clientX,e.clientY);if(moved&&drag.ids.length===1&&target){S.draft(drag.before,p=>reparentProject(p,drag.ids[0],target.dataset.nodeId))}S.end(drag.before);const ids=drag.ids.slice();drag=null;if(moved&&e.altKey)duplicate(ids);render()}}
function zoomBy(delta,anchor){setZoom(S.ui.zoom+delta,anchor)}
function setZoom(z,anchor){z=Math.round(U.clamp(z,.35,2.5)*100)/100;if(z===S.ui.zoom)return;const vp=U.get('viewport');const a=anchor||{clientX:vp.getBoundingClientRect().left+vp.clientWidth/2,clientY:vp.getBoundingClientRect().top+vp.clientHeight/2};const vr=vp.getBoundingClientRect(),old=S.ui.zoom,sx=(vp.scrollLeft+a.clientX-vr.left)/old,sy=(vp.scrollTop+a.clientY-vr.top)/old;S.setUi({zoom:z});render();requestAnimationFrame(()=>{vp.scrollLeft=Math.max(0,sx*z-(a.clientX-vr.left));vp.scrollTop=Math.max(0,sy*z-(a.clientY-vr.top))})}
function fit(){const vp=U.get('viewport'),sizes={desktop:1120,tablet:820,mobile:390},w0=sizes[S.ui.device]||1120,h0=810;const z=Math.min((vp.clientWidth-90)/w0,(vp.clientHeight-90)/h0);setZoom(U.clamp(z,.35,1.5))}
function onKeyDown(e){if(U.isInput(e.target))return;if(e.code==='Space'){spacePan=true;document.body.classList.add('space-pan');return}const ids=selectedIds();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?S.redo():S.undo();render();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();S.redo();render();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate(ids);return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeMany(ids);return}if(e.key==='Escape'){S.setUi({selectedIds:[],preview:false});render();return}if(ids.length&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveBy(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0,e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0)}}
E.start=()=>{if(started)return;started=true;S.load();bind();render()};E.resetToBoot=()=>{started=false;document.body.classList.remove('preview-mode');U.get('app').classList.add('hidden');U.get('bootScreen').classList.remove('hidden');U.qa('[data-mode]').forEach(b=>b.disabled=false);S.setUi({preview:false,selectedIds:[]})};E.add=add;E.render=render;E.started=()=>started;w.Bunaa.Editor=E;
})(window);