(function(w){
'use strict';
const U=w.Bunaa.Core,M=w.Bunaa.Model,E={};
function styleFor(n){const s=n.style||{},l=n.layout||{},p={top:U.num(s.paddingTop,s.padding||0),right:U.num(s.paddingRight,s.padding||0),bottom:U.num(s.paddingBottom,s.padding||0),left:U.num(s.paddingLeft,s.padding||0)};let css=`box-sizing:border-box;position:${l.position==='relative'?'relative':'relative'};`;if(l.widthMode==='fixed')css+=`width:${U.num(l.width,120)}px;`;else if(l.widthMode==='fill')css+='width:100%;';else css+='width:max-content;';if(l.heightMode==='fixed')css+=`height:${U.num(l.height,60)}px;`;if(l.display==='flex')css+=`display:flex;flex-direction:${l.direction};gap:${U.num(l.gap,0)}px;flex-wrap:${l.wrap?'wrap':'nowrap'};align-items:${l.align==='center'?'center':l.align==='end'?'flex-end':'flex-start'};justify-content:${l.justify==='between'?'space-between':l.justify==='center'?'center':l.justify==='end'?'flex-end':'flex-start'};`;else if(l.display==='grid')css+=`display:grid;grid-template-columns:repeat(${Math.max(1,l.gridColumns||3)},minmax(0,1fr));gap:${U.num(l.gap,0)}px;`;else css+='display:block;';css+=`padding:${p.top}px ${p.right}px ${p.bottom}px ${p.left}px;`;if(s.background)css+=`background:${s.background};`;if(s.color)css+=`color:${s.color};`;if(s.fontSize)css+=`font-size:${s.fontSize}px;`;if(s.fontWeight)css+=`font-weight:${s.fontWeight};`;if(s.lineHeight)css+=`line-height:${s.lineHeight};`;if(s.radius!=null)css+=`border-radius:${s.radius}px;`;if(s.border)css+=`border:${s.border};`;if(s.shadow)css+=`box-shadow:${s.shadow};`;return css}
function body(n){const t=U.esc(n.text||'');switch(n.type){case'heading':return `<h2>${t}</h2>`;case'text':return `<p>${t}</p>`;case'button':return `<button type="button">${t}</button>`;case'link':return `<a href="${U.esc(U.safeUrl(n.props.href||'#'))}">${t}</a>`;case'image':return `<img src="${U.esc(n.props.src||'')}" alt="${U.esc(n.props.alt||'')}">`;default:return t}}
function node(n){const children=n.children?.length?`<div class="children">${n.children.map(node).join('')}</div>`:'';return `<section class="bunaa-node bunaa-${U.esc(n.type)}" style="${styleFor(n)}">${body(n)}${children}</section>`}
E.projectJson=p=>JSON.stringify(p,null,2);
E.pageHtml=(project,page)=>`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${U.esc(page.name)}</title><style>body{margin:0;padding:32px;background:${U.esc(project.theme.background||'#fff')};font-family:${U.esc(project.theme.fontFamily||'Segoe UI,Tahoma,Arial')};color:${U.esc(project.theme.color||'#182136')}.bunaa-node{margin:0 0 18px}.bunaa-node h2,.bunaa-node p{margin:0 0 10px}.bunaa-node button{padding:10px 18px;border:0;border-radius:10px;background:#6575e6;color:#fff}.bunaa-node a{color:#5266d8}.children{display:contents}</style></head><body>${page.nodes.map(node).join('')}</body></html>`;
E.download=store=>{const p=store.activePage();U.download(E.pageHtml(store.project,p),(p.slug||'page')+'.html','text/html;charset=utf-8');U.download(E.projectJson(store.project),'bunaa-project.json','application/json;charset=utf-8')};
w.Bunaa.Exporter=E;
})(window);