(function(w){
'use strict';
const U=w.Bunaa.Core,M={};
M.VERSION=8;M.STORAGE_KEY='bunaa-pro-project';M.LEGACY_STORAGE_KEYS=['bunaa-v13-project','bunaa-v12-project'];
const shared={fontFamily:'Inter, Segoe UI, Tahoma, Arial, sans-serif',color:'#182136'};
const defs={
 heading:{label:'عنوان',category:'نص',icon:'T',defaultText:'عنوان جديد',style:{fontSize:34,fontWeight:800,color:'#182136'},layout:{widthMode:'hug',heightMode:'hug'}},
 text:{label:'نص',category:'نص',icon:'≡',defaultText:'اكتب نصك هنا…',style:{fontSize:17,lineHeight:1.65,color:'#445066'},layout:{widthMode:'hug',heightMode:'hug'}},
 button:{label:'زر',category:'واجهة',icon:'↗',defaultText:'اضغط هنا',props:{href:'#'},style:{paddingX:18,paddingY:11,radius:10,background:'#6575e6',color:'#fff',fontWeight:750},layout:{widthMode:'hug',heightMode:'hug'}},
 link:{label:'رابط',category:'واجهة',icon:'↗',defaultText:'رابط',props:{href:'#'},style:{color:'#5266d8',fontWeight:700},layout:{widthMode:'hug',heightMode:'hug'}},
 image:{label:'صورة',category:'وسائط',icon:'▧',props:{src:'',alt:'صورة'},layout:{widthMode:'fixed',heightMode:'hug',width:320}},
 card:{label:'بطاقة',category:'حاويات',icon:'▣',container:true,defaultText:'بطاقة محتوى',style:{padding:22,radius:16,background:'#fff',shadow:'0 18px 45px rgba(20,35,70,.10)'},layout:{widthMode:'hug',heightMode:'hug'}},
 section:{label:'قسم',category:'حاويات',icon:'□',container:true,style:{padding:32,radius:14,background:'#f5f7fb'},layout:{widthMode:'fixed',heightMode:'hug',width:720}},
 container:{label:'حاوية',category:'حاويات',icon:'▢',container:true,style:{padding:18,radius:12,border:'1px dashed #bdc7db',background:'#ffffff'},layout:{widthMode:'hug',heightMode:'hug',minWidth:120,minHeight:60}},
 stack:{label:'Stack',category:'حاويات',icon:'☰',container:true,props:{direction:'column',gap:12},style:{padding:18,radius:14,background:'#f7f8fc'},layout:{display:'flex',direction:'column',widthMode:'hug',heightMode:'hug',gap:12}},
 grid:{label:'Grid',category:'حاويات',icon:'▦',container:true,props:{columns:3},style:{padding:18,radius:14,background:'#f7f8fc'},layout:{display:'grid',gridColumns:3,widthMode:'hug',heightMode:'hug',gap:18}},
 hero:{label:'واجهة رئيسية',category:'حاويات',icon:'✦',container:true,defaultText:'ابنِ موقعك بسرعة',style:{padding:58,radius:20,background:'#596ce3',color:'#fff',fontSize:31,fontWeight:800},layout:{display:'block',widthMode:'fixed',heightMode:'hug',width:760}},
 navbar:{label:'شريط تنقل',category:'حاويات',icon:'≡',container:true,defaultText:'بَنّاء   •   الرئيسية   •   الخدمات   •   تواصل',style:{paddingX:22,paddingY:16,radius:12,background:'#10182a',color:'#fff',fontWeight:700},layout:{display:'flex',direction:'row',align:'center',justify:'between',widthMode:'fill',heightMode:'hug'}},
 footer:{label:'تذييل',category:'حاويات',icon:'⌄',container:true,defaultText:'© بَنّاء — جميع الحقوق محفوظة',style:{padding:22,radius:12,background:'#10182a',color:'#fff'},layout:{widthMode:'fixed',heightMode:'hug',width:720}},
 form:{label:'نموذج',category:'حاويات',icon:'▤',container:true,defaultText:'نموذج تواصل',style:{padding:20,radius:14,background:'#fff',border:'1px solid #e2e7f0'},layout:{widthMode:'hug',heightMode:'hug'}},
 input:{label:'حقل إدخال',category:'نموذج',icon:'▭',props:{placeholder:'اكتب هنا'},style:{paddingX:12,paddingY:10},layout:{widthMode:'fixed',heightMode:'hug',width:240}},
 textarea:{label:'مربع نص',category:'نموذج',icon:'▤',props:{placeholder:'اكتب رسالتك'},style:{paddingX:12,paddingY:10},layout:{widthMode:'fixed',heightMode:'fixed',width:280,height:110}},
 select:{label:'قائمة اختيار',category:'نموذج',icon:'▾',props:{options:'الخيار الأول|الخيار الثاني|الخيار الثالث'},style:{paddingX:10,paddingY:9},layout:{widthMode:'fixed',heightMode:'hug',width:240}},
 checkbox:{label:'مربع اختيار',category:'نموذج',icon:'☑',props:{label:'أوافق'},style:{padding:8},layout:{widthMode:'hug',heightMode:'hug'}},
 radio:{label:'خيار دائري',category:'نموذج',icon:'◉',props:{label:'الخيار'},style:{padding:8},layout:{widthMode:'hug',heightMode:'hug'}},
 gallery:{label:'معرض',category:'وسائط',icon:'▧',container:true,style:{padding:12,radius:12},layout:{display:'flex',direction:'row',gap:10,wrap:true,widthMode:'hug',heightMode:'hug'}},
 carousel:{label:'شرائح',category:'وسائط',icon:'◈',container:true,props:{items:['الشريحة الأولى','الشريحة الثانية','الشريحة الثالثة'],index:0},style:{padding:24,radius:14,background:'#eef1ff'},layout:{widthMode:'hug',heightMode:'hug'}},
 video:{label:'فيديو',category:'وسائط',icon:'▶',props:{src:'',poster:''},style:{background:'#111827',radius:12},layout:{widthMode:'fixed',heightMode:'fixed',width:340,height:190}},
 audio:{label:'صوت',category:'وسائط',icon:'◖',props:{src:''},style:{padding:12,radius:12,background:'#eef1ff'},layout:{widthMode:'fixed',heightMode:'hug',width:280}},
 alert:{label:'تنبيه',category:'واجهة',icon:'!',container:true,defaultText:'هذه رسالة تنبيه',style:{padding:14,radius:12,background:'#fff3cd',color:'#725a00'},layout:{widthMode:'hug',heightMode:'hug'}},
 badge:{label:'شارة',category:'واجهة',icon:'●',defaultText:'شارة',style:{paddingX:9,paddingY:5,radius:999,background:'#e6ebff',color:'#3f51b4',fontSize:13,fontWeight:700},layout:{widthMode:'hug',heightMode:'hug'}},
 progress:{label:'تقدم',category:'بيانات',icon:'▰',props:{value:72},layout:{widthMode:'fixed',heightMode:'hug',width:260}},
 stats:{label:'إحصاءات',category:'بيانات',icon:'▥',container:true,defaultText:'72%',props:{label:'التقدم'},style:{padding:22,radius:16,background:'#eef1ff',fontSize:28,fontWeight:800},layout:{widthMode:'hug',heightMode:'hug'}},
 pricing:{label:'أسعار',category:'بيانات',icon:'◆',container:true,defaultText:'99 ر.ع / شهر',props:{label:'الخطة الاحترافية'},style:{padding:24,radius:18,background:'#fff',fontSize:25,fontWeight:800,shadow:'0 18px 40px rgba(20,35,70,.09)'},layout:{widthMode:'hug',heightMode:'hug'}},
 testimonial:{label:'شهادة',category:'بيانات',icon:'❞',container:true,defaultText:'تجربة ممتازة جدًا.',props:{author:'عميل'},style:{padding:22,radius:16,background:'#fff'},layout:{widthMode:'hug',heightMode:'hug'}},
 table:{label:'جدول',category:'بيانات',icon:'▤',container:true,props:{rows:[['العنصر','القيمة'],['المشروع','Bunaa'],['الحالة','جاهز']]},style:{padding:14,radius:12,background:'#fff'},layout:{widthMode:'hug',heightMode:'hug'}},
 chart:{label:'رسم',category:'بيانات',icon:'▥',container:true,props:{values:[25,55,40,80,65]},style:{padding:18,radius:12,background:'#fff'},layout:{widthMode:'hug',heightMode:'hug'}},
 faq:{label:'أسئلة شائعة',category:'واجهة',icon:'?',container:true,defaultText:'كيف يعمل بَنّاء؟',props:{answer:'أضف عنصرًا وحدده ثم عدّل خصائصه.'},style:{padding:18,radius:12,background:'#fff'},layout:{widthMode:'hug',heightMode:'hug'}},
 counter:{label:'عداد',category:'بيانات',icon:'#',defaultText:'1250',props:{label:'زائر'},style:{padding:22,radius:14,background:'#eef1ff',fontSize:30,fontWeight:800},layout:{widthMode:'hug',heightMode:'hug'}},
 social:{label:'تواصل',category:'واجهة',icon:'●',defaultText:'YouTube   •   X   •   Instagram',style:{padding:14},layout:{widthMode:'hug',heightMode:'hug'}},
 spacer:{label:'مسافة',category:'تخطيط',icon:'↕',props:{height:60},layout:{widthMode:'fixed',heightMode:'fixed',width:30,height:60}},
 divider:{label:'فاصل',category:'تخطيط',icon:'—',style:{height:1,background:'#d9deea'},layout:{widthMode:'fixed',heightMode:'fixed',width:340,height:1}}
};
M.defs=defs;
M.categories=['الكل','حاويات','نص','واجهة','تخطيط','نموذج','وسائط','بيانات'];
M.label=t=>defs[t]?.label||t;M.category=t=>defs[t]?.category||'أخرى';M.icon=t=>defs[t]?.icon||'•';M.isContainer=t=>!!defs[t]?.container;M.supportsChildren=t=>!!defs[t]?.container;
function normalizeLayout(l,type,depth){const d=defs[type]||defs.text;const x=U.num(l.x,36),y=U.num(l.y,36);let display=['flex','grid','block','inline-flex','inline-block'].includes(l.display)?l.display:(d.layout?.display||'block');if(type==='stack')display='flex';if(type==='grid')display='grid';const widthMode=['hug','fill','fixed'].includes(l.widthMode)?l.widthMode:(l.widthMode==='auto'?'hug':(d.layout?.widthMode||'hug'));const heightMode=['hug','fill','fixed'].includes(l.heightMode)?l.heightMode:(l.heightMode==='auto'?'hug':(d.layout?.heightMode||'hug'));return Object.assign({x,y,z:U.num(l.z,1),position:l.position==='relative'?'relative':'absolute',widthMode,heightMode,width:null,height:null,minWidth:null,maxWidth:null,minHeight:null,maxHeight:null,display,direction:l.direction==='row'?'row':'column',wrap:!!l.wrap,gap:U.num(l.gap,U.num(d.layout?.gap,12)),align:l.align||'start',justify:l.justify||'start',gridColumns:Math.max(1,Math.round(U.num(l.gridColumns,d.layout?.gridColumns||d.props?.columns||3))),order:U.num(l.order,0),locked:!!l.locked,aspectLocked:!!l.aspectLocked,overflow:l.overflow||'visible'},l||{});}
function placeholder(label){return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="420"><rect width="100%" height="100%" fill="#dce3f5"/><text x="50%" y="52%" text-anchor="middle" fill="#52607a" font-family="Arial" font-size="38">${label}</text></svg>`)}
M.create=(type,over={})=>{const d=defs[type]||defs.text,n={id:U.uid('node'),type:defs[type]?type:'text',name:d.label,text:d.defaultText||'',props:U.clone(d.props)||{},style:Object.assign({},U.clone(d.style)||{}),children:[],interactions:[],allowChildren:!!d.container,layout:normalizeLayout(Object.assign({},U.clone(d.layout)||{},U.clone(over.layout)||{}),type,0),meta:{createdAt:Date.now()}};if(type==='image')n.props.src=placeholder('Bunaa');if(type==='gallery')n.props.images=[placeholder('1'),placeholder('2'),placeholder('3')];if(over.id)n.id=over.id;if(over.name)n.name=over.name;if(over.text!==undefined)n.text=over.text;n.props=Object.assign(n.props,U.clone(over.props)||{});n.style=Object.assign(n.style,U.clone(over.style)||{});n.children=U.clone(over.children)||[];n.interactions=U.clone(over.interactions)||[];n.layout=normalizeLayout(Object.assign(n.layout,U.clone(over.layout)||{}),n.type,0);return M.normalizeNode(n)};
M.normalizeNode=(n,index=0,depth=0)=>{n.id=n.id||U.uid('node');n.type=defs[n.type]?n.type:'text';n.name=String(n.name||M.label(n.type));n.text=String(n.text??'');n.props=n.props&&typeof n.props==='object'?n.props:{};n.style=n.style&&typeof n.style==='object'?n.style:{};n.children=Array.isArray(n.children)?n.children:[];n.interactions=Array.isArray(n.interactions)?n.interactions:[];n.allowChildren=M.isContainer(n.type);n.layout=normalizeLayout(n.layout||{},n.type,depth);if(n.layout.widthMode==='fixed')n.layout.width=Math.max(20,U.num(n.layout.width,defs[n.type].layout?.width||120));else n.layout.width=n.layout.width==null?null:Math.max(20,U.num(n.layout.width,120));if(n.layout.heightMode==='fixed')n.layout.height=Math.max(1,U.num(n.layout.height,defs[n.type].layout?.height||60));else n.layout.height=n.layout.height==null?null:Math.max(1,U.num(n.layout.height,60));n.children.forEach((c,i)=>M.normalizeNode(c,i,depth+1));return n};
M.walk=(nodes,fn,parent=null)=>{(nodes||[]).forEach(n=>{fn(n,parent);if(n.children?.length)M.walk(n.children,fn,n)})};
M.find=(nodes,id)=>{let out=null;M.walk(nodes,n=>{if(n.id===id)out=n});return out};
M.parentOf=(nodes,id)=>{let out=null;M.walk(nodes,(n,p)=>{if(n.id===id)out=p});return out};
M.ancestors=(nodes,id)=>{const out=[];let p=M.parentOf(nodes,id);while(p){out.push(p);p=M.parentOf(nodes,p.id)}return out};
M.contains=(root,id)=>{let found=false;M.walk(root?.children||[],n=>{if(n.id===id)found=true});return found};
M.remove=(nodes,id)=>{for(let i=0;i<nodes.length;i++){if(nodes[i].id===id)return nodes.splice(i,1)[0];const r=M.remove(nodes[i].children||[],id);if(r)return r}return null};
M.insert=(nodes,node,parentId,index)=>{if(parentId){const p=M.find(nodes,parentId);if(!p||!p.allowChildren)return false;const i=index==null?p.children.length:Math.max(0,index);p.children.splice(i,0,node);return true}const i=index==null?nodes.length:Math.max(0,index);nodes.splice(i,0,node);return true};
M.reparent=(nodes,id,parentId,index)=>{if(id===parentId)return false;const moving=M.find(nodes,id);if(!moving)return false;if(parentId&&M.contains(moving,parentId))return false;const removed=M.remove(nodes,id);if(!removed)return false;return M.insert(nodes,removed,parentId,index)};
function starter(){const page={id:U.uid('page'),name:'الرئيسية',slug:'home',nodes:[]};const hero=M.create('hero',{text:'ابنِ موقعك بسرعة',layout:{x:46,y:40,widthMode:'fixed',width:760}});hero.interactions=[{id:U.uid('int'),event:'click',action:'animate',effect:'pulse'}];const stack=M.create('stack',{name:'محتوى رئيسي',layout:{x:46,y:210,widthMode:'fixed',width:420,gap:14}});stack.children=[M.create('heading',{text:'مرحبًا بك في بَنّاء'}),M.create('text',{text:'غيّر التخطيط إلى Stack أو Grid، أو استخدم الوضع الحر لتحريك أي عنصر بدقة.'}),M.create('button',{text:'جرّب التفاعل'})];const cards=M.create('grid',{name:'بطاقات',layout:{x:510,y:210,widthMode:'fixed',width:420,gridColumns:3,gap:14}});cards.children=[M.create('card',{text:'بطاقة 1'}),M.create('card',{text:'بطاقة 2'}),M.create('card',{text:'بطاقة 3'})];const footer=M.create('footer',{layout:{x:46,y:520,widthMode:'fixed',width:884}});page.nodes=[hero,stack,cards,footer];return {schema:M.VERSION,name:'مشروعي الأول',theme:{...shared,background:'#ffffff'},pages:[page],activePageId:page.id}}
M.createProject=()=>starter();
M.migrateProject=project=>{if(!project||!Array.isArray(project.pages))return M.createProject();const p=U.clone(project);p.pages.forEach((page,pi)=>{page.id=page.id||U.uid('page');page.name=page.name||`صفحة ${pi+1}`;page.slug=page.slug||'page-'+page.id.slice(-6);M.walk(page.nodes,(n)=>{if(n.layout?.widthMode==='auto')n.layout.widthMode='hug';if(n.layout?.heightMode==='auto')n.layout.heightMode='hug';if(n.layout?.display==null)n.layout.display=(n.type==='stack'?'flex':n.type==='grid'?'grid':'block');if(n.type==='stack')n.layout.direction=n.props?.direction==='horizontal'?'row':'column';if(n.type==='grid')n.layout.gridColumns=Math.max(1,Math.round(U.num(n.props?.columns,3)))})});return p};
M.normalizeProject=project=>{let p=M.migrateProject(project);p.schema=M.VERSION;p.name=p.name||'مشروعي';p.theme=p.theme&&typeof p.theme==='object'?p.theme:{...shared,background:'#fff'};p.pages=Array.isArray(p.pages)&&p.pages.length?p.pages:[M.createProject().pages[0]];const ids=new Set(),pages=new Set();p.pages.forEach((page,i)=>{page.id=page.id||U.uid('page');while(pages.has(page.id))page.id=U.uid('page');pages.add(page.id);page.name=page.name||`صفحة ${i+1}`;page.slug=page.slug||`page-${page.id.slice(-6)}`;page.nodes=Array.isArray(page.nodes)?page.nodes:[];M.walk(page.nodes,(n,parent)=>{while(!n.id||ids.has(n.id))n.id=U.uid('node');ids.add(n.id);M.normalizeNode(n,0,parent?1:0);n.interactions=n.interactions.filter(rule=>rule&&rule.event&&rule.action);});});p.activePageId=p.pages.some(x=>x.id===p.activePageId)?p.activePageId:p.pages[0].id;return p};
w.Bunaa.Model=M;
})(window);