(function(w){
'use strict';
const U=w.Bunaa.Core,M=w.Bunaa.Model,C=w.Bunaa.Catalog,UI={};
UI.toast=message=>{const box=U.get('toast');box.textContent=message;box.classList.remove('hidden');clearTimeout(UI.toastTimer);UI.toastTimer=setTimeout(()=>box.classList.add('hidden'),1800)};
UI.field=(label,id,value,type='text',extra='')=>`<label class="field"><span>${U.esc(label)}</span><input id="${id}" class="prop-input" type="${type}" value="${U.esc(value??'')}" ${extra}></label>`;
UI.selectField=(label,id,value,options)=>`<label class="field"><span>${U.esc(label)}</span><select id="${id}" class="prop-select">${options.map(([v,t])=>`<option value="${U.esc(v)}" ${v===value?'selected':''}>${U.esc(t)}</option>`).join('')}</select></label>`;
UI.renderLibrary=store=>{U.get('categoryBar').innerHTML=C.categories.map(c=>`<button type="button" class="chip ${store.ui.category===c?'active':''}" data-category="${U.esc(c)}">${U.esc(c)}</button>`).join('');const items=C.search(store.ui.search,store.ui.category);U.get('library').innerHTML=items.length?items.map(x=>`<button class="library-card ${x.container?'container-card':''}" type="button" draggable="true" data-add-type="${x.type}"><span class="lib-icon">${U.esc(x.icon)}</span><span class="lib-copy"><b>${U.esc(x.name)}</b><small>${x.container?'حاوية • تقبل أبناء':x.category}</small></span><i>＋</i></button>`).join(''):'<div class="panel-empty">لا توجد نتائج.</div>'};
function layerRows(nodes,store,depth=0){return nodes.map(n=>{const open=store.ui.collapsedLayers[n.id]!==true;const kids=n.children?.length?`<div class="layer-children ${open?'':'hidden'}">${layerRows(n.children,store,depth+1)}</div>`:'';return `<div class="layer-row ${store.ui.selectedIds.includes(n.id)?'active':''}" data-layer-id="${U.esc(n.id)}" style="--depth:${depth}"><button class="layer-caret ${n.children.length?'':'empty'}" data-layer-toggle="${U.esc(n.id)}">${n.children.length?(open?'▾':'▸'):''}</button><span class="layer-icon">${U.esc(M.icon(n.type))}</span><span class="layer-main"><b>${U.esc(n.name)}</b><small>${U.esc(M.label(n.type))}${n.children.length?' • '+n.children.length+' أبناء':''}</small></span><button data-layer-action="up" title="أعلى">↑</button><button data-layer-action="down" title="أسفل">↓</button><button data-layer-action="duplicate" title="نسخ">⧉</button><button data-layer-action="delete" title="حذف">×</button></div>${kids}`}).join('')}
UI.renderLayers=store=>{const p=store.activePage();U.get('layers').innerHTML=p?.nodes.length?'<div class="layers-note">Navigator: يمكنك تحديد أكثر من عنصر بـShift.</div>'+layerRows(p.nodes,store):'<div class="panel-empty">الصفحة فارغة.</div>'};
UI.renderInspector=store=>{const ids=store.ui.selectedIds,n=ids.length===1?store.find(ids[0]):null,empty=U.get('inspectorEmpty'),box=U.get('inspector');if(ids.length!==1||!n){empty.classList.remove('hidden');box.classList.add('hidden');U.get('inspectorHint').textContent=ids.length>1?`${ids.length} عناصر محددة`:'حدد عنصرًا';return}empty.classList.add('hidden');box.classList.remove('hidden');U.get('inspectorHint').textContent=M.label(n.type);const l=n.layout,s=n.style||{},p=n.props||{};const parent=store.parentOf(n.id);
 box.innerHTML=`<div class="selected-card"><div class="selected-icon">${U.esc(M.icon(n.type))}</div><div><strong>${U.esc(n.name)}</strong><small>${U.esc(M.label(n.type))} • ${U.esc(n.id)}</small></div></div><div class="inspector-actions"><button id="focusElement" class="soft-btn">◎ تركيز</button><button id="duplicateNode" class="soft-btn">⧉ نسخ</button><button id="deleteNode" class="danger-btn">حذف</button></div>`+
 `<details open><summary>أساسي</summary>${UI.field('اسم العنصر','pName',n.name)}${UI.field('النص','pText',n.text)}</details>`+
 `<details open><summary>Layout</summary><div class="field-grid">${UI.selectField('Display','pDisplay',l.display,[['block','Block'],['flex','Flex'],['grid','Grid'],['inline-flex','Inline Flex'],['inline-block','Inline Block']])}${UI.selectField('Position','pPosition',l.position,[['absolute','Free / Absolute'],['relative','Relative / Flow']])}</div><div class="field-grid">${UI.selectField('العرض','pWidthMode',l.widthMode,[['hug','Hug content'],['fill','Fill'],['fixed','Fixed']])}${UI.field('قيمة العرض','pWidth',l.width??'', 'number',l.widthMode==='fixed'?'':'disabled')}</div><div class="field-grid">${UI.selectField('الارتفاع','pHeightMode',l.heightMode,[['hug','Hug content'],['fill','Fill'],['fixed','Fixed']])}${UI.field('قيمة الارتفاع','pHeight',l.height??'','number',l.heightMode==='fixed'?'':'disabled')}</div><div class="field-grid">${UI.field('X','pX',Math.round(l.x),'number')}${UI.field('Y','pY',Math.round(l.y),'number')}</div><div class="field-grid">${UI.field('Min W','pMinW',l.minWidth??'','number')}${UI.field('Max W','pMaxW',l.maxWidth??'','number')}</div><div class="field-grid">${UI.field('Min H','pMinH',l.minHeight??'','number')}${UI.field('Max H','pMaxH',l.maxHeight??'','number')}</div><div class="field-grid">${UI.field('Gap','pGap',l.gap,'number')}${UI.field('الأعمدة','pCols',l.gridColumns,'number',l.display==='grid'?'':'disabled')}</div><div class="field-grid">${UI.selectField('Direction','pDirection',l.direction,[['row','Row'],['column','Column']])}${UI.selectField('Align','pAlign',l.align,[['start','Start'],['center','Center'],['end','End'],['stretch','Stretch']])}</div><div class="field-grid">${UI.selectField('Justify','pJustify',l.justify,[['start','Start'],['center','Center'],['end','End'],['between','Space Between'],['around','Space Around']])}${UI.selectField('Overflow','pOverflow',l.overflow,[['visible','Visible'],['hidden','Hidden'],['auto','Auto']])}</div><label class="check-row"><input id="pWrap" type="checkbox" ${l.wrap?'checked':''}> <span>Wrap</span></label><label class="check-row"><input id="pLocked" type="checkbox" ${l.locked?'checked':''}> <span>قفل العنصر</span></label><label class="check-row"><input id="pAspect" type="checkbox" ${l.aspectLocked?'checked':''}> <span>قفل النسبة</span></label><button id="saveLayout" class="primary-btn full">حفظ التخطيط</button></details>`+
 `<details><summary>Spacing</summary><div class="field-grid">${UI.field('Padding T','pPT',s.paddingTop??s.padding??0,'number')}${UI.field('Padding R','pPR',s.paddingRight??s.padding??0,'number')}</div><div class="field-grid">${UI.field('Padding B','pPB',s.paddingBottom??s.padding??0,'number')}${UI.field('Padding L','pPL',s.paddingLeft??s.padding??0,'number')}</div></details>`+
 `<details><summary>Appearance</summary><div class="field-grid">${UI.field('Font size','pFont',s.fontSize??16,'number')}${UI.field('Radius','pRadius',s.radius??0,'number')}</div><div class="field-grid">${UI.field('Background','pBg',s.background??'')}${UI.field('Color','pColor',s.color??'')}</div>${UI.field('Border','pBorder',s.border??'')}${UI.field('Shadow','pShadow',s.shadow??'')}${UI.field('Opacity','pOpacity',s.opacity??1,'number','min="0" max="1" step="0.05"')}</details>`+
 `<details><summary>المحتوى</summary>${n.props?.href!==undefined?UI.field('الرابط','pHref',p.href):''}${n.props?.src!==undefined?UI.field('Source','pSrc',p.src):''}${n.props?.alt!==undefined?UI.field('Alt','pAlt',p.alt):''}${n.props?.placeholder!==undefined?UI.field('Placeholder','pPlaceholder',p.placeholder):''}${n.props?.label!==undefined?UI.field('Label','pLabel',p.label):''}</details>`+
 `<details open><summary>Nested content</summary><div class="nested-callout"><strong>${n.allowChildren?'هذا العنصر حاوية':'عنصر نهائي'}</strong><span>${n.allowChildren?'يمكنك وضع عناصر داخله بالسحب، أو إنشاء ابن مباشر.':'يمكن تحويله إلى عنصر داخل حاوية أخرى من خلال السحب.'}</span>${n.allowChildren?'<button id="addChildNode" class="soft-btn full">＋ إضافة عنصر داخله</button>':''}</div>${parent?`<button id="detachNode" class="soft-btn full">↥ إخراج من الحاوية</button>`:''}</details>`;
};
UI.renderInteractions=store=>{const n=store.ui.selectedIds.length===1?store.find(store.ui.selectedIds[0]):null,box=U.get('interactionPanel');if(!n){box.innerHTML='<div class="panel-empty">حدد عنصرًا واحدًا أولًا.</div>';return}const ev=w.Bunaa.Interactions.events,ac=w.Bunaa.Interactions.actions;box.innerHTML=`<div class="interaction-summary"><strong>${U.esc(n.name)}</strong><span>${n.interactions.length} تفاعل</span></div>${n.interactions.length?n.interactions.map((x,i)=>`<div class="interaction-card"><div><b>${U.esc(ev.find(e=>e[0]===x.event)?.[1]||x.event)}</b><span>→ ${U.esc(ac.find(a=>a[0]===x.action)?.[1]||x.action)}</span></div><button data-remove-interaction="${i}">×</button></div>`).join(''):'<div class="interaction-empty">لا توجد تفاعلات.</div>'}<div class="interaction-form"><label>عند<select id="intEvent">${ev.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><label>نفّذ<select id="intAction">${ac.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><div id="intExtra"></div><button id="addInteraction" class="primary-btn full">＋ إضافة التفاعل</button></div>`;UI.renderInteractionExtra(store)};
UI.renderInteractionExtra=store=>{const action=U.get('intAction')?.value,box=U.get('intExtra');if(!box)return;const n=store.ui.selectedIds.length===1?store.find(store.ui.selectedIds[0]):null;if(action==='animate')box.innerHTML='<label>الحركة<select id="intEffect"><option value="pulse">Pulse</option><option value="fade">Fade</option><option value="slide">Slide</option><option value="shake">Shake</option><option value="zoom">Zoom</option></select></label>';else if(action==='navigate')box.innerHTML='<label>الصفحة<select id="intPage">'+store.project.pages.map(p=>`<option value="${U.esc(p.id)}">${U.esc(p.name)}</option>`).join('')+'</select></label>';else if(action==='url')box.innerHTML='<label>الرابط<input id="intUrl" placeholder="https://example.com"></label>';else if(action==='text')box.innerHTML='<label>النص الجديد<input id="intValue"></label>';else if(['show','hide','toggle'].includes(action))box.innerHTML='<label>العنصر الهدف<select id="intTarget">'+store.all().filter(x=>x.node.id!==n?.id).map(x=>`<option value="${U.esc(x.node.id)}">${U.esc(x.node.name)} — ${U.esc(M.label(x.node.type))}</option>`).join('')+'</select></label>';else box.innerHTML=''};
UI.refresh=store=>{const p=store.activePage();U.get('pageTitle').textContent=p?.name||'';U.get('canvasPageName').textContent=p?.name||'';const selected=store.ui.selectedIds.map(id=>store.find(id)).filter(Boolean);U.get('selectionState').textContent=selected.length?(selected.length===1?`${M.label(selected[0].type)} • ${selected[0].name}`:`${selected.length} عناصر محددة`):'لا يوجد تحديد';U.get('saveState').textContent=store.saved?'محفوظ':'جاري الحفظ';U.get('pageSelect').innerHTML=store.project.pages.map(pg=>`<option value="${U.esc(pg.id)}" ${pg.id===store.project.activePageId?'selected':''}>${U.esc(pg.name)}</option>`).join('');U.get('undoBtn').disabled=!store.canUndo;U.get('redoBtn').disabled=!store.canRedo;['elements','layers','interactions'].forEach(t=>{U.q(`[data-tab="${t}"]`).classList.toggle('active',store.ui.tab===t);U.get(t+'Tab').classList.toggle('hidden',store.ui.tab!==t)});U.get('traineeTip').classList.toggle('hidden',store.ui.mode!=='trainee');if(store.ui.mode==='trainee')U.get('traineeTip').innerHTML='<strong>الوضع التعليمي</strong><span>Layout = Block/Flex/Grid، والحجم = Hug/Fill/Fixed. Shift للتحديد المتعدد وSpace للـPan.</span>';};
w.Bunaa.UI=UI;
})(window);